### ISSUE TITLE
CUDA SETUP: Required library version not found: libbitsandbytes_cuda114_nocublaslt.so.

### ISSUE THREAD

**Issue by jeremistderechte** [TimDettmers/bitsandbytes#1057]
### System Info

Ubuntu Server 22.04 LTS with Python 3.11 and Tesla K40. PyTorch Version is 2.3.0 compiled from source and functional. 

### Reproduction

(bitsandbytes) jeremy@compute-main:~/Downloads/bitsandbytes$ python -m bitsandbytes
/home/jeremy/Downloads/bitsandbytes/bitsandbytes/cuda_setup/main.py:122: UserWarning: 

================================================================================
WARNING: Manual override via BNB_CUDA_VERSION env variable detected!
BNB_CUDA_VERSION=XXX can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64
Loading: libbitsandbytes_cuda114_nocublaslt114In.so
================================================================================

  warn(
False

===================================BUG REPORT===================================
/home/jeremy/Downloads/bitsandbytes/bitsandbytes/cuda_setup/main.py:183: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
/home/jeremy/Downloads/bitsandbytes/bitsandbytes/cuda_setup/main.py:183: UserWarning: /home/jeremy/miniconda3/envs/bitsandbytes did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0', 'libcudart.so.12.1', 'libcudart.so.12.2'] as expected! Searching further paths...
  warn(msg)
/home/jeremy/Downloads/bitsandbytes/bitsandbytes/cuda_setup/main.py:183: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0', 'libcudart.so.12.1', 'libcudart.so.12.2'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda-11.4/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda-11.4/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might mismatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
/home/jeremy/Downloads/bitsandbytes/bitsandbytes/cuda_setup/main.py:183: UserWarning: /usr/local/cuda-11.4/lib64::/usr/local/cuda/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0', 'libcudart.so.12.1', 'libcudart.so.12.2'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/home/jeremy/Downloads/bitsandbytes/bitsandbytes/cuda_setup/main.py:183: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0', 'libcudart.so.12.1', 'libcudart.so.12.2'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might mismatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=114, Highest Compute Capability: 3.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
/home/jeremy/Downloads/bitsandbytes/bitsandbytes/cuda_setup/main.py:183: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cuda114_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=114 make cuda11x_nomatmul
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/jeremy/Downloads/bitsandbytes/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, research, utils
  File "/home/jeremy/Downloads/bitsandbytes/bitsandbytes/research/__init__.py", line 2, in <module>
    from .autograd._functions import (
  File "/home/jeremy/Downloads/bitsandbytes/bitsandbytes/research/autograd/_functions.py", line 8, in <module>
    from bitsandbytes.autograd._functions import GlobalOutlierPooler, MatmulLtState
  File "/home/jeremy/Downloads/bitsandbytes/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import get_inverse_transform_indices, undo_layout
  File "/home/jeremy/Downloads/bitsandbytes/bitsandbytes/autograd/_functions.py", line 10, in <module>
    import bitsandbytes.functional as F
  File "/home/jeremy/Downloads/bitsandbytes/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/jeremy/Downloads/bitsandbytes/bitsandbytes/cextension.py", line 17, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

### Expected behavior

Since the compile process changed as stated in https://huggingface.co/docs/bitsandbytes/main/en/compiling i am not sure if i am missing something when compiling for Kepler (sm_35), because the compilation ends successfully and it detects the nvcc Compiler and arch correctly. But when testing bitsandbytes it cant find libbitsandbytes_cuda114_nocublaslt.so.. So I assume I am missing something, that is not written down in the doc. The last supported version for kepler (0.39.0) works on my machine, so I assume everything else should be configured correctly....

"Compilation for Kepler Architecture

From version 0.39.1, bitsandbytes no longer includes Kepler binaries in pip installations, requiring manual compilation. Follow the general steps and use cuda11x_nomatmul_kepler for Kepler-targeted compilation." (https://huggingface.co/docs/bitsandbytes/main/en/compiling ) as the webiste writes is for the old compilation process, isnt it?

**Comment by matthewdouglas** [comment]
Hi,
You're right that the docs state information related to Kepler for the old make process.

For the cmake build with Kepler, please use `-DNO_CUBLASLT` with versions below 0.45.0. This should create libbitsandbytes_cuda114_nocublaslt.so. With v0.45.0 and newer, you should be able to compile from source for Kepler without the additional flag.

Please note that given the age of Kepler, we're unlikely to continue to provide source compatibility in the future.

**Comment by jeremistderechte** [comment]
Hi,

thanks for the reply. I'll throw in my Tesla K40 in my server soon to test it out. I mean you're right that Kepler is really old by this point, but I was just interested to know how capable the GK110 still was when I opened this issue....

**Comment by TimDettmers** [comment]
Closing this issue. The Tesla K40 uses the Kepler architecture (compute capability 3.5), which is not included in pre-built binaries. The maintainer provided source build instructions in the comments. Given Kepler's age, continued source compatibility is unlikely in future releases.
