### ISSUE TITLE
Installing bitsandbytes on windows

### ISSUE THREAD

**Issue by deepakpokkalla** [TimDettmers/bitsandbytes#1085]
Hello, I 'm trying to install bitsandbytes in my windows laptop. I have created an environment with miniforge3 and installed CUDA and pytorch along with some other packages using conda install. I did pip install bitsandbytes, however I am facing an error.  I have another error when I ran python -m bitsandbytes. Any suggestions on how to resolve this? Thanks in advance. 

1. Checking CUDA version 
(dl-pii) C:\Users\dpa>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Nov__3_17:51:05_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.3, V12.3.103
Build cuda_12.3.r12.3/compiler.33492891_0

2. The error when I ran my code. 

================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
C:\Users\dpa13\AppData\Local\miniforge3\envs\dl-pii\Lib\site-packages\bitsandbytes\cuda_setup\main.py:167: UserWarning: C:\Users\dpa13\AppData\Local\miniforge3\envs\dl-pii did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {WindowsPath('/Windows/Symbols*http'), WindowsPath('//msdl.microsoft.com/download/symbols'), WindowsPath('SRV*C')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.6.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Users\dpa13\AppData\Local\miniforge3\envs\dl-pii\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.so...
[WinError 193] %1 is not a valid Win32 application
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://raw.githubusercontent.com/TimDettmers/bitsandbytes/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\dpa13\AppData\Local\miniforge3\envs\dl-pii\Lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\dpa13\AppData\Local\miniforge3\envs\dl-pii\Lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\dpa13\AppData\Local\miniforge3\envs\dl-pii\Lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\dpa13\AppData\Local\miniforge3\envs\dl-pii\Lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\dpa13\AppData\Local\miniforge3\envs\dl-pii\Lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\dpa13\AppData\Local\miniforge3\envs\dl-pii\Lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

3. Error when I ran python -m bistanadbytes 

![image](https://github.com/TimDettmers/bitsandbytes/assets/106105228/346fac64-c2f2-48f8-91fc-3400b7df6654)

**Comment by MustfainTariq** [comment]
Hi. did you find the solution? I am facing the same problem.

**Comment by matthewdouglas** [comment]
The currently released wheels on PyPI do not have Windows support. Support for Windows is currently being worked on. You would need to clone the `main` branch and [compile from source](https://huggingface.co/docs/bitsandbytes/main/en/installation?OS+system=Windows) for the time being.

Alternatively, you could grab a [development wheel](https://github.com/TimDettmers/bitsandbytes/actions/runs/8146317331/artifacts/1296417474) and try that out.

**Comment by Titus-von-Koeller** [comment]
Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗

**Comment by spydaz** [comment]
no its still problems on windows ! i cannot find out whihc cuda its working with ?? as well as pytorch version !! 
it seesm if i get the right pytorch then bitsandbytes cannot find the right dll 124 ??? 
and if i put the old verion then pytorch cannot see my gpu !!
i put my gpu to the orginal but the driver will automatically upgrade itself to the latest hence i forced to select which cuda and tools to work with !! ??

what is the correct one ?

pytorch only seems to want 12.3 ---- this is not working with bitandbytes --- and of i switch to 12.1 still bitsanbytes is looking fo the same dll ? why not the 121 verson ??
