### ISSUE TITLE
bitsandbytes searching *cuda*so only in /usr/local and does not support other paths

### ISSUE THREAD

**Issue by Parvez-Khan-1** [TimDettmers/bitsandbytes#1140]
### System Info

Operating System: Oracle Linux 7.9
Python Version: 3.10.10
GPU: NVIDIA A100
CUDA: 12.3
bitandbytes: 0.42.0

### Reproduction

To reproduce this issue:

- You should have cuda installed somewhere else other than /usr/local/ 
- export below environment variable

```
export PATH=/some_dir/cuda-12.3/bin:$PATH
export LD_LIBRARY_PATH=/some_dir//cuda-12.3/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/some_dir//cuda-12.3/
```

```
python -m bitsandbytes
```

Output:

```
python -m bitsandbytes
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "/sys_apps_01/python310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/sys_apps_01/python310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/ads_storage/e093857/venv/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 96, in <module>
    generate_bug_report_information()
  File "/ads_storage/e093857/venv/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 54, in generate_bug_report_information
    paths = find_file_recursive('/usr/local', '*cuda*so')
  File "/ads_storage/e093857/venv/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?
```

### Expected behavior

Ideally, it should look into CUDA_HOME and try to find the ```*cuda*so``` files there recursively

**Comment by matthewdouglas** [comment]
I do agree - we would ideally want it to find the CUDA libraries even if they're in a non-standard path. Note that this command is just for diagnostics though, to aid in helping a user determine how to set `LD_LIBRARY_PATH`. That could use some reworking as most of the time the libraries are going to be shipped with the PyTorch binaries.

That said, this issue might not reproduce the same way in 0.43.0 (example here is 0.42.0).

Relates to #1126

**Comment by Parvez-Khan-1** [comment]
@matthewdouglas  Seems like there is support for CUDA_PATHS variable in [0.43.0](https://github.com/TimDettmers/bitsandbytes/blob/0.43.0/bitsandbytes/__main__.py)

**Comment by fantasy-fish** [comment]
I am using the latest verison, but still have the same issue.

**Comment by TimDettmers** [comment]
Closing this issue. The CUDA search path limitation (only looking in `/usr/local`) was a known problem in the old `cuda_setup/main.py` module used in bitsandbytes 0.42.0. That entire module was replaced starting in v0.43.0 with a new library loading mechanism that uses PyTorch's CUDA detection instead of manual path searches.

If you're still hitting path issues on the **latest** bitsandbytes, please open a new issue.
