### ISSUE TITLE
 bitsandbytes cuda library error

### ISSUE THREAD

**Issue by parksez** [TimDettmers/bitsandbytes#1175]
### System Info

Python 3.10.14

### Reproduction

# 데이터셋 로드
dataset = load_dataset(superalloy_dataset, split="train")

# 4비트 양자화 QLoRA 파인튜닝 설정
compute_dtype = torch.float16
from transformers import BitsAndBytesConfig
quant_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=False
)

# 모델 로드
model = AutoModelForCausalLM.from_pretrained(
    base_model,
    quantization_config=quant_config,
    device_map={"cuda": 0} if torch.cuda.is_available() else {"cpu": 0}
)
model.config.use_cache = False
model.config.pretraining_tp = 1

# 토크나이저 로드 및 설정
tokenizer = AutoTokenizer.from_pretrained(base_model)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# PEFT 파라미터 설정 (예시)
from peft import LoraConfig
peft_params = LoraConfig(
    lora_alpha=16,
    lora_dropout=0.1,
    r=64,
    bias="none",
    task_type="CAUSAL_LM"
)

# 학습 파라미터 설정
training_params = TrainingArguments(
    output_dir="./results",
    num_train_epochs=20,  
    per_device_train_batch_size=2,
    gradient_accumulation_steps=1,
    optim="adamw",
    save_steps=100,
    logging_steps=100,
    learning_rate=2e-5,
    weight_decay=0.01,
    fp16=True,
    bf16=False,
    max_grad_norm=1.0,
    warmup_steps=500,
    lr_scheduler_type="linear",
    report_to="all"
)

# 학습기 초기화 및 학습 실행
trainer = Trainer(
    model=model,
    args=training_params,
    train_dataset=dataset,
    tokenizer=tokenizer
)
trainer.train()

# 학습된 모델 저장
model_path = "C:/Users/PSJ/Desktop/superalloy_dataset/trained_model_superalloy"
model.save_pretrained(model_path)
tokenizer.save_pretrained(model_path)

# 평가 준비
logging.set_verbosity(logging.CRITICAL)  

# 모델 및 토크나이저 로드
model = AutoModelForCausalLM.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

### Expected behavior

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
False
C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
  warn(msg)
C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: C:\Users\PSJ\AppData\Local\anaconda3\envs\text did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\PSJ\AppData\Local\anaconda3\envs\text\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by Titus-von-Koeller** [comment]
No description given, therefore closing the issue.
