### ISSUE TITLE
TypeError: Input tensors need to be on the same GPU, but found the following tensor and device combinations

### ISSUE THREAD

**Issue by rlanday** [TimDettmers/bitsandbytes#1179]
### System Info

I was using a Vast.ai server with 8x A100 GPUs, each with 80 GB of VRAM, and about 1814 GB of RAM (as reported by Vast):
```
root@C.10527886:~$ uname -r
5.15.0-1050-azure
root@C.10527886:~$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Reproduction

I don’t have an easy way to reproduce the problem. I started fine-tuning Mixtral using SFTTrainer, QLoRA, and DeepSpeed ZeRO-3 with 8x A100s and this bug occurred in the 6th epoch (perhaps it’s some sort of race condition):
```
{'loss': 1.8568, 'grad_norm': 0.035528212785720825, 'learning_rate': 4e-05, 'epoch': 0.0}
{'loss': 1.8158, 'grad_norm': 0.029280483722686768, 'learning_rate': 8e-05, 'epoch': 0.01}
{'loss': 1.8727, 'grad_norm': 0.030231980606913567, 'learning_rate': 0.00012, 'epoch': 0.01}
{'loss': 1.8823, 'grad_norm': 0.028545115143060684, 'learning_rate': 0.00016, 'epoch': 0.02}
{'loss': 1.8474, 'grad_norm': 0.026413191109895706, 'learning_rate': 0.0002, 'epoch': 0.02}
{'loss': 1.8512, 'grad_norm': 0.024209117516875267, 'learning_rate': 0.000199163179916318, 'epoch': 0.02}
  2%|██▋                                                                                                           | 6/244 [15:20<10:16:21, 155.39s/it]
Traceback (most recent call last):
  File "/root/train_bitsandbytes.py", line 117, in <module>
    trainer_stats = trainer.train()
  File "/opt/conda/lib/python3.10/site-packages/trl/trainer/sft_trainer.py", line 361, in train
    output = super().train(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 2118, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3036, in training_step
    loss = self.compute_loss(model, inputs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3059, in compute_loss
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/utils/operations.py", line 825, in forward
    return model_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/utils/operations.py", line 813, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/opt/conda/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/peft/peft_model.py", line 1129, in forward
    return self.base_model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 161, in forward
    return self.model.forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 1360, in forward
    outputs = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 161, in forward
    return self.model.forward(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 1360, in forward
    outputs = self.model(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 1217, in forward
    layer_outputs = self._gradient_checkpointing_func(
  File "/opt/conda/lib/python3.10/site-packages/torch/_compile.py", line 24, in inner
    return torch._dynamo.disable(fn, recursive)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 482, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 261, in forward
    outputs = run_function(*args)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 947, in forward
    hidden_states, router_logits = self.block_sparse_moe(hidden_states)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 877, in forward
    current_hidden_states = expert_layer(current_state) * routing_weights[top_x_list, idx_list, None]
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/mixtral/modeling_mixtral.py", line 803, in forward
    current_hidden_states = self.act_fn(self.w1(hidden_states)) * self.w3(hidden_states)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 468, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 574, in matmul_4bit
    out = F.gemv_4bit(A, B.t(), out, state=quant_state)
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1994, in gemv_4bit
    is_on_gpu([B, A, out, absmax, state.code])
  File "/opt/conda/lib/python3.10/site-packages/bitsandbytes/functional.py", line 432, in is_on_gpu
    raise TypeError(
TypeError: Input tensors need to be on the same GPU, but found the following tensor and device combinations:
 [(torch.Size([29360128, 1]), device(type='cuda', index=6)), (torch.Size([1, 4096]), device(type='cuda', index=6)), (torch.Size([1, 14336]), device(type='cuda', index=6)), (torch.Size([917504]), device(type='cuda', index=6)), (torch.Size([16]), device(type='cuda', index=0))]
```

I’m not 100% sure which part of the training stack contains the bug here, but I very briefly started debugging this and found some code in bitsandbytes that looks suspicious:
https://github.com/TimDettmers/bitsandbytes/blob/127788a96e123bb2e95ff9dbcc78672e4849cddc/bitsandbytes/nn/modules.py#L449

### Expected behavior

Training should not throw this error.

**Comment by rlanday** [comment]
Oh, and I had gradient checkpointing enabled, as you can see from the stack trace. I already found one bug with using both gradient checkpointing and LoRA that I had to work around:
https://github.com/huggingface/peft/issues/137#issuecomment-1445912413

so perhaps this is not a well-tested combination.

**Comment by satya77** [comment]
How did you solve it? I have the same issue with LoRA, with or without gradient checkpointing.

**Comment by rlanday** [comment]
I have not solved it. I tried again on 2024-07-26 but I ran into the same problem. I suppose it’s been long enough that maybe I should try it again but I’ve been thinking I’m probably going to have to debug it myself. It’s a little bit complicated but hopefully I can get to it soon.

**Comment by probaku1234** [comment]
I'm using SFTTrainer, QLoRA, and faced the same error. In my case, changing the `bnb_4bit_compute_dtype` value from `torch.float16` to `torch.bfloat16` resolved the error. 
```python
quant_config = BitsAndBytesConfig(
    load_in_8bit=False,  # 8bit 양자화는 flash attention 지원안하는 듯?
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16, # 양자화 사용시 float16으로 하면 에러남
)
model_load_confiig = {
    "torch_dtype": torch.bfloat16, # 양자화 사용시 float16으로 하면 에러남
    "attn_implementation": "flash_attention_2",
    "device_map": "auto",
    "local_files_only": True,
}
if quantization_settings.use_quantization:
    model_load_confiig["quantization_config"] = quant_config

model = AutoModelForCausalLM.from_pretrained(
    f"{base_model_path}/{model_id}",
    **model_load_confiig,
)
```

**Comment by rlanday** [comment]
I’m already doing that. I just finished reading the QLoRA paper and it does recommend using bfloat16 for optimal numerical precision, so I agree that that’s the right setting to use.

I’m going to try to debug this soon. I’m using DeepSpeed ZeRO-3 so the issue might be related to that.

**Comment by rlanday** [comment]
I’m trying my script again and I haven’t been able to reproduce the error. I did notice I didn’t have DeepSpeed set up properly (since I’m using SFTTrainer, I need to set the “deepspeed” param of the SFTConfig I’m passing in). Maybe we can close this.

**Comment by TimDettmers** [comment]
Closing per the reporter's suggestion — the issue could not be reproduced on retry. If this resurfaces, please open a new issue with a minimal reproduction.
