### ISSUE TITLE
AnimateDiff SDXL won't run

### ISSUE THREAD

**Issue by idesign2018** [TimDettmers/bitsandbytes#1209]
### System Info

Python 3.10.11
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

### Reproduction

===========================================================================
AnimateDiff SDXL
https://github.com/guoyww/AnimateDiff/tree/sdxl
Executing command line;
python --version&nvcc --version&"C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\scripts\activate.bat"&python -u -B -W ignore -m scripts.animate --exp_config config.yaml --L 16 --W 1024 --H 1024 --pretrained_model_path models/StableDiffusion&"C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\scripts\deactivate.bat"
===========================================================================

Python 3.10.11
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\huggingface_hub\utils\_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/models/StableDiffusion/resolve/main/tokenizer/vocab.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\transformers\utils\hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\huggingface_hub\file_download.py", line 1221, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\huggingface_hub\file_download.py", line 1325, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\huggingface_hub\file_download.py", line 1823, in _raise_on_head_call_error
    raise head_call_error
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\huggingface_hub\file_download.py", line 1722, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(url=url, proxies=proxies, timeout=etag_timeout, headers=headers)
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\huggingface_hub\file_download.py", line 1645, in get_hf_file_metadata
    r = _request_wrapper(
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\huggingface_hub\file_download.py", line 372, in _request_wrapper
    response = _request_wrapper(
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\huggingface_hub\file_download.py", line 396, in _request_wrapper
    hf_raise_for_status(response)
  File "C:\Users\idesign\AppData\Roaming\Visions of Chaos\Examples\MachineLearning\venv\voc_animatediffsdxl\lib\site-packages\huggingface_hub\utils\_errors.py", line 352, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoun

### Expected behavior

AnimateDiff SDXL cannot be run. Tried multiple times and the error persists.

**Comment by TimDettmers** [comment]
Closing this issue. The errors in this report originate in AnimateDiff/diffusers, not in bitsandbytes. If the issue persists, please report it to the AnimateDiff project.
