### ISSUE TITLE
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

### ISSUE THREAD

**Issue by fantasy-fish** [TimDettmers/bitsandbytes#1214]
### System Info

Debian 11, python3.10, cuda 12.1, accelerate 0.30.1

### Reproduction

python - m bitsandbytes

### Expected behavior

/home/chaiwei/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:147: UserWarning: /opt/conda did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /home/chaiwei/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/chaiwei/venv/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/home/chaiwei/venv/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 49, in generate_bug_report_information
    paths = find_file_recursive(os.environ['CONDA_PREFIX'], '*cuda*so')
  File "/home/chaiwei/venv/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

### **If I `import bitsandbytes` in python3.10, it shows the correct cuda info**
/home/chaiwei/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:147: UserWarning: /opt/conda did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /home/chaiwei/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...

**Comment by matthewdouglas** [comment]
Hi @fantasy-fish 
Thanks for reporting. This looks to be a bug in the diagnostics that are run with `python -m bitsandbytes`. At runtime these full diagnostics are not conducted, so for now you can simply ignore the failure with the diagnostic command.

cc: @Titus-von-Koeller

**Comment by TimDettmers** [comment]
Closing this issue. The maintainer confirmed this is a bug in the `python -m bitsandbytes` diagnostic script only, not in runtime behavior. The diagnostic code path has been reworked in recent releases. If you're still seeing issues at runtime (not just in the diagnostic command) on the latest version, please open a new issue.
