### ISSUE TITLE
NameError: name 'str2optimizer8bit_blockwise' is not defined

### ISSUE THREAD

**Issue by brucethemoose** [TimDettmers/bitsandbytes#123]
Hello, I am a humble end user running this script: https://github.com/kohya-ss/sd-scripts/blob/main/train_network.py

I seem to have run into an error in the bitsandbytes library itself, namely: 
```
Traceback (most recent call last):
  File "/home/alpha/clone/sd-scripts/train_db.py", line 332, in <module>
    train(args)
  File "/home/alpha/clone/sd-scripts/train_db.py", line 266, in train
    optimizer.step()
  File "/home/alpha/.local/lib/python3.10/site-packages/accelerate/optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 341, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 288, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/optim/optimizer.py", line 219, in wrapper
    out = func(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 263, in step
    self.update_step(group, p, gindex, pindex)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 504, in update_step
    F.optimizer_update_8bit_blockwise(
  File "/home/alpha/.local/lib/python3.10/site-packages/bitsandbytes/functional.py", line 972, in optimizer_update_8bit_blockwise
    str2optimizer8bit_blockwise[optimizer_name][1](
NameError: name 'str2optimizer8bit_blockwise' is not defined
steps:   0%|                                                                    | 0/1600 [00:01<?, ?it/s]
Traceback (most recent call last):
```

**Comment by brucethemoose** [comment]
Oh nevermind, this is a duplicate of #62
