### ISSUE TITLE
Can pascal ever be supported? Is it a lost cause?

### ISSUE THREAD

**Issue by Ph0rk0z** [TimDettmers/bitsandbytes#131]
I have a quadro built on pascal and see a bunch of people with P40 posting here. Someone has compiled the library for windows and is using it on a 10xx series geforce for training.

I see some docs and forum post from nvidia.
https://developer.nvidia.com/blog/new-pascal-gpus-accelerate-inference-in-the-data-center/
https://forums.developer.nvidia.com/t/about-cublasgemm-int8-support/48483

But the problem is that int8 multiplication function. 

Is it a hard blocking issue that we should give up hope on? The most accessible high vram GPUs are in this series.

Also, since they are indeed running this for training, does this mean other 8 bit operations are currently working and it's just the one required for language models?

**Comment by TimDettmers** [comment]
This is supported in the latest release. Please update to 0.37.0 and let me know if you are still having troubles.

**Comment by henk717** [comment]
@TimDettmers Maxwell user here (Nvidia M40), when trying to import the library I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henk717/koboldai/runtime/envs/koboldai/lib/python3.8/site-packages/bitsandbytes/__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "/home/henk717/koboldai/runtime/envs/koboldai/lib/python3.8/site-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "/home/henk717/koboldai/runtime/envs/koboldai/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "/home/henk717/koboldai/runtime/envs/koboldai/lib/python3.8/site-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/henk717/koboldai/runtime/envs/koboldai/lib/python3.8/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/henk717/koboldai/runtime/envs/koboldai/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 92, in run_cuda_setup
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/henk717/koboldai/runtime/envs/koboldai/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 395, in evaluate_cuda_setup
    has_cublaslt = is_cublasLt_compatible(cc)
  File "/home/henk717/koboldai/runtime/envs/koboldai/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 153, in is_cublasLt_compatible
    cuda_setup.add_log_entry("WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!", is_warning=True)
NameError: name 'cuda_setup' is not defined
```

**Comment by Ph0rk0z** [comment]
Thank you for fixing it so quickly. Unfortunately I have the same problem as henk does above. In addition to trying kobold, I used https://github.com/oobabooga/text-generation-webui and got the same "NameError: name 'cuda_setup' is not defined"

When I tried searching this was related to it not being able to find the cuda libs?

**Comment by henk717** [comment]
The same environment I use for Kobold works on a newer GPU, so I think the not finding the libs error is deceiving.

**Comment by Ph0rk0z** [comment]
True, both of of these projects I tried use a different virtual environment with cuda installed.

**Comment by Ph0rk0z** [comment]
I am able to bypass the error by doing this:

```
def is_cublasLt_compatible(cc):
    has_cublaslt = False
    if cc is not None:
        cc_major, cc_minor = cc.split('.')
        #if int(cc_major) < 7 or (int(cc_major) == 7 and int(cc_minor) < 5):
            #CUDASetup.add_log_entry("WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!", is_warning=True)
        #else:
         #   has_cublaslt = True
    return has_cublaslt

```

But now I get an error like this: https://pastebin.com/H0gvKSMF when I try to generate text.

**Comment by henk717** [comment]
KoboldAI isn't going to be a good example because we do things quite different from other projects and have no official 8-bit support yet. I recommend using something else first based on more basic HF functions.

**Comment by Ph0rk0z** [comment]
Any suggestions? I also had the same failure in the textgen-webui that natively supports 8 bit. From looking it up, it's some kind of divide by zero error due to torch.
