### ISSUE TITLE
RuntimeError: Input type (c10::Half) and bias type (float) should be the same

### ISSUE THREAD

**Issue by caldwecg** [TimDettmers/bitsandbytes#140]
Hello!
Running Shivam Srirao's new imagic and encountered the following error. Basically reproduced his Colab (https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/imagic/Imagic_Stable_Diffusion.ipynb#scrollTo=BzM7j0ZSc_9c) in AWS  and don't even know how to start dissecting this error. It gets thrown after "optimizing embedding" completes and when the fine-tuning begins. Appreciate any/all help!

Traceback (most recent call last):
  File "/home/ubuntu/train_imagic.py", line 398, in <module>
    main()
  File "/home/ubuntu/train_imagic.py", line 380, in main
    train_loop(progress_bar, optimizer, unet.parameters())
  File "/home/ubuntu/train_imagic.py", line 336, in train_loop
    noise_pred = unet(noisy_latents, timesteps, optimized_embeddings).sample
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 335, in forward
    sample = self.conv_in(sample)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (c10::Half) and bias type (float) should be the same

**Comment by akatsukisun2020** [comment]
i have the same problem now

**Comment by balazon** [comment]
I got the same error for mask2former:
https://huggingface.co/facebook/mask2former-swin-large-mapillary-vistas-panoptic
