### ISSUE TITLE
remove_non_existing_dirs tries to access system dir

### ISSUE THREAD

**Issue by chris-aeviator** [TimDettmers/bitsandbytes#157]
When unsing bitsandbytes for huggingface (`model = AutoModelForCausalLM.from_pretrained("bloom", device_map="auto", load_in_8bit=True)`), 

bitsandbytes tries to remove (as it seems) a system directory (!!)

```
  File "/home/myUser/myproject/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 166, in remove_non_existent_dirs
    if path.exists():
  File "/usr/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/var/lib/lightdm-data/myUser'

``` 

python 3.10
bitsandbytes 0.37.0 
arch linux

**Comment by chris-aeviator** [comment]
to reproduce, set an environment variable to a system dir (see https://github.com/TimDettmers/bitsandbytes/issues/35 for more info)

`SOME_ARBITRARY_ENVIRONMENT_VAR=/etc python myAppUsingBitsandbytes.py`

**Comment by svgsponer** [comment]
Same Problem here. However not dependent on anything with hugging face. A simple import in the REPL is enough to reproduce the error.

`Exception importing 8bit adam: [Errno 13] Permission denied: '/var/lib/lightdm-data/myUser'
Traceback (most recent call last):
  File "myApp.py", line 363, in inner_loop
    import bitsandbytes as bnb
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 113, in <module>
    lib = CUDASetup.get_instance().lib
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 109, in get_instance
    cls._instance.initialize()
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 59, in initialize
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 122, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 110, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 51, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 46, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 23, in remove_non_existent_dirs
    raise exc
  File "/myPath/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py", line 19, in remove_non_existent_dirs
    if path.exists():
  File "/usr/local/lib/python3.10/pathlib.py", line 1288, in exists
    self.stat()
  File "/usr/local/lib/python3.10/pathlib.py", line 1095, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/var/lib/lightdm-data/myUser'
`

Python: 3.10.0
Bitsandbytes: 0.35.4
System: Arch

**Comment by codito** [comment]
> PermissionError: [Errno 13] Permission denied: '/var/lib/lightdm-data/myUser'

Workaround: find and set the env var to empty. E.g.

```
> set XDG_GREETER_DATA_DIR=
> # run the python code
```

**Comment by makermotion** [comment]
This is still relevant for RHEL when load_in_4bit set to True using transformers.AutoModelForCausalLM.from_pretrained

I got the following:
PermissionError: [Errno 13] Permission denied: '/fs/applications/jupyterhub...

bitsandbytes==0.39.1
transformers==4.31.0.dev0

**Comment by AashayBhupendraD0shi** [comment]
I have the same issue. I've read at a few places that changing your file permissions (like role "storage admin" in GCP) will resolve the issue. The above commit resolves it only for arch linux. Is there any other way to resolve the issue on ubuntu?
