### ISSUE TITLE
CUDA detection failed. Either CUDA driver not installed, CUDA not installed, or you have multiple conflicting CUDA libraries!

### ISSUE THREAD

**Issue by Broccolitop** [TimDettmers/bitsandbytes#168]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: TODO: compile library for specific version: libbitsandbytes_cuda116.dll
CUDA SETUP: Defaulting to libbitsandbytes.so...
CUDA SETUP: CUDA detection failed. Either CUDA driver not installed, CUDA not installed, or you have multiple conflicting CUDA libraries!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
Traceback (most recent call last):
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\train_network.py", line 573, in <module>
    train(args)
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\train_network.py", line 211, in train
    import bitsandbytes as bnb
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 43, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 39, in get_instance
    cls._instance.initialize()
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 27, in initialize
    raise Exception('CUDA SETUP: Setup Failed!')
Exception: CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Users\jsdol\OneDrive\Desktop\Kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\jsdol\\OneDrive\\Desktop\\Kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--train_data_dir=C:/Users/jsdol/OneDrive/Desktop/Training/Aleisha LORE/image', '--resolution=512,512', '--output_dir=C:/Users/jsdol/OneDrive/Desktop/Training/Aleisha LORE/model', '--logging_dir=C:/Users/jsdol/OneDrive/Desktop/Training/Aleisha LORE/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=Aleisha', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1500', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--use_8bit_adam', '--bucket_no_upscale']' returned non-zero exit status 1.

Im sure Im missing an easy fix here any suggestion would be welcome.

**Comment by hjmhjms** [comment]
the same to you

**Comment by kevbit** [comment]
This solution worked for me! Thank you @FinaBro69

**Comment by jackymail** [comment]
@FinaBro69  can believe it work , it takes me 2 hours , damn it, possibly triggered by  bitsandbytes lib, but do not know how to solve it .

**Comment by islisiyuan** [comment]
> hey you too follow me go to (Training parameters) you can see is (AdamW8bit change to AdamW) and (Gradient checkpointing, Memory efficient attention) is two also tick it
> 
> Hope it helps you

牛！

**Comment by dengfeng0729** [comment]
> hey you too follow me go to (Training parameters) you can see is (AdamW8bit change to AdamW) and (Gradient checkpointing, Memory efficient attention) is two also tick it
> 
> Hope it helps you

Thank you very much for your advice. I solved my problem according to your method. This problem has been bothering me for several days, and I have found many reasons, and finally it has been solved. Thank you！
