### ISSUE TITLE
Multiple failures on regular LoRA training (it refused to download a model)

### ISSUE THREAD

**Issue by kieranxsomer** [TimDettmers/bitsandbytes#172]
Traceback (most recent call last):
  File "/content/kohya-trainer/train_network.py", line 507, in <module>
    train(args)
  File "/content/kohya-trainer/train_network.py", line 69, in train
    train_dataset = FineTuningDataset(args.in_json, args.train_batch_size, args.train_data_dir,
  File "/content/kohya-trainer/library/train_util.py", line 842, in __init__
    assert len(abs_path) >= 1, f"no image / 画像がありません: {image_key}"
AssertionError: no image / 画像がありません: ranamerchstreamlab
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/kohya-trainer/train_network.py', '--output_name=STARLLora', '--pretrained_model_name_or_path=/content/pretrained_model/anything-v3-fp32-pruned.safetensors', '--vae=/content/vae/anime.vae.pt', '--train_data_dir=/content/drive/MyDrive/STARLLora', '--in_json=/content/drive/MyDrive/training_dir/meta_lat.json', '--output_dir=/content/drive/MyDrive/training_dir/output', '--network_dim=128', '--network_alpha=128', '--network_module=networks.lora', '--unet_lr=0.0001', '--text_encoder_lr=5e-05', '--optimizer_type=AdamW8bit', '--learning_rate=2e-06', '--lr_scheduler=constant', '--lr_warmup_steps=250', '--dataset_repeats=10', '--resolution=512', '--lowram', '--mixed_precision=fp16', '--save_precision=fp16', '--save_n_epoch_ratio=3', '--save_model_as=safetensors', '--train_batch_size=4', '--max_token_length=225', '--max_train_epochs=20', '--clip_skip=2', '--logging_dir=/content/training_dir/logs', '--log_prefix=STARLLora', '--shuffle_caption', '--xformers']' returned non-zero exit status 1.

**Comment by kieranxsomer** [comment]
Yep duplicate error in LoRA training : +-------------------------------+----------------------------------------------+
| Hyperparameter                | Value                                        |
+-------------------------------+----------------------------------------------+
| v2                            | False                                        |
| v_parameterization            | False                                        |
| project_name                  | StarRyanRipley                               |
| pretrained_model_name_or_path | /content/pretrained_model/Anything-v4-5.ckpt |
| vae                           | False                                        |
| train_folder_directory        | /content/LoRA/train_data                     |
| reg_folder_directory          | /content/LoRA/reg_data                       |
| output_dir                    | /content/drive/MyDrive/LoRA/output           |
| resume_path                   | False                                        |
+-------------------------------+----------------------------------------------+
+--------------------------------+-------+
| Hyperparameter                 | Value |
+--------------------------------+-------+
| enable_bucket                  | True  |
| resolution                     | 512   |
| min_bucket_reso                | 256   |
| max_bucket_reso                | 1024  |
| bucket_reso_steps              | 64    |
| bucket_no_upscale              | True  |
| cache_latents                  | True  |
| flip_aug                       | True  |
| caption_extension              | .txt  |
| caption_dropout_rate           | 0     |
| caption_dropout_every_n_epochs | 0     |
+--------------------------------+-------+
+-------------------+----------------------+
| Hyperparameter    | Value                |
+-------------------+----------------------+
| network_dim       | 128                  |
| network_alpha     | 128                  |
| network_module    | networks.lora        |
| network_weight    | False                |
| optimizer_type    | AdamW8bit            |
| optimizer_args    | False                |
| unet_lr           | 0.0001               |
| text_encoder_lr   | 5e-05                |
| lr_scheduler      | constant_with_warmup |
| lr_warmup_steps   | 250                  |
| lr_scheduler_args | 1                    |
+-------------------+----------------------+
+-----------------------------+------------------------------+
| Hyperparameter              | Value                        |
+-----------------------------+------------------------------+
| prior_loss_weight           | 1.0                          |
| lowram                      | True                         |
| noise_offset                | 0                            |
| max_train_type              | max_train_epochs             |
| max_train_type_value        | 20                           |
| train_batch_size            | 6                            |
| mixed_precision             | fp16                         |
| save_precision              | fp16                         |
| save_n_epochs_type          | save_n_epoch_ratio           |
| save_n_epochs_type_value    | 3                            |
| save_model_as               | safetensors                  |
| max_token_length            | 225                          |
| clip_skip                   | 2                            |
| gradient_checkpointing      | False                        |
| gradient_accumulation_steps | 1                            |
| seed                        | -1                           |
| logging_dir                 | /content/LoRA/logs           |
| additional_argument         | --shuffle_caption --xformers |
+-----------------------------+------------------------------+
2023-03-02 02:30:50.037843: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-02 02:30:51.124005: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-02 02:30:51.124106: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-02 02:30:51.124124: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-03-02 02:30:54.987785: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-02 02:30:56.130620: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-02 02:30:56.130748: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2023-03-02 02:30:56.130771: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
prepare tokenizer
Downloading (…)olve/main/vocab.json: 100% 961k/961k [00:00<00:00, 5.99MB/s]
Downloading (…)olve/main/merges.txt: 100% 525k/525k [00:00<00:00, 4.46MB/s]
Downloading (…)cial_tokens_map.json: 100% 389/389 [00:00<00:00, 78.2kB/s]
Downloading (…)okenizer_config.json: 100% 905/905 [00:00<00:00, 185kB/s]
update token length: 225
Use DreamBooth method.
prepare train images.
found directory 10_star ripleyryan contains 40 image files
400 train images with repeating.
prepare reg images.
found directory 1_ripleyryan contains 0 image files
0 reg images.
no regularization images / 正則化画像が見つかりませんでした
loading image sizes.
100% 40/40 [00:00<00:00, 2965.74it/s]
make buckets
min_bucket_reso and max_bucket_reso are ignored if bucket_no_upscale is set, because bucket reso is defined by image size automatically / bucket_no_upscaleが指定された場合は、bucketの解像度は画像サイズから自動計算されるため、min_bucket_resoとmax_bucket_resoは無視されます
number of images (including repeats) / 各bucketの画像枚数（繰り返し回数を含む）
bucket 0: resolution (64, 320), count: 10
bucket 1: resolution (128, 256), count: 10
bucket 2: resolution (128, 512), count: 10
bucket 3: resolution (192, 128), count: 10
bucket 4: resolution (192, 192), count: 10
bucket 5: resolution (192, 320), count: 30
bucket 6: resolution (192, 384), count: 10
bucket 7: resolution (192, 448), count: 10
bucket 8: resolution (256, 192), count: 10
bucket 9: resolution (256, 256), count: 20
bucket 10: resolution (256, 320), count: 10
bucket 11: resolution (256, 384), count: 20
bucket 12: resolution (256, 512), count: 10
bucket 13: resolution (320, 192), count: 30
bucket 14: resolution (320, 320), count: 30
bucket 15: resolution (320, 384), count: 10
bucket 16: resolution (320, 448), count: 10
bucket 17: resolution (320, 576), count: 10
bucket 18: resolution (320, 704), count: 20
bucket 19: resolution (384, 512), count: 10
bucket 20: resolution (384, 576), count: 40
bucket 21: resolution (448, 256), count: 10
bucket 22: resolution (448, 448), count: 10
bucket 23: resolution (448, 512), count: 10
bucket 24: resolution (448, 576), count: 10
bucket 25: resolution (512, 256), count: 10
bucket 26: resolution (512, 320), count: 10
bucket 27: resolution (640, 384), count: 10
mean ar error (without repeats): 0.06005916714375318
prepare accelerator
Traceback (most recent call last):
  File "train_network.py", line 507, in <module>
    train(args)
  File "train_network.py", line 90, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "/content/kohya-trainer/library/train_util.py", line 1817, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 355, in __init__
    raise ValueError(err.format(mode="fp16", requirement="a GPU"))
ValueError: fp16 mixed precision requires a GPU
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_network.py', '--output_name=StarRyanRipley', '--pretrained_model_name_or_path=/content/pretrained_model/Anything-v4-5.ckpt', '--train_data_dir=/content/LoRA/train_data', '--reg_data_dir=/content/LoRA/reg_data', '--output_dir=/content/drive/MyDrive/LoRA/output', '--network_dim=128', '--network_alpha=128', '--network_module=networks.lora', '--optimizer_type=AdamW8bit', '--learning_rate=0.0001', '--unet_lr=0.0001', '--text_encoder_lr=5e-05', '--lr_scheduler=constant_with_warmup', '--lr_warmup_steps=250', '--enable_bucket', '--resolution=512', '--cache_latents', '--bucket_reso_steps=64', '--bucket_no_upscale', '--min_bucket_reso=256', '--max_bucket_reso=1024', '--caption_extension=.txt', '--keep_tokens=1', '--prior_loss_weight=1.0', '--lowram', '--train_batch_size=6', '--max_train_epochs=20', '--mixed_precision=fp16', '--save_precision=fp16', '--save_n_epoch_ratio=3', '--save_model_as=safetensors', '--max_token_length=225', '--gradient_accumulation_steps=1', '--clip_skip=2', '--logging_dir=/content/LoRA/logs', '--log_prefix=StarRyanRipley', '--shuffle_caption', '--xformers']' returned non-zero exit status 1.

This one's https://colab.research.google.com/github/Linaqruf/kohya-trainer/blob/main/kohya-LoRA-dreambooth.ipynb and the other one above is the new "FAST TRAIN" notebook.

**Comment by kieranxsomer** [comment]
Ok first one was my fault, 2nd may have been cause i tried to us a TPU, will come back if tehre's more errors.

**Comment by kieranxsomer** [comment]
Oops replying here, FIRST ONE was cause i trained a lora last night, didn't rename the directory, second was because i tried colab's TPU, and it kinda burned a hole in itself XD

**Comment by kieranxsomer** [comment]
Yep ok all of this was my issue, sorry!
