### ISSUE TITLE
CUDA issue on Windows...

### ISSUE THREAD

**Issue by NaitorStudios** [TimDettmers/bitsandbytes#193]
I'm using a GTX 1080 on Windows 11, I'm getting this error while trying to train lora, any idea what could cause this and how to fix?

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C'), WindowsPath('/Imagination/PowerVR_Graphics/PowerVR_Tools_Old/PVRVFrame/Profiles')}
  warn(
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "D:\Program Files (Standalone)\kohya\kohya_ss\train_network.py", line 659, in <module>
    train(args)
  File "D:\Program Files (Standalone)\kohya\kohya_ss\train_network.py", line 171, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\Program Files (Standalone)\kohya\kohya_ss\library\train_util.py", line 1719, in get_optimizer
    import bitsandbytes as bnb
  File "D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 31, in initialize
    self.lib = ct.cdll.LoadLibrary(binary_path)
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary    return self._dlltype(name)
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable
Traceback (most recent call last):
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (Standalone)\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\Program Files (Standalone)\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Program Files (Standalone)\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=D:\\Program Files (Standalone)\\kohya\\kohya_ss\\Lora Training Data\\LorryneMello\\image', '--resolution=512,512', '--output_dir=D:\\Program Files (Standalone)\\kohya\\kohya_ss\\Lora Training Data\\LorryneMello\\model', '--logging_dir=D:\\Program Files (Standalone)\\kohya\\kohya_ss\\Lora Training Data\\LorryneMello\\log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=LorryneMello', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=2690', '--train_batch_size=1', '--max_train_steps=26900', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by luiscosio** [comment]
You should follow these instructions:

https://www.reddit.com/r/LocalLLaMA/comments/11o6o3f/how_to_install_llama_8bit_and_4bit/

**Comment by NaitorStudios** [comment]
Well, not all of that unrelated software installation was too relevant to this, but now I get this...

[Dataset 0]
loading image sizes.
100%|██████████████████████████████████████████████████████████████████████████████| 265/265 [00:00<00:00, 5657.45it/s]
prepare dataset
prepare accelerator
Traceback (most recent call last):
  File "C:\Program Files (Standalone)\AI Stuff\kohya_ss\train_network.py", line 659, in <module>
    train(args)
  File "C:\Program Files (Standalone)\AI Stuff\kohya_ss\train_network.py", line 108, in train
    accelerator, unwrap_model = train_util.prepare_accelerator(args)
  File "C:\Program Files (Standalone)\AI Stuff\kohya_ss\library\train_util.py", line 1984, in prepare_accelerator
    accelerator = Accelerator(gradient_accumulation_steps=args.gradient_accumulation_steps, mixed_precision=args.mixed_precision,
  File "C:\Program Files (Standalone)\AI Stuff\kohya_ss\venv\lib\site-packages\accelerate\accelerator.py", line 370, in __init__
    raise ValueError(err.format(mode="bf16", requirement="PyTorch >= 1.10 and a supported device."))
ValueError: bf16 mixed precision requires PyTorch >= 1.10 and a supported device.
Traceback (most recent call last):
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (Standalone)\AI Stuff\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Program Files (Standalone)\AI Stuff\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Program Files (Standalone)\AI Stuff\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "C:\Program Files (Standalone)\AI Stuff\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Program Files (Standalone)\\AI Stuff\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=D:/Program Files (Standalone)/Stable Diffusion WebUI/webui/models/Stable-diffusion/v1-5-pruned.ckpt', '--train_data_dir=D:/AI MODELS/Lora Training Data/LorryneMello/image', '--resolution=512,512', '--output_dir=D:/AI MODELS/Lora Training Data/LorryneMello/model', '--logging_dir=D:/AI MODELS/Lora Training Data/LorryneMello/log', '--network_alpha=128', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=128', '--output_name=LorryneMello', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=2', '--max_train_steps=13250', '--save_every_n_epochs=1', '--mixed_precision=bf16', '--save_precision=bf16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by NaitorStudios** [comment]
After some changes... Now stuck on this, detail, the cusolver64_11.dll is there, no idea why it complains about it:

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary C:\Program Files (Standalone)\AI Stuff\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
running training / 学習開始
  num train images * repeats / 学習画像の数×繰り返し回数: 26500
  num reg images / 正則化画像の数: 0
  num batches per epoch / 1epochのバッチ数: 26500
  num epochs / epoch数: 1
  batch size per device / バッチサイズ: 1
  gradient accumulation steps / 勾配を合計するステップ数 = 1
  total optimization steps / 学習ステップ数: 26500
steps:   0%|                                                                                 | 0/26500 [00:00<?, ?it/s]epoch 1/1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\NaitorStudios\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (Standalone)\AI Stuff\kohya_ss\train_network.py", line 1, in <module>
    from torch.nn.parallel import DistributedDataParallel as DDP
  File "C:\Program Files (Standalone)\AI Stuff\kohya_ss\venv\lib\site-packages\torch\__init__.py", line 129, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Program Files (Standalone)\AI Stuff\kohya_ss\venv\lib\site-packages\torch\lib\cusolver64_11.dll" or one of its dependencies.

**Comment by FinaBro69** [comment]
go to (Training parameters) you can see is (AdamW8bit change to AdamW)
and (Gradient checkpointing, Memory efficient attention) is two also tick it

Hope it helps you

**Comment by NaitorStudios** [comment]
I noticed this btw:
"The paging file is too small for this operation to complete."
Which paging file would that be? Because Windows automatically allocated 42046 MB of Virtual Memory, which is a paging file...

**Comment by FinaBro69** [comment]
Do not install kohya_ss on Local Disk (C)
Install kohya_ss on Local Disk (D) here

Your paging size of my Local Disk (C) is higher than mine, and the paging size of Local Disk (D) has surpassed ours several times
I don't know if you have HardDrive
I see you have installed it on Local Disk (D) before, right?

I installed it on Local Disk (D)
![Screenshot 2023-03-18 100734](https://user-images.githubusercontent.com/127876242/226077663-00284fd5-2939-440d-bd59-4629fa48a71f.png)

Hope it helps you
