### ISSUE TITLE
BUG REPORT 

### ISSUE THREAD

**Issue by Piccata** [TimDettmers/bitsandbytes#197]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary g:\stablediffusion\lora\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "train_network.py", line 659, in <module>
    train(args)
  File "train_network.py", line 171, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "G:\StableDiffusion\lora\kohya_ss\library\train_util.py", line 1719, in get_optimizer
    import bitsandbytes as bnb
  File "g:\stablediffusion\lora\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "g:\stablediffusion\lora\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "g:\stablediffusion\lora\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "g:\stablediffusion\lora\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 43, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "g:\stablediffusion\lora\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 39, in get_instance
    cls._instance.initialize()
  File "g:\stablediffusion\lora\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 33, in initialize
    self.lib = ct.cdll.LoadLibrary(str(binary_path))            # $$$
  File "C:\Users\Piccata\Anaconda3\lib\ctypes\__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Piccata\Anaconda3\lib\ctypes\__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'g:\stablediffusion\lora\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Traceback (most recent call last):
  File "C:\Users\Piccata\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Piccata\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "G:\StableDiffusion\lora\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "g:\stablediffusion\lora\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "g:\stablediffusion\lora\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "g:\stablediffusion\lora\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['g:\\stablediffusion\\lora\\kohya_ss\\venv\\scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=G:/StableDiffusion/Stable-diffusion-webui/models/Stable-diffusion/chilloutmix_NiPrunedFp32Fix.safetensors', '--train_data_dir=C:\\Users\\Piccata\\Documents\\test', '--resolution=512,512', '--output_dir=G:\\StableDiffusion\\loradata\\standelisedimg', '--logging_dir=', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=1.5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=cc_test', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--train_batch_size=3', '--max_train_steps=8', '--save_every_n_epochs=1', '--mixed_precision=no', '--save_precision=fp16', '--seed=1234', '--cache_latents', '--optimizer_type=AdamW8bit', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by 2018211801** [comment]
I meet the same problem!
