### ISSUE TITLE
Petals server explicit CUDA version check

### ISSUE THREAD

**Issue by malinah** [TimDettmers/bitsandbytes#199]
Please explicitly detect and document supported CUDA library versions to avoid further submissions of this issue.

Probably the fallback library _libbitsandbytes.so_ should have been used when version mismatch happens but I don't seem to find it in the pip package.

Please print meaningful error message when this happens.

Better yet, prepare the libbitsandbytes_cuda*.so library with "all" CUDA versions if possible.

```
$ python -m petals.cli.run_server bigscience/bloom-petals
...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: TODO: compile library for specific version: libbitsandbytes_cuda118.so
CUDA SETUP: Defaulting to libbitsandbytes.so...
CUDA SETUP: CUDA detection failed. Either CUDA driver not installed, CUDA not installed, or you have multiple conflicting CUDA libraries!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/codegen/venv/lib/python3.10/site-packages/petals/cli/run_server.py", line 216, in <module>
    main()
  File "/tmp/codegen/venv/lib/python3.10/site-packages/petals/cli/run_server.py", line 199, in main
    server = Server(
  File "/tmp/codegen/venv/lib/python3.10/site-packages/petals/server/server.py", line 202, in __init__
    throughput = get_host_throughput(
  File "/tmp/codegen/venv/lib/python3.10/site-packages/petals/server/throughput.py", line 77, in get_host_throughput
    cache[cache_key] = measure_throughput_info(
  File "/tmp/codegen/venv/lib/python3.10/site-packages/petals/server/throughput.py", line 105, in measure_throughput_info
    result = measure_compute_rps(
  File "/tmp/codegen/venv/lib/python3.10/site-packages/petals/server/throughput.py", line 152, in measure_compute_rps
    block = convert_block(block, config, tensor_parallel_devices, device, load_in_8bit=load_in_8bit, freeze=True)
  File "/tmp/codegen/venv/lib/python3.10/site-packages/petals/utils/convert_block.py", line 52, in convert_block
    block = replace_8bit_linear(block, threshold=threshold)
  File "/tmp/codegen/venv/lib/python3.10/site-packages/petals/utils/convert_block.py", line 78, in replace_8bit_linear
    import bitsandbytes as bnb
  File "/tmp/codegen/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/tmp/codegen/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/tmp/codegen/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/tmp/codegen/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "/tmp/codegen/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "/tmp/codegen/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 27, in initialize
    raise Exception('CUDA SETUP: Setup Failed!')
Exception: CUDA SETUP: Setup Failed!
```

Cheers

**Comment by TimDettmers** [comment]
The issue with this is that petals installs an old version of bitsandbytes which does not have a pre-compiled CUDA 11.8 version. You need to manually convert or install a newer version. I will update this on the petal repo once PR #159 is merged
