### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by barrand** [TimDettmers/bitsandbytes#209]
I'm trying to run this from the Ubuntu gui.sh and I'm running into this issue. Any ideas on how to get around this?

`Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Folder 100_test: 3900 steps
max_train_steps = 1950
stop_text_encoder_training = 0
lr_warmup_steps = 195
accelerate launch --num_cpu_threads_per_process=2 "train_db.py" --enable_bucket -train_data_dir="/mnt/c/Users/barra/Documents/Lora/wifimar/image" --resolution=512,512 --output_dir="/mnt/c/Users/barra/Documents/Lora/wifimar/model" --logging_dir="/mnt/c/Users/barra/Documents/Lora/wifimar/logs" --save_model_as=safetensors --output_name="last" --learning_rate="1e-5" --lr_scheduler="cosine" --lr_warmup_steps="195" --train_batch_size="2" --max_train_steps="1950" --save_every_n_epochs="1" --mixed_precision="fp16" --save_precision="fp16" --cache_latents --optimizer_type="AdamW" --bucket_reso_steps=64 --xformers --bucket_no_upscale
2023-03-21 20:49:25.432254: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-21 20:49:25.589505: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-21 20:49:26.051015: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-03-21 20:49:26.051079: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-03-21 20:49:26.051086: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-03-21 20:49:27.108910: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-21 20:49:27.219013: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-03-21 20:49:27.552648: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-03-21 20:49:27.552711: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-03-21 20:49:27.552730: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "/home/barrand/kohya_ss/train_db.py", line 17, in <module>
    import library.train_util as train_util
  File "/home/barrand/kohya_ss/library/train_util.py", line 39, in <module>
    import albumentations as albu
  File "/home/barrand/kohya_ss/venv/lib/python3.10/site-packages/albumentations/__init__.py", line 5, in <module>
    from .augmentations import *
  File "/home/barrand/kohya_ss/venv/lib/python3.10/site-packages/albumentations/augmentations/__init__.py", line 2, in <module>
    from .blur.functional import *
  File "/home/barrand/kohya_ss/venv/lib/python3.10/site-packages/albumentations/augmentations/blur/__init__.py", line 1, in <module>
    from .functional import *
  File "/home/barrand/kohya_ss/venv/lib/python3.10/site-packages/albumentations/augmentations/blur/functional.py", line 5, in <module>
    import cv2
  File "/home/barrand/kohya_ss/venv/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/barrand/kohya_ss/venv/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/barrand/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/barrand/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/barrand/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/home/barrand/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/barrand/kohya_ss/venv/bin/python3', 'train_db.py', '--enable_bucket', '--pretrained_model_name_or_path=/mnt/c/Users/barra/Downloads/model_.safetensors', '--train_data_dir=/mnt/c/Users/barra/Documents/Lora/wifimar/image', '--resolution=512,512', '--output_dir=/mnt/c/Users/barra/Documents/Lora/wifimar/model', '--logging_dir=/mnt/c/Users/barra/Documents/Lora/wifimar/logs', '--save_model_as=safetensors', '--output_name=last', '--learning_rate=1e-5', '--lr_scheduler=cosine', '--lr_warmup_steps=195', '--train_batch_size=2', '--max_train_steps=1950', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.`

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
