### ISSUE TITLE
CUDA setup failed despite GPU being available

### ISSUE THREAD

**Issue by HughMungis** [TimDettmers/bitsandbytes#231]
Trying to run the oobabooga web UI for a locally hosted chat bot. Running a Win10 machine with a 3080 GPU. Here's the trace:

```Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('G')}
  warn(msg)
G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/AI/one-click-installers-oobabooga-windows/one-click-installers-oobabooga-windows/installer_files/env/etc/xml/catalog'), WindowsPath('file'), WindowsPath('/G')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:136: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\text-generation-webui\server.py", line 13, in <module>
    from modules import chat, shared, training, ui
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\text-generation-webui\modules\training.py", line 11, in <module>
    from peft import (LoraConfig, get_peft_model, get_peft_model_state_dict,
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\peft\tuners\__init__.py", line 20, in <module>
    from .lora import LoraConfig, LoraModel
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 36, in <module>
    import bitsandbytes as bnb
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "G:\AI\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues```

**Comment by zoudong** [comment]
me too

**Comment by HurterJ** [comment]
same

**Comment by jllllll** [comment]
bitsandbytes does not support Windows out of the box when installed through pip. The one-click-installer for [text-generation-webui](https://github.com/oobabooga/text-generation-webui) has been updated to fix this automatically. [Link](https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga-windows.zip)

**Comment by censolute** [comment]
> bitsandbytes does not support Windows out of the box when installed through pip. The one-click-installer for [text-generation-webui](https://github.com/oobabooga/text-generation-webui) has been updated to fix this automatically. [Link](https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga-windows.zip)

Thanks a lot! I have the same problem when I try to import bitsandbytes. I download the 'Link' and found modifications were necessary to make it work:
1. get two bitsandbytes' "dll" and place it in bitsandbytes' path.
one for cpu, one for cuda, 
[https://github.com/DeXtmL/bitsandbytes-win-prebuilt/raw/main/libbitsandbytes_cpu.dll](url)
[https://github.com/james-things/bitsandbytes-prebuilt-all_arch/raw/main/0.37.0/libbitsandbytes_cudaall.dll](url)
move both "dll" to <your env>/lib/site-packages/bitsandbytes

2. modify the cuda_setup/main.py

(1)  get the right path to dll for win <your env>/lib/site-packages/bitsandbytes/cuda_setup/main.py,  roughly around line 370
```
def evaluate_cuda_setup():
    .....
    # if not torch.cuda.is_available(): return 'libsbitsandbytes_cpu.so', None, None, None, None
    if torch.cuda.is_available(): 
        return 'libbitsandbytes_cudaall.dll', None, None, None, None
    else: 
        return 'libbitsandbytes_cpu.dll', None, None, None, None
```

(2) set str(the path),  roughly around line 120
```
class CUDASetup:
......
    def run_cuda_setup(self):
......
        try:
            if not binary_path.exists():
                ......
                # self.lib = ct.cdll.LoadLibrary(binary_path)
                self.lib = ct.cdll.LoadLibrary(str(binary_path))
            else:
                self.add_log_entry(f"CUDA SETUP: Loading binary {binary_path}...")
                # self.lib = ct.cdll.LoadLibrary(binary_path)
                self.lib = ct.cdll.LoadLibrary(str(binary_path)) 
```

**Comment by jllllll** [comment]
> Thanks a lot! I have the same problem when I try to import bitsandbytes. I download the 'Link' and found modifications were necessary to make it work:

All of that is supposed to happen automatically. But, for reasons unknown, it doesn't work for everyone. Windows can be a downright cryptic mess sometimes.

**Comment by DeepMindOmega** [comment]
> > > Thanks a lot! I have the same problem when I try to import bitsandbytes. I download the 'Link' and found modifications were necessary to make it work:
> > 
> > 
> > All of that is supposed to happen automatically. But, for reasons unknown, it doesn't work for everyone. Windows can be a downright cryptic mess sometimes.
> 
> Forgive my poor English, but what I meant was that I found the section on processing 'bitsandbytes' in the .bat file that came with the link, and after manually following those instructions, it started working properly without needing any additional installation.



> > bitsandbytes does not support Windows out of the box when installed through pip. The one-click-installer for [text-generation-webui](https://github.com/oobabooga/text-generation-webui) has been updated to fix this automatically. [Link](https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga-windows.zip)
> 
> Thanks a lot! I have the same problem when I try to import bitsandbytes. I download the 'Link' and found out why it works:
> 
> 1. get two bitsandbytes' "dll" and place it in bitsandbytes' path.
>    one for cpu, one for cuda,
>    [https://github.com/DeXtmL/bitsandbytes-win-prebuilt/raw/main/libbitsandbytes_cpu.dll](url)
>    [https://github.com/james-things/bitsandbytes-prebuilt-all_arch/raw/main/0.37.0/libbitsandbytes_cudaall.dll](url)
>    move both "dll" to /lib/site-packages/bitsandbytes
> 2. modify the cuda_setup/main.py
> 
> (1) get the right path to dll for win /lib/site-packages/bitsandbytes/cuda_setup/main.py, roughly around line 370
> 
> ```
> def evaluate_cuda_setup():
>     .....
>     # if not torch.cuda.is_available(): return 'libsbitsandbytes_cpu.so', None, None, None, None
>     if torch.cuda.is_available(): 
>         return 'libbitsandbytes_cudaall.dll', None, None, None, None
>     else: 
>         return 'libbitsandbytes_cpu.dll', None, None, None, None
> ```
> 
> (2) set str(the path), roughly around line 120
> 
> ```
> class CUDASetup:
> ......
>     def run_cuda_setup(self):
> ......
>         try:
>             if not binary_path.exists():
>                 ......
>                 # self.lib = ct.cdll.LoadLibrary(binary_path)
>                 self.lib = ct.cdll.LoadLibrary(str(binary_path))
>             else:
>                 self.add_log_entry(f"CUDA SETUP: Loading binary {binary_path}...")
>                 # self.lib = ct.cdll.LoadLibrary(binary_path)
>                 self.lib = ct.cdll.LoadLibrary(str(binary_path)) 
> ```

thanks，problem has been sloved
