### ISSUE TITLE
Error when import bnb.nn.Linear8bitLt

### ISSUE THREAD

**Issue by Alex-Songs** [TimDettmers/bitsandbytes#24]
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.3/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 113
CUDA SETUP: TODO: compile library for specific version: libbitsandbytes_cuda113_nocublaslt.so
CUDA SETUP: Defaulting to libbitsandbytes.so...
CUDA SETUP: CUDA detection failed. Either CUDA driver not installed, CUDA not installed, or you have multiple conflicting CUDA libraries!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
Traceback (most recent call last):
  File "1.py", line 1, in <module>
    import bitsandbytes as bnb
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/lisong39/python_packs/lib/python3.8/site-packages/bitsandbytes-0.32.1-py3.8.egg/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/lisong39/python_packs/lib/python3.8/site-packages/bitsandbytes-0.32.1-py3.8.egg/bitsandbytes/autograd/_functions.py", line 4, in <module>
    import bitsandbytes.functional as F
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/lisong39/python_packs/lib/python3.8/site-packages/bitsandbytes-0.32.1-py3.8.egg/bitsandbytes/functional.py", line 14, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/lisong39/python_packs/lib/python3.8/site-packages/bitsandbytes-0.32.1-py3.8.egg/bitsandbytes/cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/lisong39/python_packs/lib/python3.8/site-packages/bitsandbytes-0.32.1-py3.8.egg/bitsandbytes/cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "/mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/lisong39/python_packs/lib/python3.8/site-packages/bitsandbytes-0.32.1-py3.8.egg/bitsandbytes/cextension.py", line 27, in initialize
    raise Exception('CUDA SETUP: Setup Failed!')
Exception: CUDA SETUP: Setup Failed!

**Comment by TimDettmers** [comment]
It seems a specific compiled version has not been found even though it should be available. 

Can you please provide the output for the command
```bash
ls /mnt/dolphinfs/hdd_pool/docker/user/hadoop-speech/users/lisong39/python_packs/lib/python3.8/site-packages/bitsandbytes-0.32.1-py3.8.egg/bitsandbytes/
```
