### ISSUE TITLE
我在使用kohya_ss训练lora模型时出现以下报错？是什么原因？怎么解决呀？

### ISSUE THREAD

**Issue by Helio1997hub** [TimDettmers/bitsandbytes#269]
电脑设备：MacOS Apple Silicon M2

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:93: UserWarning: /Users/xiangshuchen/miniconda3 did not contain libcudart.so as expected! Searching further paths...
  warn(
/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib')}
  warn(
/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:105: UserWarning: /Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/cv2/../../lib: did not contain libcudart.so as expected! Searching further paths...
  warn(
/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('https'), PosixPath('//mirrors.tuna.tsinghua.edu.cn/homebrew-bottles')}
  warn(
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary /Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "/Users/xiangshuchen/opt/kohya_ss/train_db.py", line 429, in <module>
    train(args)
  File "/Users/xiangshuchen/opt/kohya_ss/train_db.py", line 150, in train
    _, _, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/Users/xiangshuchen/opt/kohya_ss/library/train_util.py", line 2312, in get_optimizer
    import bitsandbytes as bnb
  File "/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 31, in initialize
    self.lib = ct.cdll.LoadLibrary(binary_path)
  File "/Users/xiangshuchen/miniconda3/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Users/xiangshuchen/miniconda3/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006): tried: '/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (no such file), '/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file)
Traceback (most recent call last):
  File "/Users/xiangshuchen/opt/kohya_ss/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/Users/xiangshuchen/opt/kohya_ss/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/Users/xiangshuchen/opt/kohya_ss/venv/bin/python3', 'train_db.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=/Users/xiangshuchen/opt/Lora/img', '--resolution=512,512', '--output_dir=/Users/xiangshuchen/opt/Lora/model', '--logging_dir=/Users/xiangshuchen/opt/Lora/log', '--save_model_as=safetensors', '--output_name=meiyi', '--max_data_loader_n_workers=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=4000', '--save_every_n_epochs=1', '--mixed_precision=no', '--save_precision=float', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--mem_eff_attn', '--gradient_checkpointing', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
