### ISSUE TITLE
How to fix this

### ISSUE THREAD

**Issue by TerminatorTerminated** [TimDettmers/bitsandbytes#276]
Traceback (most recent call last):
  File "D:\Program Files\GPT4\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "D:\Program Files\GPT4\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Program Files\GPT4\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Program Files\GPT4\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models\\gpt4-x-alpaca-13b-native-4bit-128g\\pytorch_model-00001-of-00006.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\GPT4\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\Program Files\GPT4\oobabooga-windows\text-generation-webui\modules\models.py", line 170, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "D:\Program Files\GPT4\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "D:\Program Files\GPT4\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2736, in from_pretrained
    ) = cls._load_pretrained_model(
  File "D:\Program Files\GPT4\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3050, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "D:\Program Files\GPT4\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 445, in load_state_dict
    with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\\gpt4-x-alpaca-13b-native-4bit-128g\\pytorch_model-00001-of-00006.bin'
Press any key to continue . . .

**Comment by kuldp18** [comment]
I have the same error as well

**Comment by TimDettmers** [comment]
You can fix the error by pointing the code to the model checkpoint. This error is not related to bitsandbytes and I close this issue.
