### ISSUE TITLE
Strange Issue while following tutorial

### ISSUE THREAD

**Issue by ZenbladeJS** [TimDettmers/bitsandbytes#279]
This was the tutorial I was following:

https://www.youtube.com/watch?v=nVC9D9fRyNU&ab_channel=Aitrepreneur

This is the error:

Traceback (most recent call last):
  File "C:\Users\zenbl\OneDrive\Desktop\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\zenbl\OneDrive\Desktop\oobabooga-windows\text-generation-webui\modules\models.py", line 100, in load_model
    from modules.GPTQ_loader import load_quantized
  File "C:\Users\zenbl\OneDrive\Desktop\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 14, in <module>
    import llama_inference_offload
ModuleNotFoundError: No module named 'llama_inference_offload'

Any solutions? I am running in CPU mode.

**Comment by chirag062002** [comment]
same.. did you find any solution?

**Comment by minglang8632** [comment]
same, is there any way to solve it

**Comment by MrDiver** [comment]
same

**Comment by chirag062002** [comment]
so what I did for this was I went to the install.bat and did both GPU and CPU installations.. it solved the missing module problem. but then because I have GTX 1660 which is not compatible with CUDA acceleration I can not run the webUI because i get CUDA error message -_- sed.
