### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by khanfar** [TimDettmers/bitsandbytes#287]
PLEASE HELP I GOT THIS ERROR :  

Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Loading binary E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
CUDA extension not installed.
Found the following quantized model: models\anon8231489123_vicuna-13b-GPTQ-4bit-128g\vicuna-13b-4bit-128g.safetensors
Loading model ...
E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Done.
Traceback (most recent call last):
  File "E:\vicuna-chatgpt4\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "E:\vicuna-chatgpt4\oobabooga-windows\text-generation-webui\modules\models.py", line 103, in load_model
    model = load_quantized(model_name)
  File "E:\vicuna-chatgpt4\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 154, in load_quantized
    model = model.to(torch.device('cuda:0'))
  File "E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 1888, in to
    return super().to(*args, **kwargs)
  File "E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "E:\vicuna-chatgpt4\oobabooga-windows\installer_files\env\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Press any key to continue . . .

**Comment by czy-moyu** [comment]
I have the same error:
(base) PS K:\MiniGPT-4> python demo.py --cfg-path eval_configs/minigpt4_eval.yaml
Initializing Chat
Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Loading LLAMA

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: Loading binary C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
Loading checkpoint shards:   0%|                                                                 | 0/3 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "K:\MiniGPT-4\demo.py", line 60, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "K:\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 243, in from_config
    model = cls(
  File "K:\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 90, in __init__
    self.llama_model = LlamaForCausalLM.from_pretrained(
  File "C:\Users\chenz\miniconda3\lib\site-packages\transformers\modeling_utils.py", line 2795, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\chenz\miniconda3\lib\site-packages\transformers\modeling_utils.py", line 3123, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "C:\Users\chenz\miniconda3\lib\site-packages\transformers\modeling_utils.py", line 706, in _load_state_dict_into_meta_model
    set_module_8bit_tensor_to_device(
  File "C:\Users\chenz\miniconda3\lib\site-packages\transformers\utils\bitsandbytes.py", line 87, in set_module_8bit_tensor_to_device
    new_value = value.to(device)
  File "C:\Users\chenz\miniconda3\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
(base) PS K:\MiniGPT-4> python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: Loading binary C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "C:\Users\chenz\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenz\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\__main__.py", line 49, in generate_bug_report_information
    paths = find_file_recursive(os.environ['CONDA_PREFIX'], '*cuda*so')
  File "C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\__main__.py", line 35, in find_file_recursive
    out, err = execute_and_return(cmd)
  File "C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\__main__.py", line 30, in execute_and_return
    std_out, std_err = execute_and_return_decoded_std_streams(command_string)
  File "C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\__main__.py", line 22, in execute_and_return_decoded_std_streams
    return _decode(
  File "C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\__main__.py", line 16, in _decode
    return tuple(
  File "C:\Users\chenz\miniconda3\lib\site-packages\bitsandbytes\__main__.py", line 17, in <genexpr>
    to_decode.decode("UTF-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 0: invalid continuation byte
