### ISSUE TITLE
Training LORA model error

### ISSUE THREAD

**Issue by yefeng520dtet** [TimDettmers/bitsandbytes#289]
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
D:\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\paths.py:27: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary D:\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
Traceback (most recent call last):
  File "D:\kohya\kohya_ss\train_network.py", line 748, in <module>
    train(args)
  File "D:\kohya\kohya_ss\train_network.py", line 223, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\kohya\kohya_ss\library\train_util.py", line 2312, in get_optimizer
    import bitsandbytes as bnb
  File "D:\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "D:\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "D:\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "D:\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "D:\kohya\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 31, in initialize
    self.lib = ct.cdll.LoadLibrary(binary_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary    return self._dlltype(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'WindowsPath' is not iterable
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=E:/BaiduNetdiskDownload/stable diffusion秋叶整合包/1.novelai-webui/novelai-webui-aki-v3/models/Stable-diffusion/v1-5-pruned-emaonly.ckpt', '--train_data_dir=D:/kohya/LoraTrain/image', '--resolution=512,512', '--output_dir=D:/kohya/LoraTrain/model', '--logging_dir=D:/kohya/LoraTrain/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=last', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=670', '--train_batch_size=1', '--max_train_steps=6700', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by yefeng520dtet** [comment]
Can you tell me how to solve it? Thank you very much!

**Comment by RiskySignal** [comment]
As far as I know, libsandbytes does not support the Windows system.

**Comment by TimDettmers** [comment]
If you try to use the new release, this error might be fixed:
```python
pip install -U bitsandbytess
```
Otherwise you will need to compile from source to fix this error. As @RiskySignal already says, Windows support is experimental, but people figured out how to compile it. Please look at other issues for regarding to how to compile on windows.

**Comment by github-gil** [comment]
I have something that seems similar:
**Traceback (most recent call last):
  File "D:\Kohya-ss\kohya_ss\library\train_util.py", line 3616, in get_optimizer
    import bitsandbytes as bnb**
  File "D:\Kohya-ss\kohya_ss\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\Kohya-ss\kohya_ss\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\Kohya-ss\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\Kohya-ss\kohya_ss\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\Kohya-ss\kohya_ss\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\Kohya-ss\kohya_ss\venv\lib\site-packages\bitsandbytes\cextension.py", line 5, in <module>
    from .cuda_setup.main import evaluate_cuda_setup
  File "D:\Kohya-ss\kohya_ss\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 21, in <module>
    from .paths import determine_cuda_runtime_lib_path
ModuleNotFoundError: No module named 'bitsandbytes.cuda_setup.paths'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Kohya-ss\kohya_ss\train_db.py", line 504, in <module>
    train(args)
  File "D:\Kohya-ss\kohya_ss\train_db.py", line 180, in train
    _, _, optimizer = train_util.get_optimizer(args, trainable_params)
  File "D:\Kohya-ss\kohya_ss\library\train_util.py", line 3618, in get_optimizer
    raise ImportError("No bitsandbytes / bitsandbytesがインストールされていないようです")
ImportError: No bitsandbytes / bitsandbytesがインストールされていないようです
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Kohya-ss\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\Kohya-ss\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "D:\Kohya-ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "D:\Kohya-ss\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Kohya-ss\\kohya_ss\\venv\\Scripts\\python.exe', './train_db.py', '--bucket_no_upscale', '--bucket_reso_steps=64', '--cache_latents', '--caption_extension=.txt', '--enable_bucket', '--min_bucket_reso=256', '--max_bucket_reso=2048', '--learning_rate=1e-05', '--learning_rate_te=1e-05', '--logging_dir=D:/LORA-training/NA-House/log', '--lr_scheduler=cosine', '--lr_scheduler_num_cycles=10', '--lr_warmup_steps=900', '--max_data_loader_n_workers=0', '--resolution=512,512', '--max_train_steps=9000', '--mixed_precision=fp16', '--optimizer_type=AdamW8bit', '--output_dir=D:/LORA-training/NA-House/model', '--output_name=NA-House', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--save_every_n_epochs=1', '--save_model_as=safetensors', '--save_precision=fp16', '--train_batch_size=1', '--train_data_dir=D:/LORA-training/NA-House/images', '--xformers']' returned non-zero exit status 1.


this is under Kohya installed yesterday:
**09:40:34-824768 INFO     Version: v22.6.2**

09:40:34-827767 INFO     nVidia toolkit detected
09:40:35-846456 INFO     Torch 2.1.2+cu118
09:40:35-857961 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
09:40:35-859961 INFO     Torch detected GPU: NVIDIA GeForce RTX 4070 Ti VRAM 12282 Arch (8, 9) Cores 60
09:40:35-860961 INFO     Verifying modules installation status from requirements_windows_torch2.txt...
09:40:35-861961 INFO     Installing package: torch==2.1.2+cu118 torchvision==0.16.2+cu118 torchaudio==2.1.2+cu118
                         --index-url https://download.pytorch.org/whl/cu118
09:40:39-083097 INFO     Installing package: xformers==0.0.23.post1+cu118 --index-url
                         https://download.pytorch.org/whl/cu118
09:40:40-785788 INFO     Verifying modules installation status from requirements.txt...
09:40:43-443995 INFO     headless: False
