### ISSUE TITLE
 not enough memory

### ISSUE THREAD

**Issue by daama007** [TimDettmers/bitsandbytes#290]
![Screenshot 2023-04-10 182558](https://user-images.githubusercontent.com/121124981/230945924-f050de24-5f5d-4941-9d10-7342dea2d219.png)

**Comment by Akako0** [comment]
Same error here

`Loading gpt4-x-alpaca-13b-native-4bit-128g...
CUDA extension not installed.
Found the following quantized model: models\gpt4-x-alpaca-13b-native-4bit-128g\gpt-x-alpaca-13b-native-4bit-128g-cuda.pt
Loading model ...
Traceback (most recent call last):
  File "D:\AI\oobabooga\oobabooga-windows\text-generation-webui\server.py", line 346, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\AI\oobabooga\oobabooga-windows\text-generation-webui\modules\models.py", line 103, in load_model
    model = load_quantized(model_name)
  File "D:\AI\oobabooga\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 136, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "D:\AI\oobabooga\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 63, in _load_quant
    model.load_state_dict(torch.load(checkpoint), strict=False)
  File "D:\AI\oobabooga\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\AI\oobabooga\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "D:\AI\oobabooga\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 1142, in persistent_load
    typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "D:\AI\oobabooga\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 1112, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 35389440 bytes.
Press any key to continue . . .`

**Comment by TimDettmers** [comment]
Thank you for your report. This is an error where you run out of CPU memory. It is not related to bitsandbytes but I want to give you a space to discuss it. I close this issue, but please continue your discussion in issue #294 which is a duplicate.
