### ISSUE TITLE
Error with AI

### ISSUE THREAD

**Issue by TRKiller** [TimDettmers/bitsandbytes#299]
Hi! Was using new AI to test it out. I was starting it all the time by "start-webui-vicuna-gpu" bat, and it Worked, but has a problem with "CUDA out of memory" that I fixed somehow. Then I decided to start "Start-WebUI" bat, and it happened:

Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: C:\Users\anton\Desktop\AI\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary C:\Users\anton\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
Auto-assiging --gpu-memory 7 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Loading checkpoint shards: 0%| | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
File "C:\Users\anton\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 442, in load_state_dict
return torch.load(checkpoint_file, map_location="cpu")
File "C:\Users\anton\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 791, in load
with _open_file_like(f, 'rb') as opened_file:
File "C:\Users\anton\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 271, in _open_file_like
return _open_file(name_or_buffer, mode)
File "C:\Users\anton\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\torch\serialization.py", line 252, in init
super().init(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models\anon8231489123_vicuna-13b-GPTQ-4bit-128g\pytorch_model-00001-of-00003.bin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\anton\Desktop\AI\oobabooga-windows\text-generation-webui\server.py", line 347, in
shared.model, shared.tokenizer = load_model(shared.model_name)
File "C:\Users\anton\Desktop\AI\oobabooga-windows\text-generation-webui\modules\models.py", line 171, in load_model
model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
File "C:\Users\anton\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
return model_class.from_pretrained(
File "C:\Users\anton\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2736, in from_pretrained
) = cls._load_pretrained_model(
File "C:\Users\anton\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 3050, in _load_pretrained_model
state_dict = load_state_dict(shard_file)
File "C:\Users\anton\Desktop\AI\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 445, in load_state_dict
with open(checkpoint_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models\anon8231489123_vicuna-13b-GPTQ-4bit-128g\pytorch_model-00001-of-00003.bin'
To continue press any key...

**Comment by TimDettmers** [comment]
Thank you for your report. This does not seem to be a problem with bitsandbytes, because bitsandbytes loads without any error. The error lies in that you have not yet downloaded the model or you filepath points to a model that does not exist.

**Comment by TRKiller** [comment]
But I have downloaded a model for this thing. Why then it says that my path is wrong?
