### ISSUE TITLE
Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by Samsuditana** [TimDettmers/bitsandbytes#302]
ibleedcaffeine@gmail.com
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: F:\TRubybot\one-click-installers\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
F:\TRubybot\one-click-installers\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary F:\TRubybot\one-click-installers\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll...
The following models are available:

1. autobot
2. facebook_opt-6.7b
3. gpt4-x-alpaca-13b-native-4bit-128g
4. gpt4all
5. jquave_gpt4all-lora-unfiltered-quantized
6. llama-cpp-python-main
7. nomic-ai_gpt4all-lora
8. zpn_llama-7b

Which one do you want to load? 1-8

5

Loading jquave_gpt4all-lora-unfiltered-quantized...
Auto-assiging --gpu-memory 5 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Traceback (most recent call last):
  File "F:\TRubybot\one-click-installers\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 442, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "F:\TRubybot\one-click-installers\installer_files\env\lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "F:\TRubybot\one-click-installers\installer_files\env\lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: could not find MARK

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\TRubybot\one-click-installers\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 446, in load_state_dict
    if f.read(7) == "version":
  File "F:\TRubybot\one-click-installers\installer_files\env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 38: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\TRubybot\one-click-installers\text-generation-webui\server.py", line 351, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "F:\TRubybot\one-click-installers\text-generation-webui\modules\models.py", line 171, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "F:\TRubybot\one-click-installers\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "F:\TRubybot\one-click-installers\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2504, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "F:\TRubybot\one-click-installers\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 458, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'models\jquave_gpt4all-lora-unfiltered-quantized\pytorch_model.bin' at 'models\jquave_gpt4all-lora-unfiltered-quantized\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
Press any key to continue . . .

**Comment by TimDettmers** [comment]
Thank you for your report. This does not seem to be a problem with bitsandbytes, because bitsandbytes loads without any error. The error lies seems to be that you try to load a model checkpoint that does not exist or is corrupted.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
