### ISSUE TITLE
kohya doesnt work

### ISSUE THREAD

**Issue by GiotaroKugio** [TimDettmers/bitsandbytes#316]
fatal: not a git repository (or any of the parent directories): .git
steps:   0%|                                                                                  | 0/1495 [00:00<?, ?it/s]epoch 1/1
WARNING:root:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Traceback (most recent call last):
  File "D:\kohya\kohya_ss\train_network.py", line 760, in <module>
    train(args)
  File "D:\kohya\kohya_ss\train_network.py", line 591, in train
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "D:\kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\utils\operations.py", line 490, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "D:\kohya\kohya_ss\venv\lib\site-packages\torch\amp\autocast_mode.py", line 12, in decorate_autocast
    return func(*args, **kwargs)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_condition.py", line 381, in forward
    sample, res_samples = downsample_block(
  File "D:\kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 612, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "D:\kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 216, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\diffusers\models\attention.py", line 484, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "D:\kohya\kohya_ss\venv\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kohya\kohya_ss\library\train_util.py", line 1792, in forward_xformers
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)  # 最適なのを選んでくれる
  File "D:\kohya\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 197, in memory_efficient_attention
    return _memory_efficient_attention(
  File "D:\kohya\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 298, in _memory_efficient_attention
    return _fMHA.apply(
  File "D:\kohya\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 43, in forward
    out, op_ctx = _memory_efficient_attention_forward_requires_grad(
  File "D:\kohya\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 326, in _memory_efficient_attention_forward_requires_grad
    out = op.apply(inp, needs_gradient=True)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\xformers\ops\fmha\cutlass.py", line 106, in apply
    out, lse = cls.OPERATOR(
  File "D:\kohya\kohya_ss\venv\lib\site-packages\torch\_ops.py", line 143, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: xformers::efficient_attention_forward_cutlass() expected at most 8 argument(s) but received 9 argument(s). Declaration: xformers::efficient_attention_forward_cutlass(Tensor query, Tensor key, Tensor value, Tensor? cu_seqlens_q, Tensor? cu_seqlens_k, int? max_seqlen_q, bool compute_logsumexp, bool causal) -> (Tensor, Tensor)
steps:   0%|                                                                                  | 0/1495 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\alegi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\alegi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\kohya\kohya_ss\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "D:\kohya\kohya_ss\venv\lib\site-packages\accelerate\commands\launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\kohya\\kohya_ss\\venv\\Scripts\\python.exe', 'train_network.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Users/alegi/Desktop/loradandy/img', '--resolution=512,512', '--output_dir=C:/Users/alegi/Desktop/loradandy/model', '--logging_dir=C:/Users/alegi/Desktop/loradandy/log', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-5', '--unet_lr=0.0001', '--network_dim=8', '--output_name=dandy', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=constant', '--train_batch_size=1', '--max_train_steps=1495', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--seed=1234', '--caption_extension=.txt', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=1', '--clip_skip=2', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by maozdemir** [comment]
did you even read the error?

https://pypi.org/project/triton/

**Comment by GiotaroKugio** [comment]
i did , but I didnt understand it. I solved it somehow anyways
