### ISSUE TITLE
why does oobabooba keep getting errors for bitsandbytes?

### ISSUE THREAD

**Issue by Anonym0us33** [TimDettmers/bitsandbytes#322]
```v5>python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin D:\venv_ooba5\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
D:\venv_ooba5\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
D:\venv_ooba5\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
D:\venv_ooba5\lib\site-packages\bitsandbytes\cuda_setup\main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary D:\venv_ooba5\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.9.6\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.9.6\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\User\.pyenv\pyenv-win\versions\3.9.6\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "D:\venv_ooba5\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\venv_ooba5\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\venv_ooba5\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\venv_ooba5\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\venv_ooba5\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\venv_ooba5\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```
what is the solution on windows?

nvcc --version
Cuda compilation tools, release 11.7, V11.7.99

nvidia-smi
Sun Apr 16 22:09:39 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 496.76       Driver Version: 496.76       CUDA Version: 11.5

**Comment by Anonym0us33** [comment]
i also get 
``` File "C:\Users\xxxx\.pyenv\pyenv-win\versions\3.9.6\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'clion32bit_g32' not found
```
after following the instructions for the useless conda tutorial. from march

**Comment by JOY-SWang** [comment]
> 

Have you solved the problem?

**Comment by ksylvan** [comment]
In your WSL Ubuntu, add the following two lines to your `~/.bashrc` and then quit that shell and restart it, and it will work.

```bash
export PATH="$PATH:/usr/local/cuda/bin"
export LD_LIBRARY_PATH="/usr/lib/wsl/lib:/usr/local/cuda/lib64"
```

@Anonym0us33 @JOY-SWang - I submitted a documentation PR about this here: https://github.com/TimDettmers/bitsandbytes/pull/337

**Comment by nivibilla** [comment]
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#mandatory-actions

Also written here

**Comment by ksylvan** [comment]
@nivibilla I don't see anything there referencing `/usr/lib/wsl/lib` - it does talk about the cuda binary and library paths (which can be generic, like `/usr/local/cuda`, as those are symlinks to the real directories).

**Comment by nivibilla** [comment]
You're right, I had to change the path manually. It says that the paths may not be right. Just put it there for reference

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
