### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'device'

### ISSUE THREAD

**Issue by guihonghao** [TimDettmers/bitsandbytes#327]
I run generate.py on 3090 （24GB），but meet following error **“AttributeError: 'NoneType' object has no attribute 'device‘”**，How can I solve it?

Traceback (most recent call last):
  File "inference.py", line 140, in <module>
    fire.Fire(main)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "inference.py", line 134, in main
    result = evaluate(instruction=record['instruction'], input=record['input'])
  File "inference.py", line 115, in evaluate
    generation_output = model.generate(
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/peft/peft_model.py", line 580, in generate
    return self.base_model.generate(**kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/transformers/generation/utils.py", line 1437, in generate
    return self.greedy_search(
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/transformers/generation/utils.py", line 2248, in greedy_search
    outputs = self(
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/peft/tuners/lora.py", line 502, in forward
    result = super().forward(x)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/bitsandbytes/nn/modules.py", line 320, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py", line 500, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py", line 340, in forward
    state.CxB, state.SB = F.transform(state.CB, to_order=formatB)
  File "/data/guihh/anaconda3/envs/adakgc/lib/python3.8/site-packages/bitsandbytes/functional.py", line 1724, in transform
    prev_device = pre_call(A.device)
AttributeError: 'NoneType' object has no attribute 'device'

**Comment by wpy-hd** [comment]
Hello, I meet the same problem, and i'm sure i have passed the right input format. How do you solve your problem? Can you help me?

**Comment by guihonghao** [comment]
I solved it by the following modifies:
from peft import (
    LoraConfig,
    PeftModel,
    get_peft_model,
    set_peft_model_state_dict,
)
from peft.utils import WEIGHTS_NAME

    if device == "cuda":
        model = LlamaForCausalLM.from_pretrained(
            base_model,
            load_in_8bit=load_8bit,
            torch_dtype=torch.float16,
            device_map="auto",
        )
        config = LoraConfig.from_pretrained(lora_weights)
        model = get_peft_model(model, config) 
        adapters_weights = torch.load(os.path.join(lora_weights, WEIGHTS_NAME), map_location=model.device)
        model = set_peft_model_state_dict(model, adapters_weights)

**Comment by wangyongshuai88** [comment]
I also encountered the same issue
