### ISSUE TITLE
The installed version of bitsandbytes was loaded without gpu support 

### ISSUE THREAD

**Issue by dangelo352** [TimDettmers/bitsandbytes#329]
bin C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
CUDA SETUP: Loading binary C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\__main__.py", line 49, in generate_bug_report_information
    paths = find_file_recursive(os.environ['CONDA_PREFIX'], '*cuda*so')
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

**Comment by dangelo352** [comment]
and when i try another version like the windows fork 
I get 

Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA SETUP: Loading binary C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "C:\MINIGPT\MiniGPT-4\demo.py", line 59, in <module>
    model = model_cls.from_config(model_config).to('cuda:0')
  File "C:\MINIGPT\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 241, in from_config
    model = cls(
  File "C:\MINIGPT\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 89, in __init__
    self.llama_model = LlamaForCausalLM.from_pretrained(
  File "C:\Users\Dangelo\anaconda3\envs\minigpt4\lib\site-packages\transformers\modeling_utils.py", line 2740, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.
