### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by clzzw666** [TimDettmers/bitsandbytes#380]
I'm trying to run Mini GPT-4, but it suggests

S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] Not found a specified application. 'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?

warn(

Initializing Chat

Loading VIT

Loading VIT Done

Loading Q-Former

Loading Q-Former Done

Loading LLAMA

=== sync, corrected by elderman ==

Welcome to bitsandbytes. Welcome to bitsandbytes. For bug reports, please submit your error trace to: For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

=======================================

S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('D:/Java18/jdk-18.0.1.1'), WindowsPath ('C:/Users/Administrator/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/LocalCache/local-packages/Python39/site-packages'), WindowsPath('C:/cmder'), WindowsPath('S:/本地chat-GPT/mini-gpt4/MiniGPT-4-v1/MiniGPT-4/venv/Lib/site-packages/cv2/../../../x64/vc14/bin'), WindowsPath(''D:/python3.9.5'), WindowsPath('C:/Program Files/MySQL/MySQL Server 5.7/bin'), WindowsPath('D:/python3.9.5/Scripts'), WindowsPath('D:/TDM-'), WindowsPath('D:/Microsoft VS Code/bin'), WindowsPath('CC-64/bin'), WindowsPath('D:/nodejs 18.15.0'), WindowsPath('C:/Users/Administrator/Desktop/Language/Pythonrestructuring English 741;/Jump')

warn(msg)

CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cudart64_110.dll

CUDA SETUP: Highest compute capability among GPUs detected: 7.5

CUDA SETUP: Detected CUDA version 116

CUDA SETUP: Loading binary S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...

Loading checkpoint shards: 0%. 0/2 [00:15<?, ?it/s]

Traceback (most recent call last):

Local chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\demo.py", line 60, in <module>

model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))

File "S:\local chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 243, in from_config

model = cls(

File "S:\local chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 90, in _init__

self.llama_model = LlamaForCausalLM.from_pretrained(

File "S:\local chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\transformers\modeling_utils.py", line 2795, in from_pretrained

= cl._ load_pretrained_model(

"S:\local chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\transformers\modeling_utils.py", line 3123, in _load_pretrained_model

new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(

File "S:\local chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\transformers\modeling_utils.py", line 706, in _load_state_dict_into_meta_model

set_module_8bit_tensor_to_device(

File "S:\local chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\transformers\utils\bitsandbytes.py", line 78, in set_module_8bit_tensor_to_device

new_value = bnb.nn.Int8Params(new_value, requires_grad=False, has_fp16_weights=has_fp16_weights).to(device)

File "S:\local chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\bitsandbytes\nn\modules.py", line 196, in to

return self.cuda(device)

File "S:\local chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\bitsandbytes\nn\modules.py", line 160, in

CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)

File "S:\local chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\bitsandbytes\functional.py", line 1629, in double_quant

out_row = torch.zeros(A.shape, device=device, dtype=torch.int8)

RuntimeError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 4.00 GiB total capacity; 3.35 GiB already allocated; 0 bytes free; 3.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by clzzw666** [comment]
I try it again.
But it report errors agian.
Initializing Chat
Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Loading LLAMA

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('D:/python3.9.5'), WindowsPath('D:/Microsoft VS Code/bin'), WindowsPath('D:/nodejs 18.15.0'), WindowsPath('C:/Users/Administrator/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0/LocalCache/local-packages/Python39/site-packages'), WindowsPath('C:/Program Files/MySQL/MySQL Server 5.7/bin'), WindowsPath('D:/Java18/jdk-18.0.1.1'), WindowsPath('C:/Users/Administrator/Desktop/语言/Python编程入门指南--实例源码/源码/下册33+5/20/微信跳一跳辅助工具（修改兼容8.0系统）/Jump'), WindowsPath('D:/TDM-'), WindowsPath('C:/cmder'), WindowsPath('CC-64/bin'), WindowsPath('S:/本地chat-GPT/mini-gpt4/MiniGPT-4-v1/MiniGPT-4/venv/Lib/site-packages/cv2/../../x64/vc14/bin'), WindowsPath('D:/python3.9.5/Scripts')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
Loading checkpoint shards:   0%|                                                                 | 0/2 [00:43<?, ?it/s]
Traceback (most recent call last):
  File "S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\demo.py", line 60, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 243, in from_config
    model = cls(
  File "S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\minigpt4\models\mini_gpt4.py", line 90, in __init__
    self.llama_model = LlamaForCausalLM.from_pretrained(
  File "S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\transformers\modeling_utils.py", line 2795, in from_pretrained
    ) = cls._load_pretrained_model(
  File "S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\transformers\modeling_utils.py", line 3123, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\transformers\modeling_utils.py", line 706, in _load_state_dict_into_meta_model
    set_module_8bit_tensor_to_device(
  File "S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\transformers\utils\bitsandbytes.py", line 78, in set_module_8bit_tensor_to_device
    new_value = bnb.nn.Int8Params(new_value, requires_grad=False, has_fp16_weights=has_fp16_weights).to(device)
  File "S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\bitsandbytes\nn\modules.py", line 196, in to
    return self.cuda(device)
  File "S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\bitsandbytes\nn\modules.py", line 160, in cuda
    CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)
  File "S:\本地chat-GPT\mini-gpt4\MiniGPT-4-v1\MiniGPT-4\venv\lib\site-packages\bitsandbytes\functional.py", line 1629, in double_quant
    out_row = torch.zeros(A.shape, device=device, dtype=torch.int8)
RuntimeError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 4.00 GiB total capacity; 3.35 GiB already allocated; 0 bytes free; 3.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
