### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'device'

### ISSUE THREAD

**Issue by wengieeee** [TimDettmers/bitsandbytes#390]
执行多轮对话交互接口webui 脚本时，界面可以打开，但是无法进行对话，报错如下：
**AttributeError: 'NoneType' object has no attribute 'device'**
请问这种情况有遇到过吗？

![image](https://github.com/TimDettmers/bitsandbytes/assets/16257260/21954d8e-9d94-45cd-8015-ad9e28ec6334)

python ./Chinese-Vicuna/interaction.py --lora_path Facico/Chinese-Vicuna-lora-7b-3epoch-belle-and-guanaco --use_local 0

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /mnt/data/cuda-11.6/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 116
CUDA SETUP: Loading binary /mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116.so...
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'.
The class this function is called from is 'LlamaTokenizer'.
Facico/Chinese-Vicuna-lora-7b-3epoch-belle-and-guanaco/adapter_model.bin
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 33/33 [00:11<00:00,  3.00it/s]
/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/gradio/components.py:4193: UserWarning: The 'color_map' parameter has been deprecated.
  warnings.warn("The 'color_map' parameter has been deprecated.")
/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/gradio/components.py:153: UserWarning: Unknown style parameter: color_map
  warnings.warn(f"Unknown style parameter: {key}")
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://bfe3ccf49a5f6a81ec.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
test1
5
Traceback (most recent call last):
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/gradio/routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/gradio/blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/gradio/blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/data/code/./Chinese-Vicuna/interaction.py", line 142, in interaction
    generation_output = model.generate(
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/peft/peft_model.py", line 627, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/transformers/generation/utils.py", line 1524, in generate
    return self.beam_search(
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/transformers/generation/utils.py", line 2810, in beam_search
    outputs = self(
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/peft/tuners/lora.py", line 576, in forward
    result = super().forward(x)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/bitsandbytes/nn/modules.py", line 242, in forward
    out = bnb.matmul(x, self.weight, bias=self.bias, state=self.state)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 488, in matmul
    return MatMul8bitLt.apply(A, B, out, bias, state)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 317, in forward
    state.CxB, state.SB = F.transform(state.CB, to_order=formatB)
  File "/mnt/data/deploy/venv_vicuna/lib/python3.9/site-packages/bitsandbytes/functional.py", line 1698, in transform
    prev_device = pre_call(A.device)
**AttributeError: 'NoneType' object has no attribute 'device'**

**Comment by Tracin** [comment]
Same problem, `Int8Params.CB` is None which is a bug I think.

**Comment by wangyongshuai88** [comment]
请问大佬解决了吗？我也是一样的问题。

**Comment by apple55bc** [comment]
> 

from-pretrained 参数 device_map={"":0} 就好了，不知为何

**Comment by wangyongshuai88** [comment]
> 

感谢，的确这样就好了。
