### ISSUE TITLE
Unknown CUDA exception! Please check your CUDA install. It might also be that your GPU is too old.

### ISSUE THREAD

**Issue by Bluejay47** [TimDettmers/bitsandbytes#418]
Probably some dumb mistake on my part... BitsAndBytes in the oobabooga / text-generation-webui system seems to work fine in its Conda env on the same system.

Installed with: pip install bitsandbytes==0.38.1; platform_system != "Windows"

I've also tried installing from source, same error

Error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 7
      4 from accelerate import init_empty_weights, load_checkpoint_and_dispatch, infer_auto_device_map
      5 from transformers import AutoConfig, AutoModelForCausalLM
----> 7 model = AutoModelForCausalLM.from_pretrained(
      8     checkpoint,
      9     device_map='auto',
     10     load_in_8bit=True,
     11     torch_dtype=torch.float16
     12 )
     14 print(model.hf_device_map)

File [~/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:467](https://vscode-remote+ssh-002dremote-002bchiharu.vscode-resource.vscode-cdn.net/models/chiharu/~/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py:467), in _BaseAutoModelClass.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    465 elif type(config) in cls._model_mapping.keys():
    466     model_class = _get_model_class(config, cls._model_mapping)
--> 467     return model_class.from_pretrained(
    468         pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs, **kwargs
    469     )
    470 raise ValueError(
    471     f"Unrecognized configuration class {config.__class__} for this kind of AutoModel: {cls.__name__}.\n"
    472     f"Model type should be one of {', '.join(c.__name__ for c in cls._model_mapping.keys())}."
    473 )

File [~/.local/lib/python3.10/site-packages/transformers/modeling_utils.py:2777](https://vscode-remote+ssh-002dremote-002bchiharu.vscode-resource.vscode-cdn.net/models/chiharu/~/.local/lib/python3.10/site-packages/transformers/modeling_utils.py:2777), in PreTrainedModel.from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
...
--> 392     func = self._FuncPtr((name_or_ordinal, self))
    393     if not isinstance(name_or_ordinal, int):
    394         func.__name__ = name_or_ordinal

AttributeError: /home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cget_col_row_stats
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?dfdd8c86-dc4d-40e7-abb9-e26d27030281) or open in a [text editor](command:workbench.action.openLargeOutput?dfdd8c86-dc4d-40e7-abb9-e26d27030281). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
```

System Info:

Host: KVM/QEMU (Standard PC (Q35 + ICH9, 2009) pc-q35-7.1) 
Kernel: 5.15.0-72-generic 
Shell: bash 5.1.16 
CPU: AMD Ryzen 9 5900X (22) @ 3.700GHz 
GPU: NVIDIA 01:00.0 NVIDIA Corporation Device 2684 
Memory: 4716MiB / 58821MiB 

```
$ echo $LD_LIBRARY_PATH
/usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/:/usr/local/cuda-12.1/targets/x86_64-linux/lib/:/usr/local/cuda-12.0/lib64/stubs/:/usr/local/cuda-12.0/lib64
```

```
$ echo $CUDA_HOME
/usr/local/cuda-12.1
```

```
$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
```

Debug Report

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda-12.0/lib64/stubs'), PosixPath('/usr/local/cuda-12.0/lib64')}
  warn(msg)
Unknown CUDA exception! Please check your CUDA install. It might also be that your GPU is too old.
Unknown CUDA exception! Please check your CUDA install. It might also be that your GPU is too old.
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudart.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/jerry/.local/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda102_nocublaslt.so
/home/jerry/.local/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/jerry/.local/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/jerry/.local/lib/python3.10/site-packages/torch/lib/libc10_cuda.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
 /usr/local/cuda-12.1/targets/x86_64-linux/lib/ CUDA PATHS +
/usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/libcuda.so
 /usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/ CUDA PATHS
/usr/local/cuda-12.1/targets/x86_64-linux/lib/stubs/libcuda.so

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
COMPUTE_CAPABILITIES_PER_GPU = []
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

name 'str2optimizer32bit' is not defined
```

Code:

```
checkpoint="/models/models/llm/OpenAssistant_stablelm-7b-sft-v7-epoch-3"

from accelerate import init_empty_weights, load_checkpoint_and_dispatch, infer_auto_device_map
from transformers import AutoConfig, AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained(
    checkpoint,
    device_map='auto',
    load_in_8bit=True,
    torch_dtype=torch.float16
)

print(model.hf_device_map)
```

**Comment by Bluejay47** [comment]
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090         On | 00000000:01:00.0 Off |                  Off |
|  0%   44C    P8               19W / 450W|   3271MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1299      C   /bin/python                                3268MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by Bluejay47** [comment]
The following bug report resulted after reinstalling from source again (both with CUDA_VERSION=121 and CUDA_VERSION=121_nomatmul)

```
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121_nomatmul
python setup.py install
CUDA SETUP: Setup Failed!
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121_nomatmul
python setup.py install
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

**Comment by FishWoWater** [comment]
same problem on ubuntu18.04+cuda11.7+compile from source

**Comment by songkea** [comment]
4090  me too    一样的错误.

**Comment by LebronXierunfeng** [comment]
> The following bug report resulted after reinstalling from source again (both with CUDA_VERSION=121 and CUDA_VERSION=121_nomatmul)
> 
> ```
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please run
> 
> python -m bitsandbytes
> 
>  and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> ================================================================================
> bin /usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/libbitsandbytes_cpu.so
> /usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda-12.0/lib64'), PosixPath('/usr/local/cuda-12.0/lib64/stubs')}
>   warn(msg)
> Unknown CUDA exception! Please check your CUDA install. It might also be that your GPU is too old.
> Unknown CUDA exception! Please check your CUDA install. It might also be that your GPU is too old.
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda-12.1/targets/x86_64-linux/lib/libcudart.so
> /usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/cuda_setup/main.py:145: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
>   warn(msg)
> CUDA SETUP: Detected CUDA version 121
> CUDA SETUP: Required library version not found: libbitsandbytes_cpu.so. Maybe you need to compile it from source?
> CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
> 
> ================================================ERROR=====================================
> CUDA SETUP: CUDA detection failed! Possible reasons:
> 1. CUDA driver not installed
> 2. CUDA not installed
> 3. You have multiple conflicting CUDA libraries
> 4. Required library not pre-compiled for this bitsandbytes release!
> CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
> CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
> ================================================================================
> 
> CUDA SETUP: Something unexpected happened. Please compile from source:
> git clone git@github.com:TimDettmers/bitsandbytes.git
> cd bitsandbytes
> CUDA_VERSION=121_nomatmul
> python setup.py install
> CUDA SETUP: Setup Failed!
> CUDA SETUP: Something unexpected happened. Please compile from source:
> git clone git@github.com:TimDettmers/bitsandbytes.git
> cd bitsandbytes
> CUDA_VERSION=121_nomatmul
> python setup.py install
> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
>     __import__(pkg_name)
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/__init__.py", line 6, in <module>
>     from . import cuda_setup, utils, research
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/research/__init__.py", line 1, in <module>
>     from . import nn
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/research/nn/__init__.py", line 1, in <module>
>     from .modules import LinearFP8Mixed, LinearFP8Global
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/research/nn/modules.py", line 8, in <module>
>     from bitsandbytes.optim import GlobalOptimManager
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/optim/__init__.py", line 6, in <module>
>     from bitsandbytes.cextension import COMPILED_WITH_CUDA
>   File "/usr/local/lib/python3.10/dist-packages/bitsandbytes-0.38.1-py3.10.egg/bitsandbytes/cextension.py", line 20, in <module>
>     raise RuntimeError('''
> RuntimeError:
>         CUDA Setup failed despite GPU being available. Please run the following command to get more information:
> 
>         python -m bitsandbytes
> 
>         Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
>         to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
>         and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
> ```

same problem on v100 + cuda11.8

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
