### ISSUE TITLE
Bug Report Quadro RTX 8000 Cuda 12.0

### ISSUE THREAD

**Issue by forkbabu** [TimDettmers/bitsandbytes#445]
```
(peft) 21sd45@sasquatch:/ingenuity_NAS/21sd45_nas/21sd45_mount/$ python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/21sd45/miniconda3/envs/peft did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//0161-130-15-58-222.ngrok-free.app/proxy/{{port}}'), PosixPath('https')}
  warn(msg)
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/tmp/krb5cc_10105_YmAUSb'), PosixPath('FILE')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 120
CUDA SETUP: Loading binary /home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so

Traceback (most recent call last):
  File "/home/21sd45/miniconda3/envs/peft/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/21sd45/miniconda3/envs/peft/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 54, in generate_bug_report_information
    paths = find_file_recursive('/usr/local', '*cuda*so')
  File "/home/21sd45/miniconda3/envs/peft/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?
```

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.

**Comment by zihaohe123** [comment]
I'm having the same issue. and I'm using the latest version 0.41.1

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
