### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by Fengliang-hhh** [TimDettmers/bitsandbytes#457]
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-11.8/lib64/libcudart.so
Traceback (most recent call last):
  File "/usr/project/code/lora-scripts-gui/./sd-scripts/train_network.py", line 783, in <module>
    train(args)
  File "/usr/project/code/lora-scripts-gui/./sd-scripts/train_network.py", line 214, in train
    optimizer_name, optimizer_args, optimizer = train_util.get_optimizer(args, trainable_params)
  File "/usr/project/code/lora-scripts-gui/sd-scripts/library/train_util.py", line 2595, in get_optimizer
    import bitsandbytes as bnb
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 15, in initialize
    binary_name = evaluate_cuda_setup()
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 131, in evaluate_cuda_setup
    cuda = get_cuda_lib_handle()
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 60, in get_cuda_lib_handle
    check_cuda_result(cuda, cuda.cuInit(0))
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 29, in check_cuda_result
    print(f"CUDA exception! Error code: {error_str.value.decode()}")
AttributeError: 'NoneType' object has no attribute 'decode'
Traceback (most recent call last):
  File "/root/package/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/package/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1114, in <module>
    main()
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1110, in main
    launch_command(args)
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1104, in launch_command
    simple_launcher(args)
  File "/usr/project/code/lora-scripts-gui/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 567, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.
