### ISSUE TITLE
Permission denied, install bitsandbytes on SLURM system

### ISSUE THREAD

**Issue by BaohaoLiao** [TimDettmers/bitsandbytes#460]
Hi,
thank you for this great work. I met the following problem when I ran **python -m bitsandbytes**

This may be caused because I don't have access to some files and directories on the SLURM system. Do you know how I could avoid this? 

```
Traceback (most recent call last):
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 105, in run_cuda_setup
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 386, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 271, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 212, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 207, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 183, in remove_non_existent_dirs
    raise exc
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 179, in remove_non_existent_dirs
    if path.exists():
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/pathlib.py", line 1407, in exists
    self.stat()
  File "/home/bliao/miniconda3/envs/qlora/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/var/slurm/checkpoint'
```

**Comment by BaohaoLiao** [comment]
This problem is resolved. I just install it from scratch and it disappears!
