### ISSUE TITLE
LoRA installation problem

### ISSUE THREAD

**Issue by JuliaJulia27** [TimDettmers/bitsandbytes#474]
CUDA SETUP: Loading binary C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
use 8-bit AdamW optimizer | {}
Traceback (most recent call last):
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\train_network.py", line 783, in <module>
    train(args)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\train_network.py", line 253, in train
    unet, text_encoder, network, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\accelerator.py", line 1122, in prepare
    result = tuple(
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\accelerator.py", line 1123, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\accelerator.py", line 977, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\accelerator.py", line 1197, in prepare_model
    model = model.to(self.device)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 4.00 GiB total capacity; 2.31 GiB already allocated; 24.20 MiB free; 2.38 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\launch.py", line 923, in launch_command
    simple_launcher(args)
  File "C:\Kohya_ss-GUI-LoRA-Portable-main\Kohya_ss-GUI-LoRA-Portable-main\venv\lib\site-packages\accelerate\commands\launch.py", line 579, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Kohya_ss-GUI-LoRA-Portable-main\\Kohya_ss-GUI-LoRA-Portable-main\\venv\\Scripts\\python.exe', 'train_network.py', '--enable_bucket', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--train_data_dir=C:/Kohya_ss-GUI-LoRA-Portable-main', '--resolution=512,512', '--output_dir=C:/Kohya_ss-GUI-LoRA-Portable-main', '--network_alpha=1', '--save_model_as=safetensors', '--network_module=networks.lora', '--text_encoder_lr=5e-05', '--unet_lr=0.0001', '--network_dim=8', '--output_name=Julia', '--lr_scheduler_num_cycles=1', '--learning_rate=0.0001', '--lr_scheduler=cosine', '--lr_warmup_steps=200', '--train_batch_size=1', '--max_train_steps=2000', '--save_every_n_epochs=1', '--mixed_precision=fp16', '--save_precision=fp16', '--cache_latents', '--optimizer_type=AdamW8bit', '--max_data_loader_n_workers=0', '--bucket_reso_steps=64', '--xformers', '--bucket_no_upscale']' returned non-zero exit status 1.

**Comment by TimDettmers** [comment]
This seems to be an issue where you load a too-large model on a too-small GPU. Furthermore, note that Windows is currently not supported. You can find more information here: #30
