### ISSUE TITLE
OOM even though 2.5GiB free space left after loading model weights

### ISSUE THREAD

**Issue by phalexo** [TimDettmers/bitsandbytes#477]
Is anyone actually looking at the issues?

  0%|                                                                                                                                              | 0/10000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/developer/qlora/qlora.py", line 767, in <module>
    train()
  File "/home/developer/qlora/qlora.py", line 729, in train
    train_result = trainer.train(resume_from_checkpoint=checkpoint_dir)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/transformers/trainer.py", line 1696, in train
    return inner_training_loop(
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/transformers/trainer.py", line 1973, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/transformers/trainer.py", line 2787, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/transformers/trainer.py", line 2819, in compute_loss
    outputs = model(**inputs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/peft/peft_model.py", line 686, in forward
    return self.base_model(
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 569, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 565, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 305, in forward
    hidden_states = self.mlp(hidden_states)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 155, in forward
    return self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/peft/tuners/lora.py", line 768, in forward
    result = super().forward(x)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/nn/modules.py", line 219, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/autograd/_functions.py", line 564, in matmul_4bit
    return MatMul4Bit.apply(A, B, out, bias, quant_state)
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/developer/mambaforge/envs/Guanaco/lib/python3.10/site-packages/bitsandbytes-0.39.0-py3.10.egg/bitsandbytes/autograd/_functions.py", line 512, in forward
    output = torch.nn.functional.linear(A, F.dequantize_fp4(B, state).to(A.dtype).t(), bias)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 688.00 MiB (GPU 0; 11.93 GiB total capacity; 10.57 GiB already allocated; 421.88 MiB free; 10.97 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
  0%|

**Comment by phalexo** [comment]
The GPU VRAM is 12.28GiB, not sure why the error message is reporting 11.93GiB.

**Comment by TimDettmers** [comment]
If you are using accelerate, then most of the memory due to the activation gradients are allocated on GPU one. This can cause problems like these. To avoid this problem use the `device_map='balanced_low_0` value. More information here:  https://huggingface.co/docs/accelerate/usage_guides/big_modeling#designing-a-device-map

I think more documentation could help people figure these things out as this is the second issue that I have seen on this, but inherently, this is not a bitsandbytes issue.

**Comment by TimDettmers** [comment]
As I note in #451, this is actually not a Windows problem but a problem with Maxwell GPUs that have SM 5.2. While uniform memory has been supported since Keplera GPUs, it has been overhauled since  Pascal and Volta. This means, Paged optimizers break support for Maxwell GPUs.

As such, the main question is whether I want to support Maxwell GPUs. These GPUs are now 9 years old and I think I will no longer support them. I will think about this more.

**Comment by TimDettmers** [comment]
This has been fixed and pushed to pip. Memory problems might remain, but these are Windows-specific and there is nothing I can do about that. Thank you, this was an important bugfix.
