### ISSUE TITLE
Permission denied: '/root/zhaoq/neo4j-community-3.5.30' , Why  neo4j was mentioned?

### ISSUE THREAD

**Issue by eatinghungry** [TimDettmers/bitsandbytes#480]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Traceback (most recent call last):
  File "/home/renchao/anaconda3/envs/genie/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/renchao/anaconda3/envs/genie/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/renchao/anaconda3/envs/genie/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/cuda_setup/main.py", line 105, in run_cuda_setup
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/cuda_setup/main.py", line 386, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/cuda_setup/main.py", line 271, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/cuda_setup/main.py", line 212, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/cuda_setup/main.py", line 207, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/cuda_setup/main.py", line 183, in remove_non_existent_dirs
    raise exc
  File "/home/renchao/llama/bitsandbytes/bitsandbytes/cuda_setup/main.py", line 179, in remove_non_existent_dirs
    if path.exists():
  File "/home/renchao/anaconda3/envs/genie/lib/python3.8/pathlib.py", line 1407, in exists
    self.stat()
  File "/home/renchao/anaconda3/envs/genie/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/root/zhaoq/neo4j-community-3.5.30'

**Comment by TimDettmers** [comment]
This is a problem with storing a file on a path that is not accessible to your user.  This is not a bitsandbytes issue.
