### ISSUE TITLE
ValueError: Can't read templates/alpaca.json

### ISSUE THREAD

**Issue by yifeiw7** [TimDettmers/bitsandbytes#481]
running alpaca lora on remote server, I checked the file alpaca.json exists in the right location and has the same thing as the original file on github but I still got this error 
```  File "/home/myname/alpaca-lora-main/predict_test.py", line 48, in <module>
    prompter = Prompter(prompt_template)
  File "/home/myname/alpaca-lora-main/utils/prompter.py", line 20, in __init__
    raise ValueError(f"Can't read {file_name}")
ValueError: Can't read templates/alpaca.json 
```

what can i do to fix this? here's the longer error message I got from `python -m bitsandbytes` 

```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/myname/miniconda3/pkgs/cudatoolkit-11.1.1-ha002fc5_10/lib/libcudart.so
/home/myname/miniconda3/lib/libcudart.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++


+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda112.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda112_nocublaslt.so
/home/myname/miniconda3/pkgs/cudatoolkit-11.1.1-ha002fc5_10/lib/libcudart.so
/home/myname/miniconda3/lib/libcudart.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
Traceback (most recent call last):
  File "/home/myname/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/myname/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/home/myname/.local/lib/python3.8/site-packages/bitsandbytes/__main__.py", line 66, in generate_bug_report_information
    lib_path = os.environ['LD_LIBRARY_PATH'].strip()
  File "/home/myname/miniconda3/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'LD_LIBRARY_PATH'
```

**Comment by TimDettmers** [comment]
Sorry, this issue is not related to bitsandbytes. From the information given, I am unable to help you any further. I will close this issue as its not bitsandbytes related.

**Comment by kunkunkunkun1** [comment]
解决了吗，我也遇到这个问题
