### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Maxliag** [TimDettmers/bitsandbytes#497]
Traceback (most recent call last):
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 105, in run_cuda_setup
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 386, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 271, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 212, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 207, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 183, in remove_non_existent_dirs
    raise exc
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 179, in remove_non_existent_dirs
    if path.exists():
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/pathlib.py", line 1407, in exists
    self.stat()
  File "/home/maxl/anaconda3/envs/Vicuna/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/home/voicecomm/project/jdk1.8.0_301'

**Comment by TimDettmers** [comment]
Thank you for reporting this bug.

**Comment by saeedalahmari3** [comment]
I'm still having the same issue with the latest released version of bitsandbytes.

from bitsandbytes.cextension import COMPILED_WITH_CUDA                                                
  File "/home/s/saeed3/.conda/envs/LLM/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/s/saeed3/.conda/envs/LLM/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda
_setup/main.py", line 120, in run_cuda_setup
    binary_name, cudart_path, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/s/saeed3/.conda/envs/LLM/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda
_setup/main.py", line 337, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/s/saeed3/.conda/envs/LLM/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda
_setup/main.py", line 295, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/home/s/saeed3/.conda/envs/LLM/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda
_setup/main.py", line 232, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/home/s/saeed3/.conda/envs/LLM/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda
_setup/main.py", line 227, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "/home/s/saeed3/.conda/envs/LLM/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda
_setup/main.py", line 201, in remove_non_existent_dirs
    raise exc
  File "/home/s/saeed3/.conda/envs/LLM/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda
_setup/main.py", line 197, in remove_non_existent_dirs
    if path.exists():
  File "/home/s/saeed3/.conda/envs/LLM/lib/python3.9/pathlib.py", line 1424, in exists
    self.stat()
  File "/home/s/saeed3/.conda/envs/LLM/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/scratch/jobs/saeed3@cluster.osu.edu/98336'
srun: error: GPU41: task 0: Exited with exit code 1

**Comment by jprashant21** [comment]
PermissionError: [Errno 13] Permission denied: '/root/google_vm_config.lock'
