### ISSUE TITLE
Unusable on windows

### ISSUE THREAD

**Issue by chibiskuld** [TimDettmers/bitsandbytes#505]
Here is output from what I get for this:
```
+--------------------- Traceback (most recent call last) ---------------------+
| C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\runpy.py:194 |
| in _run_module_as_main                                                      |
|                                                                             |
|   191     main_globals = sys.modules["__main__"].__dict__                   |
|   192     if alter_argv:                                                    |
|   193         sys.argv[0] = mod_spec.origin                                 |
| > 194     return _run_code(code, main_globals, None,                        |
|   195                      "__main__", mod_spec)                            |
|   196                                                                       |
|   197 def run_module(mod_name, init_globals=None,                           |
|                                                                             |
| C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\runpy.py:87  |
| in _run_code                                                                |
|                                                                             |
|    84                        __loader__ = loader,                           |
|    85                        __package__ = pkg_name,                        |
|    86                        __spec__ = mod_spec)                           |
| >  87     exec(code, run_globals)                                           |
|    88     return run_globals                                                |
|    89                                                                       |
|    90 def _run_module_code(code, init_globals=None,                         |
|                                                                             |
| C:\JokenSoft\VRCAI\chat\__main__.py:30 in <module>                          |
|                                                                             |
|   27                                                                        |
|   28 import db                                                              |
|   29 import config                                                          |
| > 30 import gpt                                                             |
|   31 import api                                                             |
|                                                                             |
| C:\JokenSoft\VRCAI\chat\gpt\__init__.py:344 in <module>                     |
|                                                                             |
|   341                                                                       |
|   342         return payload                                                |
|   343                                                                       |
| > 344 gpt = GPT()                                                           |
|   345                                                                       |
|                                                                             |
| C:\JokenSoft\VRCAI\chat\gpt\__init__.py:65 in __init__                      |
|                                                                             |
|    62         self.loading = False                                          |
|    63                                                                       |
|    64         self.load_config()                                            |
| >  65         self.update_model()                                           |
|    66         if not self.model_details["accelerate"]:                      |
|    67             torch.cuda.set_device(self.gpu)                           |
|    68                                                                       |
|                                                                             |
| C:\JokenSoft\VRCAI\chat\gpt\__init__.py:93 in update_model                  |
|                                                                             |
|    90         if pid != self.model_details["id"]:                           |
|    91             if self.loaded:                                           |
|    92                 self.unload()                                         |
| >  93             self.load()                                               |
|    94         self.loading = False                                          |
|    95                                                                       |
|    96     def load(self):                                                   |
|                                                                             |
| C:\JokenSoft\VRCAI\chat\gpt\__init__.py:172 in load                         |
|                                                                             |
|   169             # if ("mosaicml" in self.model_details["name"]):          |
|   170             #    self.model_config.attn_config['attn_impl'] = 'triton |
|   171             # triton is currently not working for some reason, but pe |
| > 172             self.model = AutoModelForCausalLM.from_pretrained(        |
|   173                 self.model_details["name"],                           |
|   174                 config=self.model_config,                             |
|   175                 revision=self.model_details["revision"],              |
|                                                                             |
| C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-package |
| s\transformers\models\auto\auto_factory.py:479 in from_pretrained           |
|                                                                             |
|   476                 class_ref, pretrained_model_name_or_path, **hub_kwarg |
|   477             )                                                         |
|   478             _ = hub_kwargs.pop("code_revision", None)                 |
| > 479             return model_class.from_pretrained(                       |
|   480                 pretrained_model_name_or_path, *model_args, config=co |
|   481             )                                                         |
|   482         elif type(config) in cls._model_mapping.keys():               |
|                                                                             |
| C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-package |
| s\transformers\modeling_utils.py:2685 in from_pretrained                    |
|                                                                             |
|   2682             keep_in_fp32_modules = []                                |
|   2683                                                                      |
|   2684         if load_in_8bit or load_in_4bit:                             |
| > 2685             from .utils.bitsandbytes import get_keys_to_not_convert, |
|   2686                                                                      |
|   2687             llm_int8_skip_modules = quantization_config.llm_int8_ski |
|   2688             load_in_8bit_fp32_cpu_offload = quantization_config.llm_ |
|                                                                             |
| C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-package |
| s\transformers\utils\bitsandbytes.py:11 in <module>                         |
|                                                                             |
|     8                                                                       |
|     9                                                                       |
|    10 if is_bitsandbytes_available():                                       |
| >  11     import bitsandbytes as bnb                                        |
|    12     import torch                                                      |
|    13     import torch.nn as nn                                             |
|    14                                                                       |
|                                                                             |
| C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-package |
| s\bitsandbytes\__init__.py:6 in <module>                                    |
|                                                                             |
|    3 # This source code is licensed under the MIT license found in the      |
|    4 # LICENSE file in the root directory of this source tree.              |
|    5                                                                        |
| >  6 from . import cuda_setup, utils, research                              |
|    7 from .autograd._functions import (                                     |
|    8     MatmulLtState,                                                     |
|    9     bmm_cublas,                                                        |
|                                                                             |
| C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-package |
| s\bitsandbytes\research\__init__.py:1 in <module>                           |
|                                                                             |
| > 1 from . import nn                                                        |
|   2 from .autograd._functions import (                                      |
|   3     switchback_bnb,                                                     |
|   4     matmul_fp8_global,                                                  |
|                                                                             |
| C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-package |
| s\bitsandbytes\research\nn\__init__.py:1 in <module>                        |
|                                                                             |
| > 1 from .modules import LinearFP8Mixed, LinearFP8Global                    |
|   2                                                                         |
|                                                                             |
| C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-package |
| s\bitsandbytes\research\nn\modules.py:8 in <module>                         |
|                                                                             |
|    5 from torch import Tensor, device, dtype, nn                            |
|    6                                                                        |
|    7 import bitsandbytes as bnb                                             |
| >  8 from bitsandbytes.optim import GlobalOptimManager                      |
|    9 from bitsandbytes.utils import OutlierTracer, find_outlier_dims        |
|   10                                                                        |
|   11 T = TypeVar("T", bound="torch.nn.Module")                              |
|                                                                             |
| C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-package |
| s\bitsandbytes\optim\__init__.py:6 in <module>                              |
|                                                                             |
|    3 # This source code is licensed under the MIT license found in the      |
|    4 # LICENSE file in the root directory of this source tree.              |
|    5                                                                        |
| >  6 from bitsandbytes.cextension import COMPILED_WITH_CUDA                 |
|    7                                                                        |
|    8 from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit                |
|    9 from .adam import Adam, Adam8bit, Adam32bit, PagedAdam, PagedAdam8bit, |
|                                                                             |
| C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-package |
| s\bitsandbytes\cextension.py:20 in <module>                                 |
|                                                                             |
|   17     if lib is None and torch.cuda.is_available():                      |
|   18         CUDASetup.get_instance().generate_instructions()               |
|   19         CUDASetup.get_instance().print_log_stack()                     |
| > 20         raise RuntimeError('''                                         |
|   21         CUDA Setup failed despite GPU being available. Please run the  |
|   22                                                                        |
|   23         python -m bitsandbytes                                         |
+-----------------------------------------------------------------------------+
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following
command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA
libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the
information from python -m bitsandbytes
        and open an issue at:
https://github.com/TimDettmers/bitsandbytes/issues
```

And then python -m bitsandbytes:
```
$ python -m bitsandbytes
C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C'), WindowsPath('/Program Files/Git/etc/config.site')}
  warn(msg)
C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
  warn(msg)
C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\cuda_setup\main.py:149: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
Traceback (most recent call last):
  File "C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
False
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: Loading binary C:\Users\chibiskuld\AppData\Local\Programs\Python\Python38\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
```

**Comment by stoperro** [comment]
https://github.com/TimDettmers/bitsandbytes/issues/30

**Comment by ShanGor** [comment]
May you try to build from source on Windows, this post has a guide and fork that can be built on windows to fit your machine and CUDA version
ref to https://github.com/TimDettmers/bitsandbytes/issues/30#issuecomment-1595924414

**Comment by CHENJINGTANG** [comment]
> 

Excuse me, can you teach me how to operate

**Comment by CHENJINGTANG** [comment]
> 您可以尝试在 Windows 上从源代码构建，这篇文章有一个指南和分支，可以在 Windows 上构建以适合您的机器，并且 CUDA 版本 参考[#30（评论）](https://github.com/TimDettmers/bitsandbytes/issues/30#issuecomment-1595924414)



> May you try to build from source on Windows, this post has a guide and fork that can be built on windows to fit your machine and CUDA version ref to [#30 (comment)](https://github.com/TimDettmers/bitsandbytes/issues/30#issuecomment-1595924414)

Excuse me, can you teach me how to operate

**Comment by CHENJINGTANG** [comment]
> May you try to build from source on Windows, this post has a guide and fork that can be built on windows to fit your machine and CUDA version ref to [#30 (comment)](https://github.com/TimDettmers/bitsandbytes/issues/30#issuecomment-1595924414)

Excuse me, can you teach me how to operate

**Comment by TimDettmers** [comment]
Windows is currently not supported. You can find more information here: #30

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by mct-lrh** [comment]
@swumagic THANK YOU!!! I have been struggling with this for days, and even bitsandbytes-windows didn't work.  This works.  I can finally load my model and use it without errors.
