### ISSUE TITLE
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'

### ISSUE THREAD

**Issue by lucas0** [TimDettmers/bitsandbytes#516]
In the first lines of the script, while still importing PEFT.

is there any way to solve this?

```
Traceback (most recent call last):
  File "/home/ubuntu/empath/finetune_llm/run_finetuned_llama.py", line 2, in <module>
    from peft import PeftModel, PeftConfig
  File "/home/ubuntu/empath/finetune_llm/venv/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/home/ubuntu/empath/finetune_llm/venv/lib/python3.10/site-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/home/ubuntu/empath/finetune_llm/venv/lib/python3.10/site-packages/peft/peft_model.py", line 34, in <module>
    from .tuners import (
  File "/home/ubuntu/empath/finetune_llm/venv/lib/python3.10/site-packages/peft/tuners/__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "/home/ubuntu/empath/finetune_llm/venv/lib/python3.10/site-packages/peft/tuners/lora.py", line 731, in <module>
    class Linear8bitLt(bnb.nn.Linear8bitLt, LoraLayer):
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'
```

**Comment by lucas0** [comment]
Solved by installing this specific version of peft:

!pip install git+https://github.com/huggingface/peft@27af2198225cbb9e049f548440f2bd0fba2204aa --force-reinstall --no-deps

**Comment by senwen616** [comment]
> Solved by installing this specific version of peft:
> 
> !pip install git+https://github.com/huggingface/peft@27af2198225cbb9e049f548440f2bd0fba2204aa --force-reinstall --no-deps

not work for me, did anyone slove the problem? be very tanksful

**Comment by TimDettmers** [comment]
I think upgrading both PEFT and bitsandbytes should solve this issue. Please reopen this issue if you still find that this does not work.

**Comment by ihongxx** [comment]
$ sudo apt install gcc-10 g++-10
$ export CC=/usr/bin/gcc-10
$ export CXX=/usr/bin/g++-10
$ export CUDA_ROOT=/usr/local/cuda
$ ln -s /usr/bin/gcc-10 $CUDA_ROOT/bin/gcc
$ ln -s /usr/bin/g++-10 $CUDA_ROOT/bin/g++
$ git clone https://github.com/timdettmers/bitsandbytes.git
$ cd bitsandbytes
$ CUDA_HOME=/usr/local/cuda-11.6 CUDA_VERSION=116 make cuda11x
$ python setup.py install
I succeeded！
