### ISSUE TITLE
Example throws Tokenizer class LLaMATokenizer does not exist

### ISSUE THREAD

**Issue by lukaskellerstein** [TimDettmers/bitsandbytes#519]
I see an error for the example code in bitsandbytes. I am trying to find a minimal example that I can run, but so far without success. 

```
Traceback (most recent call last):
  File "/home/lukasmy_projects/main.py", line 17, in <module>
    tokenizer = AutoTokenizer.from_pretrained(model_name)
  File "/home/lukas/.cache/pypoetry/virtualenvs/project1-qDQav2yz-py3.10/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 688, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.
```

my pyproject.toml

```
[tool.poetry]
name = "project1"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.6"
python-dotenv = "^1.0.0"
transformers = "^4.29.2"
torch = { url = "https://download.pytorch.org/whl/cu118/torch-2.0.1%2Bcu118-cp310-cp310-linux_x86_64.whl" }
bitsandbytes = "^0.39.0"
sentencepiece = "^0.1.99"
accelerate = "^0.20.3"
scipy = "^1.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

and the example code from: https://github.com/TimDettmers/bitsandbytes/blob/main/examples/int8_inference_huggingface.py

```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

MAX_NEW_TOKENS = 128
model_name = "decapoda-research/llama-7b-hf"

text = "Hamburg is in which country?\n"
tokenizer = AutoTokenizer.from_pretrained(model_name)
input_ids = tokenizer(text, return_tensors="pt").input_ids

free_in_GB = int(torch.cuda.mem_get_info()[0] / 1024**3)
max_memory = f"{int(torch.cuda.mem_get_info()[0]/1024**3)-2}GB"

n_gpus = torch.cuda.device_count()
max_memory = {i: max_memory for i in range(n_gpus)}

model = AutoModelForCausalLM.from_pretrained(
    model_name, device_map="auto", load_in_8bit=True, max_memory=max_memory
)
generated_ids = model.generate(input_ids, max_length=MAX_NEW_TOKENS)
print(tokenizer.decode(generated_ids[0], skip_special_tokens=True))
```

What am I doing wrong?

**Comment by M-Chimiste** [comment]
Have you tried swapping out AutoTokenizer and AutoModel with: LlamaForCausalLM and LlamaTokenizer to see if it works?  I had a similar error before and solved it by explicitly calling out the imports. Another potential fix would be to try to install the latest version of Transformers through git. The error your getting calling out LLaMATokenizer doesn't make sense to me since that isn't a class in Transformers. I believe it should be just LlamaTokenizer.

**Comment by TimDettmers** [comment]
The tokenizer was renamed to CamelCase. I need to fix this.
