### ISSUE TITLE
failed to load 8bit model

### ISSUE THREAD

**Issue by moshemishan** [TimDettmers/bitsandbytes#524]
I run the following code on EC2 g4dn.2xlarge instance.

```
`from transformers import T5Tokenizer, T5ForConditionalGeneration

tokenizer = T5Tokenizer.from_pretrained("google/flan-t5-large")
model = T5ForConditionalGeneration.from_pretrained("google/flan-t5-large", device_map="auto", load_in_8bit=True)

input_text = "translate English to German: How old are you?"
input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to("cuda")

outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0]))`
```

and I got the following error:

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/ubuntu/environment/opt-bt/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/ubuntu/environment/opt-bt/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/environment/opt-bt/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2621, in from_pretrained
    from .utils.bitsandbytes import get_keys_to_not_convert, replace_8bit_linear
  File "/home/ubuntu/environment/opt-bt/lib/python3.8/site-packages/transformers/utils/bitsandbytes.py", line 9, in <module>
    import bitsandbytes as bnb
  File "/home/ubuntu/environment/opt-bt/lib/python3.8/site-packages/bitsandbytes/__init__.py", line 16, in <module>
    from .nn import modules
  File "/home/ubuntu/environment/opt-bt/lib/python3.8/site-packages/bitsandbytes/nn/__init__.py", line 6, in <module>
    from .triton_based_modules import SwitchBackLinear, SwitchBackLinearGlobal, SwitchBackLinearVectorwise, StandardLinear
  File "/home/ubuntu/environment/opt-bt/lib/python3.8/site-packages/bitsandbytes/nn/triton_based_modules.py", line 8, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "/home/ubuntu/environment/opt-bt/lib/python3.8/site-packages/bitsandbytes/triton/dequantize_rowwise.py", line 10, in <module>
    import triton
  File "/home/ubuntu/environment/opt-bt/lib/python3.8/site-packages/triton/__init__.py", line 1, in <module>
    raise RuntimeError("Should never be installed")
RuntimeError: Should never be installed

when I run the `python -m bitsandbytes` command I got the same error.

Python version 3.8.10

nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
transformers             4.29.2
bitsandbytes             0.39.0
pytorch-triton           0.0.1
triton                   2.0.0
pytorch-triton           0.0.1
torch                    2.0.1
torchaudio               2.0.2
torchvision              0.15.2
accelerate               0.19.0

can you help me solve this issue?

**Comment by moshemishan** [comment]
The problem was that I didn't remove the previous version of `triton` before installing `torch`. After removing it and reinstalling torch problem solved.
