### ISSUE TITLE
NameError: name 'CUDA_RUNTIME_LIB' is not defined. Did you mean: 'CUDA_RUNTIME_LIBS'?

### ISSUE THREAD

**Issue by CHENJINGTANG** [TimDettmers/bitsandbytes#557]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\minigpt4\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\miniconda3\envs\minigpt4\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\miniconda3\envs\minigpt4\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\CHENJINGTANG\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "C:\Users\CHENJINGTANG\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\autograd\__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "C:\Users\CHENJINGTANG\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\CHENJINGTANG\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\CHENJINGTANG\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "C:\Users\CHENJINGTANG\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cuda_setup\main.py", line 101, in run_cuda_setup
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "C:\Users\CHENJINGTANG\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cuda_setup\main.py", line 382, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "C:\Users\CHENJINGTANG\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cuda_setup\main.py", line 248, in determine_cuda_runtime_lib_path
    f'{CUDA_RUNTIME_LIB} as expected! Searching further paths...', is_warning=True)
NameError: name 'CUDA_RUNTIME_LIB' is not defined. Did you mean: 'CUDA_RUNTIME_LIBS'?

**Comment by CHENJINGTANG** [comment]
请问这个问题应该怎么处理，有知道的伙伴嘛？

**Comment by CHENJINGTANG** [comment]
CUDA 是 11.8 的，部署 Vicuna ，利用 GPU 启动是没有问题的，但是部署 MiniGPT-4 的时候，启动是报错的，处理过很多问题，反反复复都是这样。使用校验指令是 # python -m bitsandbytes!

**Comment by TimDettmers** [comment]
Windows is currently not supported. You can find more information here: #30

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
