### ISSUE TITLE
Returned non-zero exit status 1. (Already using WSL 2) can someone help please?

### ISSUE THREAD

**Issue by ZeroCool22** [TimDettmers/bitsandbytes#56]
```
(diffusers) zerocool@DESKTOP-IFR124:~/github/diffusers/examples/dreambooth$ ./my_training.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `12` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
WARNING:root:Blocksparse is not available: the current GPU does not expose Tensor cores

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cuda_setup/paths.py:86: UserWarning: /home/zerocool/anaconda3/envs/diffusers did not contain libcudart.so as expected! Searching further paths...
  warn(
/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cuda_setup/paths.py:98: UserWarning: /usr/lib/wsl/lib: did not contain libcudart.so as expected! Searching further paths...
  warn(
/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cuda_setup/paths.py:20: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('CompVis/stable-diffusion-v1-4')}
  warn(
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 6.1
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...
Caching latents: 100%|██████████████████████████████████████████████████████████████████| 27/27 [00:03<00:00,  7.42it/s]
Traceback (most recent call last):
  File "/home/zerocool/github/diffusers/examples/dreambooth/train_dreambooth.py", line 637, in <module>
    main()
  File "/home/zerocool/github/diffusers/examples/dreambooth/train_dreambooth.py", line 533, in main
    accelerator.init_trackers("dreambooth", config=vars(args))
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/accelerator.py", line 1061, in init_trackers
    tracker_init(project_name, self.logging_dir, **init_kwargs.get(str(tracker), {}))
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/tracking.py", line 133, in __init__
    self.writer = tensorboard.SummaryWriter(self.logging_dir, **kwargs)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 246, in __init__
    self._get_file_writer()
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 276, in _get_file_writer
    self.file_writer = FileWriter(
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/utils/tensorboard/writer.py", line 75, in __init__
    self.event_writer = EventFileWriter(
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/tensorboard/summary/writer/event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 900, in makedirs
    return get_filesystem(path).makedirs(path)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 201, in makedirs
    os.makedirs(path, exist_ok=True)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'my_model/logs'
Traceback (most recent call last):
  File "/home/zerocool/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zerocool/anaconda3/envs/diffusers/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=training', '--output_dir=my_model', '--instance_prompt=beaninstance', '--class_prompt=guy', '--resolution=512', '--train_batch_size=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--gradient_accumulation_steps=2', '--gradient_checkpointing', '--use_8bit_adam', '--max_train_steps=1000']' returned non-zero exit status 1.
```

**Comment by JFEspanolito** [comment]
Hey sup, i have the same error...
I checked the images I uploaded for him to use in the training, some were uploaded to the collab corruptly, I removed and re-uploaded them and the bug was removed.
I hope this helps you, as it helped me.

**Comment by ZeroCool22** [comment]
> Hey sup, i have the same error... I checked the images I uploaded for him to use in the training, some were uploaded to the collab corruptly, I removed and re-uploaded them and the bug was removed. I hope this helps you, as it helped me.

Thx, but i'm running it locally.

**Comment by ZeroCool22** [comment]
SOLUTION:

Need to use **CUDA 11.6** instead the 11.7, at least with an **1080 TI**.

![WSL + Ubuntu DB Working CUDA 11 6!](https://user-images.githubusercontent.com/13344308/194469445-9b3e9320-5c92-4dd1-9039-bc9b4bf7d2b3.jpg)

![Screenshot_9](https://user-images.githubusercontent.com/13344308/194469454-7259039e-ac24-4d49-8d82-4c945f6d55e6.jpg)
