### ISSUE TITLE
bitsandbytes runs error

### ISSUE THREAD

**Issue by alexwangyu** [TimDettmers/bitsandbytes#569]
bin C:\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\Python\Python310\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
CUDA SETUP: Loading binary C:\Python\Python310\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 109, in <module>
    generate_bug_report_information()
  File "C:\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 52, in generate_bug_report_information
    paths = find_file_recursive(os.environ['CONDA_PREFIX'], f'*cuda*{SHARED_LIB_EXTENSION}')
  File "C:\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 38, in find_file_recursive
    out, err = execute_and_return(cmd)
  File "C:\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 33, in execute_and_return
    std_out, std_err = execute_and_return_decoded_std_streams(command_string)
  File "C:\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 25, in execute_and_return_decoded_std_streams
    return _decode(
  File "C:\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 19, in _decode
    return tuple(
  File "C:\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 20, in <genexpr>
    to_decode.decode("UTF-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: invalid continuation byte

**Comment by freQuensy23-coder** [comment]
Same problem with newest version

**Comment by TimDettmers** [comment]
Windows is currently not supported. You can find more information here: #30

**Comment by henrywang0314** [comment]
try this:
pip install --trusted-host github.com --trusted-host objects.githubusercontent.com https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.0-py3-none-win_amd64.whl

**Comment by aymenabid-lab** [comment]
I want install
 bitsandbytes==0.41.3 accelerate==0.25.0
 have you trusted command
