### ISSUE TITLE
Cannot load libbitsandbytes_cuda114_nocublaslt.so despite the file being there

### ISSUE THREAD

**Issue by chen386** [TimDettmers/bitsandbytes#582]
Output of `python3 -m bitsandbytes`

```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
False
/home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/opt/miniconda3/envs/opence-v1.7.2/lib/libcudart.so'), PosixPath('/opt/miniconda3/envs/opence-v1.7.2/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /opt/miniconda3/envs/opence-v1.7.2/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.0
CUDA SETUP: Detected CUDA version 114
/home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so...
/home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=114 make cuda11x_nomatmul
python setup.py install
Traceback (most recent call last):
  File "/opt/miniconda3/envs/opence-v1.7.2/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/miniconda3/envs/opence-v1.7.2/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/miniconda3/envs/opence-v1.7.2/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

Output of `ls -l /home/chen386/.local/lib/python3.9/site-packages/bitsandbytes/`
```
total 321264
drwxr-xr-x 3 chen386 grp_202     4096 Jul 12 23:30 autograd
-rw-r--r-- 1 chen386 grp_202     1633 Jul 12 23:30 cextension.py
drwxr-xr-x 3 chen386 grp_202     4096 Jul 12 23:30 cuda_setup
-rw-r--r-- 1 chen386 grp_202    78628 Jul 12 23:30 functional.py
-rw-r--r-- 1 chen386 grp_202      670 Jul 12 23:30 __init__.py
-rwxr-xr-x 1 chen386 grp_202    41608 Jul 12 23:30 libbitsandbytes_cpu.so
-rwxr-xr-x 1 chen386 grp_202 11106616 Jul 12 23:30 libbitsandbytes_cuda110_nocublaslt.so
-rwxr-xr-x 1 chen386 grp_202  5934728 Jul 12 23:30 libbitsandbytes_cuda110.so
-rwxr-xr-x 1 chen386 grp_202 20228408 Jul 12 23:30 libbitsandbytes_cuda111_nocublaslt.so
-rwxr-xr-x 1 chen386 grp_202  8961672 Jul 12 23:30 libbitsandbytes_cuda111.so
-rwxr-xr-x 1 chen386 grp_202 20797656 Jul 12 23:30 libbitsandbytes_cuda113_nocublaslt.so
-rwxr-xr-x 1 chen386 grp_202  9215536 Jul 12 23:30 libbitsandbytes_cuda113.so
-rwxr-xr-x 1 chen386 grp_202 20965592 Jul 12 23:30 libbitsandbytes_cuda114_nocublaslt.so
-rwxr-xr-x 1 chen386 grp_202  9309744 Jul 12 23:30 libbitsandbytes_cuda114.so
-rwxr-xr-x 1 chen386 grp_202 20920872 Jul 12 23:30 libbitsandbytes_cuda115_nocublaslt.so
-rwxr-xr-x 1 chen386 grp_202  9310080 Jul 12 23:30 libbitsandbytes_cuda115.so
-rwxr-xr-x 1 chen386 grp_202 20732768 Jul 12 23:30 libbitsandbytes_cuda117_nocublaslt.so
-rwxr-xr-x 1 chen386 grp_202  9117872 Jul 12 23:30 libbitsandbytes_cuda117.so
-rwxr-xr-x 1 chen386 grp_202 26504336 Jul 12 23:30 libbitsandbytes_cuda118_nocublaslt.so
-rwxr-xr-x 1 chen386 grp_202 14914016 Jul 12 23:30 libbitsandbytes_cuda118.so
-rwxr-xr-x 1 chen386 grp_202 25693136 Jul 12 23:30 libbitsandbytes_cuda120_nocublaslt.so
-rwxr-xr-x 1 chen386 grp_202 14491928 Jul 12 23:30 libbitsandbytes_cuda120.so
-rwxr-xr-x 1 chen386 grp_202 25705424 Jul 12 23:30 libbitsandbytes_cuda121_nocublaslt.so
-rwxr-xr-x 1 chen386 grp_202 14500120 Jul 12 23:30 libbitsandbytes_cuda121.so
-rwxr-xr-x 1 chen386 grp_202 25786816 Jul 12 23:30 libbitsandbytes_cuda122_nocublaslt.so
-rwxr-xr-x 1 chen386 grp_202 14548672 Jul 12 23:30 libbitsandbytes_cuda122.so
-rw-r--r-- 1 chen386 grp_202     3992 Jul 12 23:30 __main__.py
drwxr-xr-x 3 chen386 grp_202     4096 Jul 12 23:30 nn
drwxr-xr-x 3 chen386 grp_202     4096 Jul 12 23:30 optim
drwxr-xr-x 2 chen386 grp_202     4096 Jul 12 23:30 __pycache__
drwxr-xr-x 5 chen386 grp_202     4096 Jul 12 23:30 research
drwxr-xr-x 3 chen386 grp_202     4096 Jul 12 23:30 triton
-rw-r--r-- 1 chen386 grp_202     7499 Jul 12 23:30 utils.py
```

**Comment by TimDettmers** [comment]
The binary does not seem to be there and you need to compile from source. Did you install via pip?

**Comment by chen386** [comment]
> The binary does not seem to be there and you need to compile from source. Did you install via pip?
Yeah.

**Comment by TimDettmers** [comment]
Upgrading via `pip install -U bitsandbytes` should resolve this issue. I will close this issue. Please reopen if upgrading does not resolve the error.

**Comment by sakshamsingh1** [comment]
This helped me to resolve it `conda install -c nvidia cuda-toolkit`
