### ISSUE TITLE
ImportError: cannot import name 'translate_llvmir_to_hsaco' from 'triton._C.libtriton.triton'

### ISSUE THREAD

**Issue by seifane** [TimDettmers/bitsandbytes#591]
On a fresh Venv installing bitsandbytes with pip I get a weird error related to triton. I've confirmed triton is installed. I have tried uninstalling and reinstalling triton, it did not fix the issue.

Let me know if you would like me to run some other commands !

Report :

```
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/lib/jvm/java-17-openjdk/lib/*'), PosixPath('/usr/lib/jvm/java-17-openjfx/lib/*')}
  warn(msg)
/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session0')}
  warn(msg)
/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//debuginfod.archlinux.org '), PosixPath('https')}
  warn(msg)
/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Seat0')}
  warn(msg)
/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('rofi/|usr|bin|pycharm/434339-0-archlinux_TIME46931076')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: /opt/cuda/targets/x86_64-linux/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 5.2
CUDA SETUP: Detected CUDA version 121
/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!
  warn(msg)
CUDA SETUP: Loading binary /home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so...
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/__init__.py", line 16, in <module>
    from .nn import modules
  File "/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/nn/__init__.py", line 6, in <module>
    from .triton_based_modules import SwitchBackLinear, SwitchBackLinearGlobal, SwitchBackLinearVectorwise, StandardLinear
  File "/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/nn/triton_based_modules.py", line 8, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/bitsandbytes/triton/dequantize_rowwise.py", line 10, in <module>
    import triton
  File "/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/triton/__init__.py", line 20, in <module>
    from .runtime import (
  File "/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/triton/runtime/__init__.py", line 1, in <module>
    from .autotuner import Config, Heuristics, autotune, heuristics
  File "/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/triton/runtime/autotuner.py", line 7, in <module>
    from ..compiler import OutOfResources
  File "/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/triton/compiler/__init__.py", line 1, in <module>
    from .compiler import CompiledKernel, compile, instance_descriptor
  File "/home/tiemajor/projects/perso/python/ml/langchain/venv/lib/python3.11/site-packages/triton/compiler/compiler.py", line 14, in <module>
    from .._C.libtriton.triton import (add_external_libs, compile_ptx_to_cubin,
ImportError: cannot import name 'translate_llvmir_to_hsaco' from 'triton._C.libtriton.triton' (unknown location)
```

**Comment by TimDettmers** [comment]
What triton version are you using? It seems to be a triton-related error rather than bitsandbytes since it fails at triton import. I cannot find the `translate_llmvmir...` function in the triton repo.

**Comment by meinlebenswerk** [comment]
So I had the same issue with flash-attn and pytorch version `2.1.0`, this was fixed by upgrading to `2.1.0.dev20230713+cu118`, however flash-attn triton kernels would still hang, which required me to manually downgrade triton, as suggested [here](https://huggingface.co/mosaicml/mpt-7b-storywriter/discussions/10).
Hope this helps :)

**Comment by seifane** [comment]
@TimDettmers For reference I tried with triton 2.0.0.post1 as well as 2.0.0. I could not find a reference to the function in the triton repo as well so I assumed bitsandbytes might be doing something with triton. Closing.

**Comment by kushalj001** [comment]
Hi @seifane 
I am currently facing the same error. What did you do to sort this out?
Thanks

**Comment by seifane** [comment]
@kushalj001 I could not manage to fix it so I switched to using llama.cpp

**Comment by Lashi0812** [comment]
Hi @seifane 
I faced the similar issue. [Solution](https://github.com/openai/triton/issues/2002)

**Comment by saramirabi** [comment]
I faced with the same error. Can anyone tell me what is the reason? "ImportError: cannot import name 'Config' from 'triton' (unknown location)"
