### ISSUE TITLE
NameError: name 'cuda_setup' is not defined

### ISSUE THREAD

**Issue by haotianliangye** [TimDettmers/bitsandbytes#594]
/root/miniconda3/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
Initializing Chat
Loading VIT
Loading VIT Done
Loading Q-Former
Loading Q-Former Done
Loading LLAMA

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Traceback (most recent call last):
  File "/root/MiniGPT-4/demo.py", line 60, in <module>
    model = model_cls.from_config(model_config).to('cuda:{}'.format(args.gpu_id))
  File "/root/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 243, in from_config
    model = cls(
  File "/root/MiniGPT-4/minigpt4/models/mini_gpt4.py", line 90, in __init__
    self.llama_model = LlamaForCausalLM.from_pretrained(
  File "/root/miniconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2639, in from_pretrained
    from .utils.bitsandbytes import get_keys_to_not_convert, replace_8bit_linear
  File "/root/miniconda3/lib/python3.9/site-packages/transformers/utils/bitsandbytes.py", line 9, in <module>
    import bitsandbytes as bnb
  File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/autograd/__init__.py", line 1, in <module>
    from ._functions import undo_layout, get_inverse_transform_indices
  File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py", line 92, in run_cuda_setup
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py", line 395, in evaluate_cuda_setup
    has_cublaslt = is_cublasLt_compatible(cc)
  File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py", line 153, in is_cublasLt_compatible
    cuda_setup.add_log_entry("WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!", is_warning=True)
NameError: name 'cuda_setup' is not defined

**Comment by TimDettmers** [comment]
What bitsandbytes version are you using?

**Comment by haotianliangye** [comment]
Version: 0.37.0
