### ISSUE TITLE
python -m bitsandbytes got this error message

### ISSUE THREAD

**Issue by sifei** [TimDettmers/bitsandbytes#623]
bitsandbytes=0.40.2
CUDA Version=12.0

Traceback (most recent call last):
  File "/home/hans2/miniconda3/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/hans2/miniconda3/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/hans2/miniconda3/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/hans2/miniconda3/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/hans2/miniconda3/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/hans2/miniconda3/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/hans2/miniconda3/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/hans2/miniconda3/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/hans2/miniconda3/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/hans2/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 120, in run_cuda_setup
    binary_name, cudart_path, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/hans2/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 337, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/hans2/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 295, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/home/hans2/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 231, in find_cuda_lib_in
    return get_cuda_runtime_lib_paths(
  File "/home/hans2/miniconda3/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 217, in get_cuda_runtime_lib_paths
    if (path / libname).is_file():
  File "/home/hans2/miniconda3/lib/python3.10/pathlib.py", line 1322, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/home/hans2/miniconda3/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/usr/share/lmod/lmod/init/ksh_funcs/libcudart.so'

**Comment by prasad4fun** [comment]
Facing same Issue, for earlier version setting LD_LIBRARY_PATH env varaible worked, with 0.41.0 even after setting LD_LIBRARY_PATH getting [Errno 13] Permission denied error.

**Comment by neural-oracle** [comment]
Dont know if you have windows system ... 
on Windows i had to search 24hours for solution regarding conflict between CUDA and bitsandbytes.
For me the following windows version of bitsandbytes helped:

pip install bitsandbytes-windows

search on github ... there is a repository for bitsandbytes-windows

**Comment by neural-oracle** [comment]
see also comments at bottom here
https://github.com/facebookresearch/bitsandbytes/issues/7
