### ISSUE TITLE
FileNotFoundError: Could not find module

### ISSUE THREAD

**Issue by glowstone314** [TimDettmers/bitsandbytes#626]
CUDA SETUP: Loading binary D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll...
Traceback (most recent call last):
  File "D:\stable diffusion\lora-scripts-gui\python\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\stable diffusion\lora-scripts-gui\python\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\DW\AppData\Roaming\Python\Python310\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\DW\AppData\Roaming\Python\Python310\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\DW\AppData\Roaming\Python\Python310\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\DW\AppData\Roaming\Python\Python310\site-packages\accelerate\utils\__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "C:\Users\DW\AppData\Roaming\Python\Python310\site-packages\accelerate\utils\bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\cextension.py", line 43, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\cextension.py", line 39, in get_instance
    cls._instance.initialize()
  File "D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\cextension.py", line 33, in initialize
    self.lib = ct.cdll.LoadLibrary(str(binary_path))            # $$$
  File "D:\stable diffusion\lora-scripts-gui\python\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "D:\stable diffusion\lora-scripts-gui\python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'D:\stable diffusion\lora-scripts-gui\python\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by Ragav86** [comment]
I am seeing same issue in Windows Server 2019 when trying to run from D: drive

===================================BUG REPORT=================================== 
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: D:\PycharmProjects\localGPT\venv\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary D:\PycharmProjects\localGPT\venv\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'D:\PycharmProjects\localGPT\venv\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor 
syntax.
CUDA SETUP: Loading binary D:\PycharmProjects\localGPT\venv\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'D:\PycharmProjects\localGPT\venv\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor 
syntax.
CUDA SETUP: Loading binary D:\PycharmProjects\localGPT\venv\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'D:\PycharmProjects\localGPT\venv\Lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor 
syntax.
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "D:\PycharmProjects\localGPT\run_localGPT.py", line 5, in <module>
    from auto_gptq import AutoGPTQForCausalLM
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\auto_gptq\__init__.py", line 3, in <module>
    from .utils.peft_utils import get_gptq_peft_model
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\auto_gptq\utils\peft_utils.py", line 9, in <module>
    from peft import get_peft_model, PeftConfig, PeftModel, PeftType
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\peft\auto.py", line 30, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\peft\mapping.py", line 20, in <module>
    from .peft_model import (
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\peft\peft_model.py", line 39, in <module>
    from .tuners import (
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel 
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\peft\tuners\lora.py", line 42, in <module>
    import bitsandbytes as bnb
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\bitsandbytes\__init__.py", line 7, in <module>
    from .autograd._functions import (
    from ._functions import undo_layout, get_inverse_transform_indices
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\bitsandbytes\autograd\_functions.py", line 9, in <module>
    import bitsandbytes.functional as F
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\bitsandbytes\functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "D:\PycharmProjects\localGPT\venv\Lib\site-packages\bitsandbytes\cextension.py", line 22, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
