### ISSUE TITLE
Maybe you do not have a linux system?

### ISSUE THREAD

**Issue by logan0601** [TimDettmers/bitsandbytes#634]
I install bitsandbytes, but when i use command python -m bitsandbytes, i get the following bug. I have no idea why.

False
/home/storage/logan/bitsandbytes/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/storage/logan/anaconda3/envs/three-studio/lib/libcudart.so
/home/storage/logan/anaconda3/envs/three-studio/lib/python3.9/site-packages/bitsandbytes-0.41.0-py3.9.egg/bitsandbytes/libbitsandbytes_cuda113.so
/home/storage/logan/anaconda3/envs/three-studio/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda112.so

Traceback (most recent call last):
  File "/home/storage/logan/anaconda3/envs/three-studio/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/storage/logan/anaconda3/envs/three-studio/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/storage/logan/bitsandbytes/bitsandbytes/__main__.py", line 96, in <module>
    generate_bug_report_information()
  File "/home/storage/logan/bitsandbytes/bitsandbytes/__main__.py", line 54, in generate_bug_report_information
    paths = find_file_recursive('/usr/local', '*cuda*so')
  File "/home/storage/logan/bitsandbytes/bitsandbytes/__main__.py", line 37, in find_file_recursive
    raise RuntimeError('Something when wrong when trying to find file. Maybe you do not have a linux system?')
RuntimeError: Something when wrong when trying to find file. Maybe you do not have a linux system?

**Comment by Waterglaze** [comment]
same question

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
