### ISSUE TITLE
[solved] windows + bitsandbytes-0.39.1-py3-none-win_amd64.whl meet the problem

### ISSUE THREAD

**Issue by nagaki09** [TimDettmers/bitsandbytes#639]
bin C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll
False
C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\bitsandbytes\cuda_setup\main.py:156: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C:/ProgramData/anaconda3/envs/Tuning/bin')}
  warn(msg)
C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\bitsandbytes\cuda_setup\main.py:156: UserWarning: C:\ProgramData\anaconda3\envs\Tuning did not contain ['cudart64_110.dll', 'cudart64_120.dll', 'cudart64_12.dll'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\cudart64_12.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll...
**Could not find module 'C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.dll' (or one of its dependencies). Try using the full path with constructor syntax.** 
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121
python setup.py install
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\llmtuner\__init__.py", line 1, in <module>
    from llmtuner.chat import ChatModel
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\llmtuner\chat\__init__.py", line 1, in <module>
    from llmtuner.chat.stream_chat import ChatModel
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\llmtuner\chat\stream_chat.py", line 6, in <module>
    from llmtuner.extras.misc import get_logits_processor
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\llmtuner\extras\misc.py", line 4, in <module>
    from transformers.modeling_utils import PreTrainedModel
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\transformers\modeling_utils.py", line 86, in <module>
    from accelerate import dispatch_model, infer_auto_device_map, init_empty_weights
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\accelerate\utils\bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\ProgramData\anaconda3\envs\Tuning\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by nagaki09** [comment]
problem solved with latest version
