### ISSUE TITLE
ERROR of  CUDA

### ISSUE THREAD

**Issue by Roy202307** [TimDettmers/bitsandbytes#664]
bin D:\python\Mega-AI\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda110.dll
CUDA SETUP: CUDA runtime path found: D:\NAVDIA_GPU\Toolkit\CUDA\v11.0\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 110
CUDA SETUP: Required library version not found: libbitsandbytes_cuda110.dll. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.dll...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=110 make cuda110
python setup.py install
CUDA SETUP: Setup Failed!
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=110 make cuda110
python setup.py install
Traceback (most recent call last):
  File "D:\python\Mega-AI\text-generation-webui\server.py", line 51, in <module>
    from modules import chat, shared, training, ui, utils
  File "D:\python\Mega-AI\text-generation-webui\modules\training.py", line 14, in <module>
    from peft import (
  File "D:\python\Mega-AI\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "D:\python\Mega-AI\installer_files\env\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "D:\python\Mega-AI\installer_files\env\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import (
  File "D:\python\Mega-AI\installer_files\env\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "D:\python\Mega-AI\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 40, in <module>
    import bitsandbytes as bnb
  File "D:\python\Mega-AI\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "D:\python\Mega-AI\installer_files\env\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "D:\python\Mega-AI\installer_files\env\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "D:\python\Mega-AI\installer_files\env\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "D:\python\Mega-AI\installer_files\env\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "D:\python\Mega-AI\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

![image](https://github.com/TimDettmers/bitsandbytes/assets/140703343/a6db555a-8a6f-44ed-8c85-e4d0fc26db05)

**Comment by Roy202307** [comment]
![image](https://github.com/TimDettmers/bitsandbytes/assets/140703343/a4bfe549-a3d3-4ee4-b425-273a608e002e)

now,new error!
![image](https://github.com/TimDettmers/bitsandbytes/assets/140703343/82ee40ea-284f-46be-85a4-8892cc9e24db)

**Comment by Roy202307** [comment]
My CUDA version is 12.0
so  i need reinstall bitsandbytes-windows at least 0.38.1+
![image](https://github.com/TimDettmers/bitsandbytes/assets/140703343/95d383f6-185b-43c2-bf83-c759775b7016)

**Comment by Roy202307** [comment]
I have installed bitsandbytes-windows v0.38.1
Unfortunately, the problem still persists, so weird!
