### ISSUE TITLE
run text-generation-webui  BUG REPORT（my english no good）

### ISSUE THREAD

**Issue by mknjibhuvgyo2** [TimDettmers/bitsandbytes#671]
i have 2 GPUs
i look this: https://huggingface.co/SebastianBodza/mpt-30B-qlora-multi_GPU
and run [python server.py --model llama-2-7b-chat --trust-remote-code --load-in-8bit]

(llama) K:\text-generation-webui>python server.py --model llama-2-7b-chat --trust-remote-code --load-in-8bit
2023-08-03 12:04:25 WARNING:trust_remote_code is enabled. This is dangerous.
False
C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/Users/kuan/anaconda3/envs/llama/lib'), WindowsPath('C')}
  warn(msg)
C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: C:\Users\kuan\anaconda3\envs\llama did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "K:\text-generation-webui\server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "K:\text-generation-webui\modules\chat.py", line 17, in <module>
    from modules.text_generation import (
  File "K:\text-generation-webui\modules\text_generation.py", line 22, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "K:\text-generation-webui\modules\models.py", line 10, in <module>
    from accelerate import infer_auto_device_map, init_empty_weights
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\accelerate\utils\__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\accelerate\utils\bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

(llama) K:\text-generation-webui>python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
False
C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C'), WindowsPath('/Users/kuan/anaconda3/envs/llama/lib')}
  warn(msg)
C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: C:\Users\kuan\anaconda3\envs\llama did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
  warn(msg)
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
  warn(msg)
C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cuda_setup\main.py:147: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Loading binary C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\kuan\anaconda3\envs\llama\Lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by mknjibhuvgyo2** [comment]
(llama) K:\text-generation-webui>setx LD_LIBRARY_PATH "FOUND_PATH_FROM_STEP_2;%LD_LIBRARY_PATH%"

SUCCESS: Specified value was saved.



but it is can't run again
