### ISSUE TITLE
老是报错

### ISSUE THREAD

**Issue by TwoExtremes** [TimDettmers/bitsandbytes#685]
Traceback (most recent call last):
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 页面文件太小，无法完成操作。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\lora-scripts-v1.4.2\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\lora-scripts-v1.4.2\python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\lora-scripts-v1.4.2\python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\lora-scripts-v1.4.2\python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "D:\lora-scripts-v1.4.2\python\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\lora-scripts-v1.4.2\python\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\lora-scripts-v1.4.2\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\lora-scripts-v1.4.2\sd-scripts\train_network.py", line 14, in <module>
    from accelerate.utils import set_seed
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\accelerate\accelerator.py", line 27, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\accelerate\utils\__init__.py", line 103, in <module>
    from .megatron_lm import (
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\accelerate\utils\megatron_lm.py", line 32, in <module>
    from transformers.modeling_outputs import (
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\transformers\utils\generic.py", line 33, in <module>
    import tensorflow as tf
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\tensorflow\python\__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "D:\lora-scripts-v1.4.2\python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: 页面文件太小，无法完成操作。

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.

**Comment by shenjackyuanjie** [comment]
你这是内存不够啊
