### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'cuDeviceGetCount'

### ISSUE THREAD

**Issue by Moon502** [TimDettmers/bitsandbytes#688]
++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
Traceback (most recent call last):
  File "/root/anaconda3/envs/Chinese-LLaMA-Alpaca-2/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/Chinese-LLaMA-Alpaca-2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/Chinese-LLaMA-Alpaca-2/lib/python3.10/site-packages/bitsandbytes/__main__.py", line 106, in <module>
    print(f"COMPUTE_CAPABILITIES_PER_GPU = {get_compute_capabilities(cuda)}")
  File "/root/anaconda3/envs/Chinese-LLaMA-Alpaca-2/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 349, in get_compute_capabilities
    check_cuda_result(cuda, cuda.cuDeviceGetCount(ct.byref(nGpus)))
AttributeError: 'NoneType' object has no attribute 'cuDeviceGetCount'

**Comment by Moon502** [comment]
pip uninstall bitsandbytes
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=117 make cuda11x
python setup.py install
