### ISSUE TITLE
libcudart.so not found and missing libcusparse.so

### ISSUE THREAD

**Issue by tilmanbeck** [TimDettmers/bitsandbytes#705]
Hi,

I am facing the issue that bitsandbytes is raising an UserWarning that my LD_LIBRARY_PATH does not contain any libcudart file even though I confirmed it is there. Further, it is failing to open a libcusparse.so.11 file which I don't know how to install using a torch-bundled CUDA setup. The output of `python -m bitsandbytes` is the following: 
```
(venv) [beck@scratchy context-stance]$ python -m bitsandbytes
False

===================================BUG REPORT===================================
<project-path>/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
<project-path>/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: <project-path>/venv/lib64/python3.10/site-packages/nvidia/cuda_runtime/lib did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('<user-path>/.apptainer/cache')}
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/scl/modulefiles')}
The following directories listed in your path were found to be non-existent: {PosixPath('https'), PosixPath('//debuginfod.centos.org/ ')}
The following directories listed in your path were found to be non-existent: {PosixPath('/scratch/88206/.apptainer')}
The following directories listed in your path were found to be non-existent: {PosixPath('() {  ( alias;\n eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@\n}')}
The following directories listed in your path were found to be non-existent: {PosixPath('() {  if [ "$1" = "load" -o "$1" = "unload" ]; then\n eval "module $@";\n else\n /usr/bin/scl "$@";\n fi\n}')}
The following directories listed in your path were found to be non-existent: {PosixPath('() {  eval "$($LMOD_DIR/ml_cmd "$@")"\n}')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 9.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary <project-path>/venv/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "<python-path>/minicoda3.10/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "<python-path>/minicoda3.10/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "<python-path>/minicoda3.10/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "<project-path>/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "<project-path>/venv/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "<project-path>/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "<project-path>/venv/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "<project-path>/venv/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "<project-path>/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```
Before running above command, I set LD_LIBRARY_PATH to my pip environment:
`export LD_LIBRARY_PATH="<project-path>/venv/lib64/python3.10/site-packages/nvidia/cuda_runtime/lib"` where the following files are to be found:

```
ls <project-path>/venv/lib64/python3.10/site-packages/nvidia/cuda_runtime/lib
libcudart.so.11.0  libOpenCL.so.1
```

I am on slurm node with a H100pcie GPU (80GB). I installed torch and bitsandbytes via the following 
`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`
`pip install -U bitsandbytes`

pip freeze is showing me the following
```
torch==2.0.1+cu118
torchaudio==2.0.2+cu118
torchvision==0.15.2+cu118
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.9.4.25
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
bitsandbytes==0.41.1
```

I tried loading the GPU with torch which works fine:
```
>>> import torch
>>> print(torch.__version__)
2.0.1+cu118
>>> print(torch.cuda.get_device_properties(0))
_CudaDeviceProperties(name='NVIDIA H100 PCIe', major=9, minor=0, total_memory=81089MB, multi_processor_count=114)
```

**Comment by pk1762012** [comment]
Same issue in windows

**Comment by pk1762012** [comment]
did you find a solution

**Comment by wasimbijilithehuman** [comment]
same issue, do tell me if you find the solution

**Comment by dcruiz01** [comment]
same issue here!

**Comment by tilmanbeck** [comment]
It seems the torch-bundled CUDA does not bundle all files which `python - m bitsandbytes` is looking for during compilation. I found out that our slurm cluster comes with native installation of CUDA which I loaded via `module load CUDA` before running my original python script.

**Comment by pk1762012** [comment]
> It seems the torch-bundled CUDA does not bundle all files which `python - m bitsandbytes` is looking for during compilation. I found out that our slurm cluster comes with native installation of CUDA which I loaded via `module load CUDA` before running my original python script.

What is a Slurm cluster. 
'module load CUDA' is not working for me 
module load CUDA
Get-Module : A positional parameter cannot be found that accepts argument 'CUDA'.
At line:1 char:1
+ module load CUDA

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
