### ISSUE TITLE
import not possible when running in docker container

### ISSUE THREAD

**Issue by samiede** [TimDettmers/bitsandbytes#73]
Hey! I'm trying to set up a docker container and use 8 bit Adam. When I'm trying to import bitsandbytes, I'm getting

```
2022-10-26T11:20:58.819996206Z     import bitsandbytes as bnb
2022-10-26T11:20:58.820003169Z   File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 6, in <module>
2022-10-26T11:20:58.820019600Z     from .autograd._functions import (
2022-10-26T11:20:58.820023698Z   File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
2022-10-26T11:20:58.820060948Z     import bitsandbytes.functional as F
2022-10-26T11:20:58.820067420Z   File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/functional.py", line 13, in <module>
2022-10-26T11:20:58.820089783Z     from .cextension import COMPILED_WITH_CUDA, lib
2022-10-26T11:20:58.820094021Z   File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 113, in <module>
2022-10-26T11:20:58.820140619Z     lib = CUDASetup.get_instance().lib
2022-10-26T11:20:58.820148213Z   File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 109, in get_instance
2022-10-26T11:20:58.820191876Z     cls._instance.initialize()
2022-10-26T11:20:58.820198208Z   File "/root/miniconda3/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 59, in initialize
2022-10-26T11:20:58.820229417Z     binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
2022-10-26T11:20:58.820236040Z ValueError: too many values to unpack (expected 5)
```

This happens only when I'm starting my script directly in the Dockerfile, if I instead just start the container without any CMD or ENTRYPOINT, ssh into the container and then manually start the script, it does work, but for some reason, Docker doesn't seem to be having access to CUDA properly when starting from the Dockerfile?

I've traced the error down to https://github.com/TimDettmers/bitsandbytes/blob/a371be302ddbdf3f36acef1a6fe365672099c9d9/bitsandbytes/cuda_setup/main.py#L137 since the function returns here with only one value instead of the expected 5, but I haven't had any other issues with CUDA before that, e.g. transferring models to the GPU by using `.to('cuda')`

I'm at a loss since I'm not too experienced with Docker and it does work when I'm starting the script manually via ssh.

Thanks in advance!

**Comment by 0xspeedrunner** [comment]
Hey @TimDettmers , unfortunately this is still broken for me, despite pip installing from the repo directly.

I'm running this in Docker / JupyterLabs on NVIDIA GeForce RTX 3090, 24576 MiB, 24267 

Any advice on anything I might be doing wrong?

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import bitsandbytes as bnb

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/__init__.py:6, in <module>
      1 # Copyright (c) Facebook, Inc. and its affiliates.
      2 #
      3 # This source code is licensed under the MIT license found in the
      4 # LICENSE file in the root directory of this source tree.
----> 6 from .autograd._functions import (
      7     MatmulLtState,
      8     bmm_cublas,
      9     matmul,
     10     matmul_cublas,
     11     mm_cublas,
     12 )
     13 from .cextension import COMPILED_WITH_CUDA
     14 from .nn import modules

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py:5, in <module>
      2 import warnings
      4 import torch
----> 5 import bitsandbytes.functional as F
      7 from dataclasses import dataclass
      8 from functools import reduce  # Required in Python 3

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/functional.py:13, in <module>
     10 from typing import Tuple
     11 from torch import Tensor
---> 13 from .cextension import COMPILED_WITH_CUDA, lib
     14 from functools import reduce  # Required in Python 3
     16 # math.prod not compatible with python < 3.8

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:113, in <module>
    109             cls._instance.initialize()
    110         return cls._instance
--> 113 lib = CUDASetup.get_instance().lib
    114 try:
    115     if lib is None and torch.cuda.is_available():

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:109, in CUDASetup.get_instance(cls)
    107 if cls._instance is None:
    108     cls._instance = cls.__new__(cls)
--> 109     cls._instance.initialize()
    110 return cls._instance

File /opt/conda/lib/python3.9/site-packages/bitsandbytes/cextension.py:59, in CUDASetup.initialize(self)
     56 self.lib = None
     58 from .cuda_setup.main import evaluate_cuda_setup
---> 59 binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
     60 self.cudart_path = cudart_path
     61 self.cuda = cuda

ValueError: too many values to unpack (expected 5)
```

**Comment by Hades32** [comment]
Same here, I do 
```Dockerfile
RUN pip3 install -qq git+https://github.com/TimDettmers/bitsandbytes
```
but later I get
```
UserWarning: The installed version of bitsandbytes was compiled without GPU support
...
NameError: name 'str2optimizer8bit_blockwise' is not defined
```

**Comment by Hades32** [comment]
I'm guessing that the issue might be that CUDA is installed, but during build-time no GPU is attached. Is it possible to force this somehow?

**Comment by samiede** [comment]
> Same here, I do
> 
> ```dockerfile
> RUN pip3 install -qq git+https://github.com/TimDettmers/bitsandbytes
> ```
> 
> but later I get
> 
> ```
> UserWarning: The installed version of bitsandbytes was compiled without GPU support
> ...
> NameError: name 'str2optimizer8bit_blockwise' is not defined
> ```

I have the same issue with the UserWarning now. I managed to resolve the first issue by using a different base image for my docker container, namely the `devel` instead of the `runtime` version. I'm gonna try that what this error now.

**Comment by jeanmichaeldiei** [comment]
Any updates? I am facing this exact issue on WSL2 with a 3090 and cuda 11.6 installed on the docker.

**Comment by samiede** [comment]
using the `devel` did work for me. Also manually installing cudatoolkit with conda!
