### ISSUE TITLE
==========BUG REPORT==========

### ISSUE THREAD

**Issue by Wichu990** [TimDettmers/bitsandbytes#735]
bin B:\python\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
CUDA SETUP: CUDA runtime path found: B:\python\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary B:\python\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll...
Colab Check: False, TPU: False
INIT       | OK         | KAI Horde Models
INFO       | __main__:<module>:718 - We loaded the following model backends:
KoboldAI API
KoboldAI Old Colab Method
Basic Huggingface
Huggingface
GooseAI
Legacy GPTQ
Horde
OpenAI
Read Only
INIT       | Starting   | Flask
INIT       | OK         | Flask
INIT       | Starting   | Webserver
INIT       | OK         | Webserver
MESSAGE    | Webserver started! You may now connect with a browser at http://127.0.0.1:5000
ERROR      | __main__:<module>:10982 - An error has been caught in function '<module>', process 'MainProcess' (12128), thread 'MainThread' (15748):
Traceback (most recent call last):

> File "aiserver.py", line 10982, in <module>
    run()
    └ <function run at 0x000001DD49740280>

  File "aiserver.py", line 10978, in run
    socketio.run(app, port=port)
    │        │   │         └ 5000
    │        │   └ <Flask 'KoboldAI-united'>
    │        └ <function SocketIO.run at 0x000001DD47AE7D30>
    └ <flask_socketio.SocketIO object at 0x000001DD47F2FA60>

  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 685, in run
    run_server()
    └ <function SocketIO.run.<locals>.run_server at 0x000001DD4976CCA0>

  File "B:\python\lib\site-packages\flask_socketio\__init__.py", line 662, in run_server
    eventlet_socket = eventlet.listen(addresses[0][4],
                      │        │      └ [(<AddressFamily.AF_INET: 2>, 0, 0, '', ('127.0.0.1', 5000))]
                      │        └ <function listen at 0x000001DD058C5F70>
                      └ <module 'eventlet' from 'B:\\python\\lib\\site-packages\\eventlet\\__init__.py'>

  File "B:\python\lib\site-packages\eventlet\convenience.py", line 78, in listen
    sock.bind(addr)
    │    │    └ ('127.0.0.1', 5000)
    │    └ <built-in method bind of socket object at 0x000001DD497BD3A0>
    └ <eventlet.greenio.base.GreenSocket object at 0x000001DD49769CD0>

OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by FarnazZeidi** [comment]
i have this error :RuntimeError: Failed to import transformers.models.albert.modeling_albert because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
my code was working but i just updated the torch version

**Comment by Carollxc** [comment]
> i have this error :RuntimeError: Failed to import transformers.models.albert.modeling_albert because of the following error (look up to see its traceback):
> 
> ```
>     CUDA Setup failed despite GPU being available. Please run the following command to get more information:
> 
>     python -m bitsandbytes
> 
>     Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
>     to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
>     and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
> ```
> 
> my code was working but i just updated the torch version

have you solved this ?
