### ISSUE TITLE
python -m bitsandbytes  error

### ISSUE THREAD

**Issue by darrenwang00** [TimDettmers/bitsandbytes#751]
and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/conda/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 105, in run_cuda_setup
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 386, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 271, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 212, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 207, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 183, in remove_non_existent_dirs
    raise exc
  File "/opt/conda/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py", line 179, in remove_non_existent_dirs
    if path.exists():
  File "/opt/conda/lib/python3.8/pathlib.py", line 1407, in exists
    self.stat()
  File "/opt/conda/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/sparkwebide/spark/conf'

**Comment by chencjiajy** [comment]
I met similar error when I test `python -m bitsandbytes`
```shell
Traceback (most recent call last):
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 120, in run_cuda_setup
    binary_name, cudart_path, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 337, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 295, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 232, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 227, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 201, in remove_non_existent_dirs
    raise exc
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 197, in remove_non_existent_dirs
    if path.exists():
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/home/chen/anaconda3/envs/py310/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
OSError: [Errno 107] Transport endpoint is not connected: '/opt/spark/conf
```
