### ISSUE TITLE
BNB_CUDA_VERSION env var leads to broken environment with `_nomatmul` compiled BnB version

### ISSUE THREAD

**Issue by jphme** [TimDettmers/bitsandbytes#760]
Yday I debugged a strange porblem with my docker files, when trying to run my stack on Volta-arch GPUS; bitsandbytes was compiled from source, using

```bash
git clone https://github.com/TimDettmers/bitsandbytes.git && \
    cd bitsandbytes && \
    CUDA_VERSION=118 make cuda11x_nomatmul && \
    python setup.py bdist_wheel
```

without any problems. When running the base image (using NVIDIA Dockerfile as base), e.g. `docker run -it --rm aitrain:latest python -m bitsandbytes` , output doesn't show any problems and correct CUDA version including `/workspace/builds/bitsandbytes/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so`. 

However, when trying to manually specify BNB Version (like I usually do in my train images to be on the safe side), e.g. with `docker run -it --rm -e BNB_CUDA_VERSION="118" aitrain:latest python -m bitsandbytes` , the env breaks, and throws (amongst others): `CUDA SETUP: Required library version not found: libbitsandbytes_cuda118_nocublaslt.so`.

This didn't happen for me with newer architectures and "normal" compilation with `make cuda11x`instead of `_nomatmul` (but I don't know whether this is the source of the problem or its another CUDA problem with the volta architecture).

Full output without `BNB_CUDA_VERSION="118"`:

```bash
==========
== CUDA ==
==========

CUDA Version 11.8.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.8/compat/libcuda.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/workspace/builds/bitsandbytes/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/workspace/builds/bitsandbytes/build/lib/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/workspace/wheels/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/workspace/apex/build/lib.linux-x86_64-cpython-39/scaled_softmax_cuda.cpython-39-x86_64-linux-gnu.so
/workspace/apex/build/lib.linux-x86_64-cpython-39/scaled_upper_triang_masked_softmax_cuda.cpython-39-x86_64-linux-gnu.so
/workspace/apex/build/lib.linux-x86_64-cpython-39/fused_weight_gradient_mlp_cuda.cpython-39-x86_64-linux-gnu.so
/workspace/apex/build/lib.linux-x86_64-cpython-39/fused_layer_norm_cuda.cpython-39-x86_64-linux-gnu.so
/workspace/apex/build/lib.linux-x86_64-cpython-39/scaled_masked_softmax_cuda.cpython-39-x86_64-linux-gnu.so
/workspace/apex/build/lib.linux-x86_64-cpython-39/generic_scaled_masked_softmax_cuda.cpython-39-x86_64-linux-gnu.so
/workspace/apex/build/lib.linux-x86_64-cpython-39/fused_dense_cuda.cpython-39-x86_64-linux-gnu.so
/workspace/apex/build/lib.linux-x86_64-cpython-39/mlp_cuda.cpython-39-x86_64-linux-gnu.so

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
+++++++++++++ /usr/local/cuda/lib64 CUDA PATHS +++++++++++++


++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['7.0']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Running a quick check that:
    + library is importable
    + CUDA function is callable


WARNING: Please be sure to sanitize sensible info from any such env vars!

SUCCESS!
Installation was successful!
```

Full output with `BNB_CUDA_VERSION="118"`:

```bash
==========
== CUDA ==
==========

CUDA Version 11.8.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda_setup/main.py:106: UserWarning:

================================================================================
WARNING: Manual override via BNB_CUDA_VERSION env variable detected!
BNB_CUDA_VERSION=XXX can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64
Loading CUDA version: BNB_CUDA_VERSION=118
================================================================================


  warn((f'\n\n{"="*80}\n'
False

===================================BUG REPORT===================================
/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/nvidia/lib64')}
/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda_setup/main.py:166: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda_setup/main.py:166: UserWarning: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cuda_setup/main.py:166: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cuda118_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=118 make cuda11x_nomatmul
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/root/miniconda3/envs/py3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/bitsandbytes-0.41.1-py3.9.egg/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
