### ISSUE TITLE
python -m bitsandbytes is the error message

### ISSUE THREAD

**Issue by w4d6** [TimDettmers/bitsandbytes#773]
C:\Users\xxxxxxx>python -m bitsandbytes
C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Traceback (most recent call last):
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 96, in <module>
    generate_bug_report_information()
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 60, in generate_bug_report_information
    paths = find_file_recursive(os.getcwd(), '*cuda*so')
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 35, in find_file_recursive
    out, err = execute_and_return(cmd)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 30, in execute_and_return
    std_out, std_err = execute_and_return_decoded_std_streams(command_string)
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 22, in execute_and_return_decoded_std_streams
    return _decode(
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 16, in _decode
    return tuple(
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__main__.py", line 17, in <genexpr>
    to_decode.decode("UTF-8").strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 0: invalid start byte

**Comment by GDissard** [comment]
I have this problem too. Did you manage to solve it ?
