### ISSUE TITLE
python -m bitsandbytes error message

### ISSUE THREAD

**Issue by tmukande-debug** [TimDettmers/bitsandbytes#779]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
CUDA SETUP: Loading binary /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_cluster/_fps_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_cluster/_graclus_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_cluster/_grid_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_cluster/_knn_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_cluster/_nearest_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_cluster/_radius_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_cluster/_rw_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_cluster/_sampler_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_cluster/_version_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_scatter/_scatter_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_scatter/_segment_coo_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_scatter/_segment_csr_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_scatter/_version_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_spline_conv/_basis_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_spline_conv/_version_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_spline_conv/_weighting_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_convert_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_diag_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_ego_sample_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_hgt_sample_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_metis_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_neighbor_sample_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_relabel_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_rw_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_saint_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_sample_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_spmm_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch_sparse/_version_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so
/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/lib/libc10_cuda.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++

++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/bitsandbytes/__main__.py", line 66, in generate_bug_report_information
    lib_path = os.environ['LD_LIBRARY_PATH'].strip()
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LD_LIBRARY_PATH'

**Comment by pk1762012** [comment]
Nothing is working, tried even loading through git clone in windows

**Comment by SadmanSarar** [comment]
Facing the same issue but in Ubuntu

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
