### ISSUE TITLE
Stable diffusion crash

### ISSUE THREAD

**Issue by AK51** [TimDettmers/bitsandbytes#786]
Hi, I just add some extension in stable diffusion and it crashed.
The error seems to related to bitsandbytes.
Or the path problem, I tried several times to set the path... may be I make it worst...

Is there any solution? Thx
If I install a new stable diffusion, will it work?

```
(base) ak@ak-MS-7D99:/usr/local$ ls
bin   cuda-12    cuda-12.2  games    lib  sbin   src
cuda  cuda-12.1  etc        include  man  share
(base) ak@ak-MS-7D99:/usr/local$ export BNB_CUDA_VERSION=122
(base) ak@ak-MS-7D99:/usr/local$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/tim/local/cuda-12.2
```

```
Launching Web UI with arguments: 
/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/cextension.py:101: UserWarning: /home/ak/anaconda3 did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/cextension.py:101: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('local/ak-MS-7D99'), PosixPath('@/tmp/.ICE-unix/1569,unix/ak-MS-7D99')}
  warn(msg)
/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/cextension.py:101: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-ubuntu')}
  warn(msg)
/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/cextension.py:101: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/share/gconf/ubuntu.mandatory.path')}
  warn(msg)
/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/cextension.py:101: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('1'), PosixPath('0')}
  warn(msg)
/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/cextension.py:101: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/6ac15d9c_e8df_4fb7_bd7e_fea3e973ceb4')}
  warn(msg)
/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/cextension.py:101: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/home/ak/.cache/dotnet_bundle_extract')}
  warn(msg)
/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/cextension.py:101: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/share/gconf/ubuntu.default.path')}
  warn(msg)
/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/cextension.py:101: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('tmp/restart')}
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 122
CUDA SETUP: Required library version not found: libbitsandbytes_cuda122_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=122_nomatmul
python setup.py install
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 122
CUDA SETUP: Required library version not found: libbitsandbytes_cuda122_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=122_nomatmul
python setup.py install
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 122
CUDA SETUP: Required library version not found: libbitsandbytes_cuda122_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=122_nomatmul
python setup.py install
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=122_nomatmul
python setup.py install
Traceback (most recent call last):
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/ak/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/transformers/modeling_utils.py", line 85, in <module>
    from accelerate import __version__ as accelerate_version
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/accelerate/utils/__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/accelerate/utils/bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/bitsandbytes/cextension.py", line 118, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs aboveto fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ak/sd/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/home/ak/sd/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/home/ak/sd/stable-diffusion-webui/modules/launch_utils.py", line 432, in start
    import webui
  File "/home/ak/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/home/ak/sd/stable-diffusion-webui/modules/initialize.py", line 16, in imports
    import pytorch_lightning  # noqa: F401
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/pytorch_lightning/utilities/types.py", line 27, in <module>
    from torchmetrics import Metric
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/functional/__init__.py", line 82, in <module>
    from torchmetrics.functional.text.bleu import bleu_score
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/functional/text/__init__.py", line 30, in <module>
    from torchmetrics.functional.text.bert import bert_score  # noqa: F401
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/functional/text/bert.py", line 24, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/torchmetrics/functional/text/helper_embedding_metric.py", line 26, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/ak/sd/stable-diffusion-webui/venv/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs aboveto fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues

```

```
nvidia-smi
Sun Sep 24 02:07:15 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        Off | 00000000:01:00.0  On |                  Off |
| 30%   41C    P8              25W / 450W |    700MiB / 24564MiB |      1%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1305      G   /usr/lib/xorg/Xorg                          122MiB |
|    0   N/A  N/A      1589      G   /usr/bin/gnome-shell                         85MiB |
|    0   N/A  N/A      2665      G   ...irefox/3131/usr/lib/firefox/firefox      473MiB |
+---------------------------------------------------------------------------------------+
```

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
