### ISSUE TITLE
bitsandbytes unable to find CUDA installation

### ISSUE THREAD

**Issue by michaelmior** [TimDettmers/bitsandbytes#793]
On one system, I've had no issue with installing and running bitsandbytes. However, on another, it seems to fail to find my CUDA installation even though torch has no problems. I also tried a separate CUDA installation and set `LD_LIBRARY_PATH` and `BNB_CUDA_VERSION` appropriately. I still get the error below.

```
$ ./cuda_install.sh 117 ~/local 0
$ export LD_LIBRARY_PATH=$HOME/local/cuda-11.7/lib64
$ export BNB_CUDA_VERSION=117
$ python -m bitsandbytes
/home/mjmvcs/.local/share/virtualenvs/annotate-schema-17Hsexv8/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:106: UserWarning:

================================================================================
WARNING: Manual override via BNB_CUDA_VERSION env variable detected!
BNB_CUDA_VERSION=XXX can be used to load a bitsandbytes version that is different from the PyTorch CUDA version.
If this was unintended set the BNB_CUDA_VERSION variable to an empty string: export BNB_CUDA_VERSION=
If you use the manual override make sure the right libcudart.so is in your LD_LIBRARY_PATH
For example by adding the following to your .bashrc: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path_to_cuda_dir/lib64
Loading CUDA version: BNB_CUDA_VERSION=117
================================================================================


  warn((f'\n\n{"="*80}\n'
False

===================================BUG REPORT===================================
/home/mjmvcs/.local/share/virtualenvs/annotate-schema-17Hsexv8/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug repo
rts, please run

python -m bitsandbytes


  warn(msg)
================================================================================                                                                                         
/home/mjmvcs/.local/share/virtualenvs/annotate-schema-17Hsexv8/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Found duplicate ['libcudart.so', 'lib
cudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/mjmvcs/local/cuda-11.7/lib64/libcudart.so.11.0'), PosixPath('/home/mjmvcs/local/cuda-11.7/lib64/libcudart.so')}.. W
e select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior
set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmen
tal variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr
/local/cuda-11.2
  warn(msg)
/home/mjmvcs/.local/share/virtualenvs/annotate-schema-17Hsexv8/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/mjmvcs/local/cuda-11.7/lib64 di
d not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('/.autofs/tools/spack/opt/spack/linux-rhel7-haswell/gcc-4.8.5/tk-8.6.8-hvkrhugfgwww7gtdmim
vjh7e2fguxxi3/lib /.autofs/tools/spack/opt/spack/linux-rhel7-haswell/gcc-4.8.5/tk-8.6.8-hvkrhugfgwww7gtdmimvjh7e2fguxxi3/lib /.autofs/tools/spack/opt/spack/linux-rhel7-haswell/gc
c-4.8.5/tk-8.6.8-hvkrhugfgwww7gtdmimvjh7e2fguxxi3/lib /.autofs/tools/spack/opt/spack/linux-rhel7-haswell/gcc-4.8.5/tk-8.6.8-hvkrhugfgwww7gtdmimvjh7e2fguxxi3/lib')}
The following directories listed in your path were found to be non-existent: {PosixPath('/home/mjmvcs/spack/var/spack/environments/annotate-schema/.spack-env/view/share/pkgconfig
')}
The following directories listed in your path were found to be non-existent: {PosixPath('() {  eval `/usr/bin/modulecmd bash $*`\n}')}
The following directories listed in your path were found to be non-existent: {PosixPath('() {  '), PosixPath(' /home/mjmvcs/spack/bin/spack;\n _spack_shell_wrapper "$@";\n return
 $?\n}'), PosixPath(' /home/mjmvcs/spack/share/spack/setup-env.sh;\n '), PosixPath(' the real spack script is here'), PosixPath(' this is a shell function from')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=117, Highest Compute Capability: 6.1.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
/home/mjmvcs/.local/share/virtualenvs/annotate-schema-17Hsexv8/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: WARNING: Compute capability < 7.5 det
ected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog
/4bit-transformers-bitsandbytes
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cuda117_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/home/mjmvcs/spack/var/spack/environments/annotate-schema/.spack-env/view/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/mjmvcs/spack/var/spack/environments/annotate-schema/.spack-env/view/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/mjmvcs/spack/var/spack/environments/annotate-schema/.spack-env/view/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/mjmvcs/.local/share/virtualenvs/annotate-schema-17Hsexv8/lib/python3.8/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/mjmvcs/.local/share/virtualenvs/annotate-schema-17Hsexv8/lib/python3.8/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/mjmvcs/.local/share/virtualenvs/annotate-schema-17Hsexv8/lib/python3.8/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/mjmvcs/.local/share/virtualenvs/annotate-schema-17Hsexv8/lib/python3.8/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/mjmvcs/.local/share/virtualenvs/annotate-schema-17Hsexv8/lib/python3.8/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/mjmvcs/.local/share/virtualenvs/annotate-schema-17Hsexv8/lib/python3.8/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

I'll note that I've also tried compiling bitsandbytes myself and that hasn't fixed anything either. Any help would be appreciated!

**Comment by 3dj18** [comment]
@michaelmior Hey there! I'm currently running into the same issue! Have you had any luck resolving it?

**Comment by TerrinX** [comment]
Same here

**Comment by GlycerinLOL** [comment]
Same issue here, my cuda version is 12.2
any progress here?

**Comment by TerrinX** [comment]
Best solution so far is to delete the "venv" file and let it rebuild when it breaks

**Comment by michaelmior** [comment]
@TerrinX As I mentioned in the issue, I have tried compiling bitsandbytes from scratch and it's still not able to detect the CUDA version. There's nothing to delete and rebuild.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by JohnHerry** [comment]
try  to download the compiled libbitsandbytes_XX.so  according to your cuda version and move to where the local bitesandbytes installed.

https://huggingface.co/spaces/algovenus/text-generation-webui/tree/main/venv/lib/python3.10/site-packages/bitsandbytes
