### ISSUE TITLE
RuntimeError: Failed to import transformers.modeling_utils in a1111

### ISSUE THREAD

**Issue by 108806** [TimDettmers/bitsandbytes#799]
I have this error, my a1111 installation depends on bitsandbytes. 

```
(3106) H:\PROJECTS\AI\_SD_WEBUI>webui.bat
venv "H:\PROJECTS\AI\_SD_WEBUI\venv\Scripts\Python.exe"
Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing Miaoshou assistant requirement: gpt_index==0.4.24
Installing Miaoshou assistant requirement: langchain==0.0.132
Installing Miaoshou assistant requirement: gradio_client==0.5.0
False

===================================BUG REPORT===================================
H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('D'), WindowsPath('/_anaconda/envs/3106/lib')}
H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: D:\_anaconda\envs\3106 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {WindowsPath('tmp/restart')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 7.5.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
Traceback (most recent call last):
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\launch_utils.py", line 231, in run_extension_installer
    stdout = run(f'"{python}" "{path_installer}"', errdesc=f"Error running install.py for extension {extension_dir}", custom_env=env).strip()
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\launch_utils.py", line 115, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Error running install.py for extension H:\PROJECTS\AI\_SD_WEBUI\extensions\sd-webui-roop.
Command: "H:\PROJECTS\AI\_SD_WEBUI\venv\Scripts\python.exe" "H:\PROJECTS\AI\_SD_WEBUI\extensions\sd-webui-roop\install.py"
Error code: 1
stderr: Traceback (most recent call last):
  File "H:\PROJECTS\AI\_SD_WEBUI\extensions\sd-webui-roop\install.py", line 25, in <module>
    download(model_url, model_path)
  File "H:\PROJECTS\AI\_SD_WEBUI\extensions\sd-webui-roop\install.py", line 16, in download
    request = urllib.request.urlopen(url)
  File "D:\_anaconda\envs\3106\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "D:\_anaconda\envs\3106\lib\urllib\request.py", line 525, in open
    response = meth(req, response)
  File "D:\_anaconda\envs\3106\lib\urllib\request.py", line 634, in http_response
    response = self.parent.error(
  File "D:\_anaconda\envs\3106\lib\urllib\request.py", line 563, in error
    return self._call_chain(*args)
  File "D:\_anaconda\envs\3106\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "D:\_anaconda\envs\3106\lib\urllib\request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\_anaconda\envs\3106\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\transformers\modeling_utils.py", line 85, in <module>
    from accelerate import __version__ as accelerate_version
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\accelerate\accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\accelerate\checkpointing.py", line 24, in <module>
    from .utils import (
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\accelerate\utils\__init__.py", line 131, in <module>
    from .bnb import has_4bit_bnb_layers, load_and_quantize_model
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\accelerate\utils\bnb.py", line 42, in <module>
    import bitsandbytes as bnb
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\script_loading.py", line 26, in preload_extensions
    module = load_module(preload_script)
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\PROJECTS\AI\_SD_WEBUI\extensions\a1111-sd-webui-lycoris\preload.py", line 2, in <module>
    from modules import paths
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\paths.py", line 61, in <module>
    import sgm  # noqa: F401
  File "H:\PROJECTS\AI\_SD_WEBUI\repositories\generative-models\sgm\__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "H:\PROJECTS\AI\_SD_WEBUI\repositories\generative-models\sgm\models\__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "H:\PROJECTS\AI\_SD_WEBUI\repositories\generative-models\sgm\models\autoencoder.py", line 6, in <module>
    import pytorch_lightning as pl
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
    from torchmetrics import Metric
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\torchmetrics\functional\__init__.py", line 120, in <module>
    from torchmetrics.functional.text._deprecated import _bleu_score as bleu_score
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\torchmetrics\functional\text\__init__.py", line 50, in <module>
    from torchmetrics.functional.text.bert import bert_score  # noqa: F401
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\torchmetrics\functional\text\bert.py", line 23, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\torchmetrics\functional\text\helper_embedding_metric.py", line 27, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "H:\PROJECTS\AI\_SD_WEBUI\venv\lib\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\PROJECTS\AI\_SD_WEBUI\launch.py", line 48, in <module>
    main()
  File "H:\PROJECTS\AI\_SD_WEBUI\launch.py", line 39, in main
    prepare_environment()
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\launch_utils.py", line 400, in prepare_environment
    run_extensions_installers(settings_file=args.ui_settings_file)
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\launch_utils.py", line 268, in run_extensions_installers
    run_extension_installer(path)
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\launch_utils.py", line 235, in run_extension_installer
    errors.report(str(e))
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\errors.py", line 29, in report
    record_exception()
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\errors.py", line 17, in record_exception
    from modules import sysinfo
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\sysinfo.py", line 13, in <module>
    from modules import paths_internal, timer, shared, extensions, errors
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\shared.py", line 5, in <module>
    from modules import shared_cmd_options, shared_gradio_themes, options, shared_items, sd_models_types
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\shared_cmd_options.py", line 9, in <module>
    script_loading.preload_extensions(extensions_dir, parser, extension_list=launch.list_extensions(launch.args.ui_settings_file))
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\script_loading.py", line 31, in preload_extensions
    errors.report(f"Error running preload() for {preload_script}", exc_info=True)
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\errors.py", line 29, in report
    record_exception()
  File "H:\PROJECTS\AI\_SD_WEBUI\modules\errors.py", line 18, in record_exception
    exception_records.append(sysinfo.format_exception(e, tb))
AttributeError: partially initialized module 'modules.sysinfo' has no attribute 'format_exception' (most likely due to a circular import)
```

```
(3106) H:\PROJECTS\AI\_SD_WEBUI>python -m bitsandbytes

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
binary_path: D:\_anaconda\envs\3106\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll
CUDA SETUP: Loading binary D:\_anaconda\envs\3106\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'D:\_anaconda\envs\3106\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
CUDA SETUP: Loading binary D:\_anaconda\envs\3106\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll...
Could not find module 'D:\_anaconda\envs\3106\lib\site-packages\bitsandbytes\cuda_setup\libbitsandbytes_cuda116.dll' (or one of its dependencies). Try using the full path with constructor syntax.
D:\_anaconda\envs\3106\lib\site-packages\bitsandbytes\cextension.py:31: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++ DEBUG INFORMATION +++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

++++++++++ POTENTIALLY LIBRARY-PATH-LIKE ENV VARS ++++++++++
'SD_WEBUI_RESTART': 'tmp/restart'
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

WARNING: Please be sure to sanitize sensible info from any such env vars!

++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = False
Traceback (most recent call last):
  File "D:\_anaconda\envs\3106\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\_anaconda\envs\3106\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\_anaconda\envs\3106\lib\site-packages\bitsandbytes\__main__.py", line 47, in <module>
    print(f"COMPUTE_CAPABILITIES_PER_GPU = {get_compute_capabilities(cuda)}")
  File "D:\_anaconda\envs\3106\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 336, in get_compute_capabilities
    check_cuda_result(cuda, cuda.cuDeviceGetCount(ct.byref(nGpus)))
AttributeError: 'NoneType' object has no attribute 'cuDeviceGetCount'
```

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
