### ISSUE TITLE
`Linear8bitLt` `backward` `RuntimeError`: size mismatch

### ISSUE THREAD

**Issue by carmocca** [TimDettmers/bitsandbytes#804]
Repro code:

```python
import torch
import torch.nn as nn
from bitsandbytes.nn.modules import Linear8bitLt


class Linear(Linear8bitLt):
    def __init__(self, *args, device=None, threshold=6.0, **kwargs):
        super().__init__(*args, device=device, has_fp16_weights=False, **kwargs)


class SimpleNet(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, num_layers):
        super().__init__()
        self.num_layers = num_layers
        self.linears = nn.ModuleList([Linear(input_size, hidden_size)])
        self.nonlinearities = nn.ModuleList([nn.ReLU()])

        if num_layers > 1:
            for _ in range(num_layers - 1):
                self.linears.append(Linear(hidden_size, hidden_size))
                self.nonlinearities.append(nn.ReLU())

        self.output_linear = Linear(hidden_size, output_size)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        for i in range(self.num_layers):
            x = self.linears[i](x)
            x = self.nonlinearities[i](x)
        x = self.output_linear(x)
        return self.softmax(x)


device = torch.device("cuda")
dtype = torch.float16

input_size = 16
model = SimpleNet(input_size, input_size * 2, 8, 1)
model.to(device)
x = torch.randn(10, input_size, device=device, dtype=dtype)

loss = model(x).sum()
loss.backward()

print(loss)
```

```python
Traceback (most recent call last):
  File "/home/demo.py", line 43, in <module>
    loss.backward()
  File "/home/venv/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/home/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 485, in backward
    .mul_(state.SCB.unsqueeze(1).mul(1.0 / 127.0))
RuntimeError: The size of tensor a (32) must match the size of tensor b (8) at non-singleton dimension 0
```

The same code works with the 4bit layers.

**Comment by edbeeching** [comment]
Hey @carmocca , I have the same error. Did you manage to resolve it?

**Comment by carmocca** [comment]
Unfortunately no

**Comment by hanoonaR** [comment]
Hi @carmocca, @edbeeching, I noticed the discussion on this closed issue. I'm facing a similar challenge and would greatly appreciate any insights or solutions you might have found. @TimDettmers, your expertise on this matter would also be incredibly valuable. Thanks in advance for any help you can provide!
