### ISSUE TITLE
example `int8_inference_huggingface.py` encounters problem but `python -m bitsandbytes` succeeds

### ISSUE THREAD

**Issue by davidleejy** [TimDettmers/bitsandbytes#823]
I compiled bitsandbytes with:
```
CUDA_VERSION=116 make cuda116
python setup.py install
```

and encountered error when running `python examples/int8_inference_huggingface.py`:

```
$ python examples/int8_inference_huggingface.py

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'.
The class this function is called from is 'LlamaTokenizer'.
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thouroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
False
 
===================================BUG REPORT===================================
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run
 
python -m bitsandbytes
 
 
  warn(msg)
================================================================================
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/davidlee/anaconda3/envs/bnb did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0'), PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=116, Highest Compute Capability: 8.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Required library version not found: libbitsandbytes_cuda116.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...
 
================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================
 
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=116 make cuda11x
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1282, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/transformers/integrations/bitsandbytes.py", line 11, in <module>
    import bitsandbytes as bnb
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:
 
        python -m bitsandbytes
 
        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/home/davidlee/code/bitsandbytes/examples/int8_inference_huggingface.py", line 21, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3096, in from_pretrained
    from .integrations import get_keys_to_not_convert, replace_with_bnb_linear
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.integrations.bitsandbytes because of the following error (look up to see its traceback):
 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:
 
        python -m bitsandbytes
 
        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

But python -m bitsandbytes` succeeds with:

```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cpp.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/torch/lib/libc10_cuda.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/torch/lib/libtorch_cuda_linalg.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cu.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122_nocublaslt.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110_nocublaslt.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda110.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda122.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/home/davidlee/anaconda3/envs/bnb/lib/python3.10/site-packages/bitsandbytes-0.41.1-py3.10.egg/bitsandbytes/libbitsandbytes_cuda116.so
 
++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.6/compat/libcuda.so
/usr/local/cuda-11.6/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.6/targets/x86_64-linux/lib/libcudart.so
 
+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++
/home/davidlee/code/bitsandbytes/build/lib/bitsandbytes/libbitsandbytes_cuda116.so
/home/davidlee/code/bitsandbytes/bitsandbytes/libbitsandbytes_cuda116.so
 
++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
 
++++++++++++++++++++++++++ OTHER +++++++++++++++++++++++++++
COMPILED_WITH_CUDA = True
COMPUTE_CAPABILITIES_PER_GPU = ['8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0', '8.0']
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++++++ DEBUG INFO END ++++++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
Running a quick check that:
    + library is importable
    + CUDA function is callable
 
 
WARNING: Please be sure to sanitize sensible info from any such env vars!
 
SUCCESS!
Installation was successful!

```

**Comment by davidleejy** [comment]
I've tried adding path to cuda 11.6's library files to no avail:
`export LD_LIBRARY_PATH=/usr/local/cuda-11.6/targets/x86_64-linux/lib`

Also tried setting `BNB_CUDA_VERSION=116` to no avail.

**Comment by ihongxx** [comment]
$ sudo apt install gcc-10 g++-10
$ export CC=/usr/bin/gcc-10
$ export CXX=/usr/bin/g++-10
$ export CUDA_ROOT=/usr/local/cuda
$ ln -s /usr/bin/gcc-10 $CUDA_ROOT/bin/gcc
$ ln -s /usr/bin/g++-10 $CUDA_ROOT/bin/g++
$ git clone https://github.com/timdettmers/bitsandbytes.git
$ cd bitsandbytes
$ CUDA_HOME=/usr/local/cuda-11.6 CUDA_VERSION=116 make cuda11x
$ python setup.py install
I succeeded！
