### ISSUE TITLE
Assertion Error during Text Generation (model inference): assert quant_state is not None

### ISSUE THREAD

**Issue by akjindal53244** [TimDettmers/bitsandbytes#825]
Hi,

I am facing an issue while doing text generation with Mistral 7B model. I tried it with llama-2 7B model and seeing the same error.

Error log:
```FP4 quantization state not initialized. Please call .cuda() or .to(device) on the LinearFP4 layer first.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/transformers/generation/utils.py", line 1693, in generate
    return self.sample(
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/transformers/generation/utils.py", line 2775, in sample
    outputs = self(
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/transformers/models/mistral/modeling_mistral.py", line 1042, in forward
    outputs = self.model(
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/transformers/models/mistral/modeling_mistral.py", line 929, in forward
    layer_outputs = decoder_layer(
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/transformers/models/mistral/modeling_mistral.py", line 618, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/transformers/models/mistral/modeling_mistral.py", line 258, in forward
    query_states = self.q_proj(hidden_states)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/bitsandbytes/nn/modules.py", line 248, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "/home/minimalist/miniconda3/envs/tempPy39/lib/python3.9/site-packages/bitsandbytes/autograd/_functions.py", line 567, in matmul_4bit
    assert quant_state is not None
AssertionError
```

**Steps to Reproduce:**

1. **Installations**:

```
conda create -n <env_name> python=3.9
conda activate <env_name>
pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cu118
pip install scipy
pip install -q -U bitsandbytes
pip install -q -U git+https://github.com/huggingface/transformers.git
pip install -q -U git+https://github.com/huggingface/peft.git
pip install -q -U git+https://github.com/huggingface/accelerate.git
```

2. **Code**

```
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

model_id = "mistralai/Mistral-7B-Instruct-v0.1"
model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=bnb_config, device_map="{"": "cpu"}")
tokenizer = AutoTokenizer.from_pretrained(model_id)

PROMPT= """ ### Instruction: Act as a data science expert.
### Question:
Explain to me what is Large Language Model. Assume that I am a 5-year-old child.

### Answer:
"""

model_inputs = tokenizer(PROMPT, return_tensors="pt", add_special_tokens=True)

generated_ids = model.generate(**model_inputs, max_new_tokens=1000, do_sample=True, pad_token_id=tokenizer.eos_token_id)
```

I found similar issues: 
1. https://stackoverflow.com/questions/77008422/error-when-running-a-huggingface-model-in-4bit-mode-in-streamlit-using-bitsnbyte
2. https://github.com/TimDettmers/bitsandbytes/issues/764

**Comment by akjindal53244** [comment]
I verified that it doesn't fail, if I remove `quantization_config` parameter while calling `AutoModelForCausalLM.from_pretrained()` to load the model so it seems to do with `BitsAndBytes`. 

Specifically: 

- `model = AutoModelForCausalLM.from_pretrained(model_id, device_map="{"": "cpu"}")` works 
- But `model = AutoModelForCausalLM.from_pretrained(model_id, quantization_config=bnb_config, device_map="{"": "cpu"}")` fails with error mentioned above.

**Comment by akjindal53244** [comment]
Hi @TimDettmers , could you help take a look here? Thanks!

**Comment by sigma-andex** [comment]
Getting the same error here. Tried with cuda 11 and 12.

Dependencies
```bash
...
torch==2.1.0
transformers==4.34.0
tokenizers==0.14.0
packaging==23.2
ninja==1.11.1.1
bitsandbytes==0.41.1
accelerate==0.24.0
scipy==1.11.3
wheel==0.41.3
setuptools==68.2.2
```
Code:
```
model_name_or_path = meta-llama/Llama-2-70b-chat-hf
AutoModelForCausalLM.from_pretrained(model_name_or_path,
        load_in_4bit=True,
        quantization_config=BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch.bfloat16,
            bnb_4bit_use_double_quant=True,
            bnb_4bit_quant_type='nf4'
        ),
        device_map="cuda",
        use_flash_attention_2=True
        )
 ```

<details>
<summary>Logs</summary>
Exception in thread Thread-3 (generate):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1652, in generate
    return self.sample(
  File "/opt/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2734, in sample
    outputs = self(
  File "/opt/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1038, in forward
    outputs = self.model(
  File "/opt/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 925, in forward
    layer_outputs = decoder_layer(
  File "/opt/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 635, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/opt/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 437, in forward
    query_states = self.q_proj(hidden_states)
  File "/opt/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 248, in forward
    out = bnb.matmul_4bit(x, self.weight.t(), bias=bias, quant_state=self.weight.quant_state)
  File "/opt/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 567, in matmul_4bit
    assert quant_state is not None
AssertionError
</summary>

**Comment by shivanandmn** [comment]
@here, the error you are getting is from `accelerate` library.
in this line 
![image](https://github.com/TimDettmers/bitsandbytes/assets/21271698/5414f3a2-bafd-4755-92f7-1a86da916b9a)
 device is trying to fetch index of the cuda, if you have given `cuda` as device then `torch.device("cuda").index` will be None. 
The solution is to give as `cuda:0` or `auto` as device.
https://github.com/huggingface/accelerate/blob/fc0a43c3c1235f1540b5401e03a1710fb72fb8e9/src/accelerate/utils/modeling.py#L361
