### ISSUE TITLE
windows调用报错

### ISSUE THREAD

**Issue by wjl3022** [TimDettmers/bitsandbytes#852]
torch2.1.0与cuda11.8版本调用bitsandbytes提示
python -m bitsandbytes

  warn(msg)
C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
Traceback (most recent call last):
  File "E:\GPT\Test.py", line 4, in <module>
    from peft import LoraConfig
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\auto.py", line 31, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\mapping.py", line 23, in <module>
    from .peft_model import (
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\peft_model.py", line 38, in <module>
    from .tuners import (
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\peft\tuners\lora.py", line 45, in <module>
    import bitsandbytes as bnb
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by recman55** [comment]
same error occurred.

@TimDettmers hey Tim, why did you ignore this problems long time!?

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）
