### ISSUE TITLE
Unable to get error logs on import

### ISSUE THREAD

**Issue by NicoLivesey** [TimDettmers/bitsandbytes#86]
Hey, i'm trying to import `bitsandbytes` on a multi-gpu server (2 x Tesla P6) with cuda 10.2.
On `import bitsandbytes` I get

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File ".../python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File ".../python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File ".../python3.10/site-packages/bitsandbytes/cextension.py", line 113, in <module>
    lib = CUDASetup.get_instance().lib
  File ".../python3.10/site-packages/bitsandbytes/cextension.py", line 109, in get_instance
    cls._instance.initialize()
  File ".../python3.10/site-packages/bitsandbytes/cextension.py", line 59, in initialize
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File ".../python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 123, in evaluate_cuda_setup
    cuda = get_cuda_lib_handle()
  File ".../python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 63, in get_cuda_lib_handle
    check_cuda_result(cuda, cuda.cuInit(0))
  File ".../python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 31, in check_cuda_result
    CUDASetup.get_instance().add_log_entry(f"CUDA exception! Error code: {error_str.value.decode()}")
AttributeError: 'NoneType' object has no attribute 'decode'
```

It seems that the sanity checks happening on the import fails but I don't get any `error_str.value`. My assumption is that the Tesla P6 is too old to support `bitandbytes` but anyway I find it weird that the error cannot be traced well.

Can you please confirm ?

**Comment by TimDettmers** [comment]
Thanks for the report! Pascal GPUs should be just fine (`LLM.int8()` is not supported, but other functions are). 

I am not sure what the problem is. My guess would be some issues with the CUDA install, but I have never seen an error like this. It probably means that the function call failed before the error code could be returned, which would be unusual. 

I will add an error message for now, which should no longer crash the application. With that, more information on the environment should be printed for debugging purposes.

Can you please run `python -m bitsandbytes` and paste the outputs here? That would help speed up the debugging.

**Comment by luckymomohd** [comment]
I'm having the same issue with bitsandbytes 0.35.4 and CUDA 11.7.
Trying to use 8bit adam gives me:

> Exception importing 8bit adam: 'NoneType' object has no attribute 'decode'
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/train_dreambooth.py", line 304, in inner_loop
    import bitsandbytes as bnb
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 113, in <module>
    lib = CUDASetup.get_instance().lib
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 109, in get_instance
    cls._instance.initialize()
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 59, in initialize
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 123, in evaluate_cuda_setup
    cuda = get_cuda_lib_handle()
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 63, in get_cuda_lib_handle
    check_cuda_result(cuda, cuda.cuInit(0))
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 31, in check_cuda_result
    CUDASetup.get_instance().add_log_entry(f"CUDA exception! Error code: {error_str.value.decode()}")
AttributeError: 'NoneType' object has no attribute 'decode'

Running `python -m bitsandbytes` returns:

> Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 113, in <module>
    lib = CUDASetup.get_instance().lib
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 109, in get_instance
    cls._instance.initialize()
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 59, in initialize
    binary_name, cudart_path, cuda, cc, cuda_version_string = evaluate_cuda_setup()
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 123, in evaluate_cuda_setup
    cuda = get_cuda_lib_handle()
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 63, in get_cuda_lib_handle
    check_cuda_result(cuda, cuda.cuInit(0))
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 31, in check_cuda_result
    CUDASetup.get_instance().add_log_entry(f"CUDA exception! Error code: {error_str.value.decode()}")
AttributeError: 'NoneType' object has no attribute 'decode'

Using bitsandbytes 0.36.0post1 `python -m bitsandbytes` gives me:

> Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 7, in <module>
    from .autograd._functions import (
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/autograd/_functions.py", line 8, in <module>
    import bitsandbytes.functional as F
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/functional.py", line 17, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    if 'BITSANDBYTES_NOWELCOME' not in os.environ or str(os.environ['BITSANDBYTES_NOWELCOME']) == '0':
NameError: name 'os' is not defined
