### ISSUE TITLE
BnB on a cluster: permission denied: '/var/run/consul/http.sock'

### ISSUE THREAD

**Issue by Eugleo** [TimDettmers/bitsandbytes#865]
Installing bnb with `pip install` into my venv and then running a `python -m bitsandbytes` on a GPU-enabled node on a cluster results in:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/cextension.py", line 13, in <module>
    setup.run_cuda_setup()
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/cuda_setup/main.py", line 120, in run_cuda_setup
    binary_name, cudart_path, cc, cuda_version_string = evaluate_cuda_setup()
                                                        ^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/cuda_setup/main.py", line 337, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/cuda_setup/main.py", line 295, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/cuda_setup/main.py", line 232, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/cuda_setup/main.py", line 227, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/cuda_setup/main.py", line 201, in remove_non_existent_dirs
    raise exc
  File "/cluster/home/ewybitul/dsl_hate_speech/.venv/lib64/python3.11/site-packages/bitsandbytes/cuda_setup/main.py", line 197, in remove_non_existent_dirs
    if path.exists():
       ^^^^^^^^^^^^^
  File "/cluster/apps/nss/gcc-8.2.0/python/3.11.2/x86_64/lib64/python3.11/pathlib.py", line 1235, in exists
    self.stat()
  File "/cluster/apps/nss/gcc-8.2.0/python/3.11.2/x86_64/lib64/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/var/run/consul/http.sock'
```

Any idea what this might be related to?

Context:
- I'm running this on a cluster using slurm (if that matters)
- I'm using `torch==2.0.1+cu118`
- the GPU supports up to cuda 12.0 as per `nvidia-smi`
- I only have cuda 11.8.0 on path (verified via `PATH`, `CUDA_HOMA` and `LD_LIBRARY_PATH`) since that's what I load with lmod

Compiling the package throws permission-related errors and since 11.8 should be precompiled anyway I decided to open this issue instead of fiddling with permissions.

**Comment by swumagic** [comment]
Bitsandbytes was not supported windows before, but my method can support windows.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.41.1-py3-none-win_amd64.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by swumagic** [comment]
OR you are  Linux distribution (Ubuntu, MacOS, etc.)system ,AND CUDA Version: 11.X.

Bitsandbytes can support ubuntu.（yuhuang）
1  open folder J:\StableDiffusion\sdwebui，Click the address bar of the folder and enter CMD
or WIN+R, CMD  。enter，cd /d J:\StableDiffusion\sdwebui
2  J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes

3 J:\StableDiffusion\sdwebui\py310\python.exe -m pip uninstall bitsandbytes-windows

4 J:\StableDiffusion\sdwebui\py310\python.exe -m pip install https://github.com/TimDettmers/bitsandbytes/releases/download/0.41.0/bitsandbytes-0.41.0-py3-none-any.whl

Replace your SD venv directory file（python.exe Folder） here（J:\StableDiffusion\sdwebui\py310）

**Comment by Eugleo** [comment]
I am a bit confused here; the system is indeed Linux — are you suggesting I should install a pre-compiled wheel directly off of github instead of going through pypi? 

Also, out of curiosity, what is the reason why pypi fails to install said wheel for me?

**Comment by RibinMTC** [comment]
I also encounted the same error when running the code on a slurm-based cluster. How can I solve this issue?

**Comment by Eugleo** [comment]
Someone told me the fix could be setting the env variable `CONSUL_HTTP_ADDR=`, i.e. to an empty string. I didn't have the opportunity to test is myself yet, but you can try it.

**Comment by RibinMTC** [comment]
Setting `CONSUL_HTTP_ADDR=` to an empty string has indeed solved the issue. Could you explain why this fixed the error? And thanks for the suggestion :)

**Comment by Eugleo** [comment]
From what I've heard from the person who suggested the fix, bnb checks for CUDA in a lot of different places — here, it detects that a specific path exists and tries to access it, but doesn't pay attention to the permissions, which causes the error. The fix effectively tells bnb that the path doesn't exist and so bnb ignores it, as it should've done in the first place.
