### ISSUE TITLE
bitsandbytes just doesn't work. Even having the right version of pytorch and CUDA

### ISSUE THREAD

**Issue by venturaEffect** [TimDettmers/bitsandbytes#890]
Very frustrating, trying to run a script, installed everything in different versions for torch and CUDA (12.1, 12.0, 11.8,... ) Nothing. It just gives same error and tells to run `python -m bitsandbytes` what brings to the same error.

Tried by clonning the repo: Nothing. Same error.
Trie by `pip install bitsandbytes==0.41.2.post2` Nothing. Same error.

Here the error:

`
(llamaCPP)C:\Users\zaesa\OneDrive\Escritorio\code\llama.cpp>python download_model_to_convert.py
You have loaded an AWQ model on CPU and have a CUDA device available, make sure to set your model on a GPU device in order to run your model.
False

===================================BUG REPORT===================================
C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\bitsandbytes\cuda_setup\main.py:166: UserWarning: C:\Users\zaesa\anaconda3\envs\llamaCPP did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {WindowsPath('AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAALlVQwdfVQEq2ykt8ra5mZgQAAAACAAAAAAAQZgAAAAEAACAAAADQ4AOCb3OtZsbw6cOG66Asmk/GzUYFzw7ZiDbfqALNsAAAAAAOgAAAAAIAACAAAAC7BLJjV0BqCcgFypX5Lg3oAG6A0aVJl3aEb9yK1BJZBGAAAAADs1iFUmNBJBcrsvCkfzRUE59nh/+u8nPlqxL4IY8y5QTGubL0voGlzixA1JwCHPRiNuREQClH8P1+CXoZ2aR1HWJfgVS/eqBs8njQ6khoFagNvV/UH+CliqYZB5uxiCNAAAAAkVUvdhu7oXWcGkZMFAXxs8cVvWHgVQWy9PyUl4jRrAiAz8A2gBAAxjvk7J/VayZezpyqgprZ2EgQwawFuINgyQ==')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.9.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\bitsandbytes\libbitsandbytes_cuda121.so...
argument of type 'WindowsPath' is not iterable
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh      
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local  
Traceback (most recent call last):
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\transformers\utils\import_utils.py", line 1353, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)     
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^     
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import   
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked 
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\transformers\integrations\bitsandbytes.py", line 11, in <module>       
    import bitsandbytes as bnb
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zaesa\OneDrive\Escritorio\code\llama.cpp\download_model_to_convert.py", line 15, in <module>
    model = AutoModelForCausalLM.from_pretrained(model_path)        
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\transformers\models\auto\auto_factory.py", line 566, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\transformers\modeling_utils.py", line 3312, in from_pretrained
    from .integrations import get_keys_to_not_convert, replace_with_awq_linear
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\transformers\utils\import_utils.py", line 1343, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zaesa\anaconda3\envs\llamaCPP\Lib\site-packages\transformers\utils\import_utils.py", line 1355, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.integrations.bitsandbytes because of the following error (look up to see its traceback):    

        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
`

torch version: 2.1.1
CUDA: cuda_11.8

Any clue what is going on? Appreciate

**Comment by act-agi** [comment]
Looks like your nvcc is not setup. Can you try nvcc on terminal? 
It is usually under the bin of your cuda path something like /usr/local/cuda/bin
if you find it there, set it up to your PATH 

Once done with that follow steps below,

`git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=<your cuda version> make cuda11x
python setup.py install
`

**Comment by ken19980727** [comment]
Has this problem been sloved?
