### ISSUE TITLE
A bug when finetuning llama-7b

### ISSUE THREAD

**Issue by lyccyl1** [TimDettmers/bitsandbytes#893]
```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================

Traceback (most recent call last):
  File "/data0/user/ycliu/work1/llama/alpaca-lora/finetune.py", line 283, in <module>
    fire.Fire(train)
  File "/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data0/user/ycliu/work1/llama/alpaca-lora/finetune.py", line 112, in train
    model = LlamaForCausalLM.from_pretrained(
  File "/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2749, in from_pretrained
    raise ImportError(
ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 
```
And when I input python -m bitsandbytes in command prompt

Output:
```
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /data0/user/ycliu/.conda/envs/nlp/lib/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary /data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
++++++++++++++++++ BUG REPORT INFORMATION ++++++++++++++++++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

+++++++++++++++++++ ANACONDA CUDA PATHS ++++++++++++++++++++
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/torch/lib/libc10_cuda.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/torch/lib/libtorch_cuda_linalg.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda111.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda111_nocublaslt.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda113_nocublaslt.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda114_nocublaslt.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda115.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda115_nocublaslt.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda116_nocublaslt.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118_nocublaslt.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda120.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda120_nocublaslt.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda121_nocublaslt.so
/data0/user/ycliu/.conda/envs/nlp/lib/libicudata.so

++++++++++++++++++ /usr/local CUDA PATHS +++++++++++++++++++
/usr/local/cuda-11.8/targets/x86_64-linux/lib/libcudart.so
/usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-glibc_2_11_3-x64/libcuda-injection.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-t210-a64/libcuda-injection.so
/usr/local/cuda-11.8/nsight-compute-2022.3.0/target/linux-desktop-glibc_2_19_0-ppc64le/libcuda-injection.so

+++++++++++++++ WORKING DIRECTORY CUDA PATHS +++++++++++++++


++++++++++++++++++ LD_LIBRARY CUDA PATHS +++++++++++++++++++
Traceback (most recent call last):
  File "/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/__main__.py", line 95, in <module>
    generate_bug_report_information()
  File "/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/site-packages/bitsandbytes/__main__.py", line 66, in generate_bug_report_information
    lib_path = os.environ['LD_LIBRARY_PATH'].strip()
  File "/data0/user/ycliu/.conda/envs/nlp/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'LD_LIBRARY_PATH'
```

Could anyone help me for this bug?

**Comment by lyccyl1** [comment]
I fix this problem by change the script code 
from 
```
#!/bin/bash
#SBATCH -J test                  
#SBATCH -o /data0/user/ycliu/work1/llama/lora_log/lora_sft.out             

python finetune.py \
    --base_model '/data0/user/ycliu/work1/models/models--meta-llama--Llama-2-7b-hf/snapshots' \
    --data_path '/data0/user/ycliu/work1/peft/data'\
    --output_dir './lora-alpaca-res' 
```

to 
```

#!/bin/bash
#SBATCH -J test                  
#SBATCH -o /data0/user/ycliu/work1/llama/lora_log/lora_sft.out             
#SBATCH --qos=debug              
#SBATCH -N 1              
#SBATCH --ntasks-per-node=1     
#SBATCH --cpus-per-task=1      
#SBATCH --gres=gpu:4              
#SBATCh -w gpu01              
python finetune.py \
    --base_model '/data0/user/ycliu/work1/models/models--meta-llama--Llama-2-7b-hf/snapshots' \
    --data_path '/data0/user/ycliu/work1/peft/data'\
    --output_dir './lora-alpaca-res' 
```

Then it works. Anyone can tell me reasons? thx a lot.
