### ISSUE TITLE
suddenly getting this error after everything was running fine last night running windows 10 and this is effecting both fooocus and vlad 

### ISSUE THREAD

**Issue by Windrider30** [TimDettmers/bitsandbytes#907]
===================================BUG REPORT===================================
C:\Users\Dennis\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes-0.41.3-py3.10.egg\bitsandbytes\cuda_setup\main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {WindowsPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 6.1.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
C:\Users\Dennis\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes-0.41.3-py3.10.egg\bitsandbytes\cuda_setup\main.py:166: UserWarning: WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!                     If you run into issues with 8-bit matmul, you can try 4-bit quantization: https://huggingface.co/blog/4bit-transformers-bitsandbytes
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cuda121_nocublaslt.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
2. CUDA driver not installed
3. CUDA not installed
4. You have multiple conflicting CUDA libraries
5. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "C:\Users\Dennis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\Dennis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\Dennis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Dennis\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes-0.41.3-py3.10.egg\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "C:\Users\Dennis\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes-0.41.3-py3.10.egg\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "C:\Users\Dennis\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes-0.41.3-py3.10.egg\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "C:\Users\Dennis\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes-0.41.3-py3.10.egg\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "C:\Users\Dennis\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes-0.41.3-py3.10.egg\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "C:\Users\Dennis\AppData\Local\Programs\Python\Python310\lib\site-packages\bitsandbytes-0.41.3-py3.10.egg\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by poedator** [comment]
Got same error with 0.41.3.post1 when trying to test 4bit serialization. 0.41.3. works ok. installed and reinstalled twice.
@Titus-von-Koeller please take a look

```E   RuntimeError: 
E           CUDA Setup failed despite GPU being available. Please run the following command to get more information:
E   
E           python -m bitsandbytes
E   
E           Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
E           to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
E           and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
------------------------------------------------------------------------------------------------------------------------------------------------- Captured stdout -------------------------------------------------------------------------------------------------------------------------------------------------
False

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {PosixPath('/nix/var/nix/profiles/default /home/optimus/.nix-profile')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so)
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121
python setup.py install
================================================================================================================================================ warnings summary =================================================================================================================================================
../conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166
  /home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run
  
  python -m bitsandbytes
  
  
    warn(msg)

```

**Comment by Titus-von-Koeller** [comment]
@Windrider30 Did you go through the solution steps? When did this issue start occurring? Did anything change, i.e. bnb/pytorch version, CUDA driver, CUDA installation?

@poedator's issue has to be unrelated, since `0.41.3.post1` was released only 4 hours ago. @poedator, could you please run python -m bitsandbytes? On your system everything stayed the same then?

**Comment by poedator** [comment]
@Titus-von-Koeller, I installed and tested 0.41.3.post1 right after you published it and sent me a message at trasnformers github.
### here is my output with 0.41.3.post1:
```
$ python -m bitsandbytes
False

===================================BUG REPORT===================================
/home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
/home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/optimus/conda/envs/py38 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/optimus/local/cuda-11.8/lib64/libcudart.so'), PosixPath('/home/optimus/local/cuda-11.8/lib64/libcudart.so.11.0')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
/home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: :/home/optimus/local/cuda-11.8/lib64:/home/optimus/local/cuda-11.8/lib64:/home/optimus/local/cuda-11.8/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('25078'), PosixPath('//localhost'), PosixPath('http')}
The following directories listed in your path were found to be non-existent: {PosixPath('/nix/var/nix/profiles/default /home/optimus/.nix-profile')}
The following directories listed in your path were found to be non-existent: {PosixPath('se=\\E[23m'), PosixPath('cl=\\E[H\\E[J'), PosixPath('%e=\\E[5;2~'), PosixPath('k6=\\E[17~'), PosixPath('k0=\\E[10~'), PosixPath('nw=\\EE'), PosixPath('sr=\\EM'), PosixPath('k9=\\E[20~'), PosixPath('kP=\\E[5~'), PosixPath('k3=\\EOR'), PosixPath('kB=\\E[Z'), PosixPath('*7=\\E[1;2F'), PosixPath('cd=\\E[J'), PosixPath('F1=\\E[23~'), PosixPath('it#8'), PosixPath('pt'), PosixPath('k;=\\E[21~'), PosixPath('%i=\\E[1;2C'), PosixPath('me=\\E[m'), PosixPath('AB=\\E[4%dm'), PosixPath('ta=^I'), PosixPath('ei=\\E[4l'), PosixPath('op=\\E[39;49m'), PosixPath('FA=\\E[19;2~'), PosixPath('dc=\\E[P'), PosixPath('mi'), PosixPath('le=^H'), PosixPath('as=\\E(0'), PosixPath('kR=\\E[1;2A'), PosixPath('up=\\EM'), PosixPath('AX'), PosixPath('mr=\\E[7m'), PosixPath('ku=\\EOA'), PosixPath('po=\\E[5i'), PosixPath('kF=\\E[1;2B'), PosixPath('kN=\\E[6~'), PosixPath('@1=\\E[1~'), PosixPath('rs=\\Ec'), PosixPath('te=\\E[?1049l'), PosixPath('Co#8'), PosixPath('AL=\\E[%dL'), PosixPath('#2=\\E[1;2H'), PosixPath('ce=\\E[K'), PosixPath('xv'), PosixPath('ae=\\E(B'), PosixPath('km'), PosixPath('so=\\E[3m'), PosixPath('F6=\\E[1;2S'), PosixPath('kl=\\EOD'), PosixPath('rc=\\E8'), PosixPath('k8=\\E[19~'), PosixPath('FB=\\E[20;2~'), PosixPath('dl=\\E[M'), PosixPath('UP=\\E[%dA'), PosixPath('F4=\\E[1;2Q'), PosixPath('k5=\\E[15~'), PosixPath('SC|screen.xterm-256color|VT 100/ANSI X3.64 virtual terminal'), PosixPath('@7=\\E[4~'), PosixPath('F7=\\E[15;2~'), PosixPath('RI=\\E[%dC'), PosixPath('im=\\E[4h'), PosixPath('kh=\\E[1~'), PosixPath('li#41'), PosixPath('vi=\\E[?25l'), PosixPath('pa#64'), PosixPath('F8=\\E[17;2~'), PosixPath('nd=\\E[C'), PosixPath('#3=\\E[2;2~'), PosixPath('kI=\\E[2~'), PosixPath('FD=\\E[23;2~'), PosixPath('LE=\\E[%dD'), PosixPath('*4=\\E[3;2~'), PosixPath('mb=\\E[5m'), PosixPath('F5=\\E[1;2R'), PosixPath('ke=\\E[?1l\\E>'), PosixPath('ue=\\E[24m'), PosixPath('cm=\\E[%i%d;%dH'), PosixPath('kd=\\EOB'), PosixPath('am'), PosixPath('Km=\\E[M'), PosixPath('mh=\\E[2m'), PosixPath('k2=\\EOQ'), PosixPath('K2=\\EOE'), PosixPath('F3=\\E[1;2P'), PosixPath('k4=\\EOS'), PosixPath('DL=\\E[%dM'), PosixPath('kb=\x7f'), PosixPath('ac=\\140\\140aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~..--++,,hhII00'), PosixPath('ks=\\E[?1h\\E='), PosixPath('vb=\\Eg'), PosixPath('DC=\\E[%dP'), PosixPath('#4=\\E[1;2D'), PosixPath('G0'), PosixPath('DO=\\E[%dB'), PosixPath('do=^J'), PosixPath('k1=\\EOP'), PosixPath('\\\n\t'), PosixPath('is=\\E)0'), PosixPath('bs'), PosixPath('xn'), PosixPath('%c=\\E[6;2~'), PosixPath('bt=\\E[Z'), PosixPath('ms'), PosixPath('AF=\\E[3%dm'), PosixPath('k7=\\E[18~'), PosixPath('ct=\\E[3g'), PosixPath('ve=\\E[34h\\E[?25h'), PosixPath('kD=\\E[3~'), PosixPath('kH=\\E[4~'), PosixPath('FE=\\E[24;2~'), PosixPath('cr=^M'), PosixPath('ho=\\E[H'), PosixPath('bl=^G'), PosixPath('sc=\\E7'), PosixPath('ti=\\E[?1049h'), PosixPath('IC=\\E[%d@'), PosixPath('cs=\\E[%i%d;%dr'), PosixPath('co#172'), PosixPath('al=\\E[L'), PosixPath('vs=\\E[34l'), PosixPath('us=\\E[4m'), PosixPath('F9=\\E[18;2~'), PosixPath('md=\\E[1m'), PosixPath('F2=\\E[24~'), PosixPath('FC=\\E[21;2~'), PosixPath('st=\\EH'), PosixPath('pf=\\E[4i'), PosixPath('kr=\\EOC'), PosixPath('LP')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so)
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121
python setup.py install
Traceback (most recent call last):
  File "/home/optimus/conda/envs/py38/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/optimus/conda/envs/py38/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/optimus/conda/envs/py38/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

**Comment by Windrider30** [comment]
> @Windrider30 Did you go through the solution steps? When did this issue start occurring? Did anything change, i.e. bnb/pytorch version, CUDA driver, CUDA installation?
> 
> @poedator's issue has to be unrelated, since `0.41.3.post1` was released only 4 hours ago. @poedator, could you please run `python -m bitsandbytes` and post the results here? On your system everything stayed the same then?
> 
> Two things that catch my eye in your case are that `/usr/local/cuda/lib64/libcudart.so` doesn't seem to be in the `LD_LIBRARY_PATH` and that
> 
> ```
> CUDA SETUP: Loading binary /home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...
> /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so)
> ```
> 
> which to me means there's a version mismatch.
> 
> Please check `ldd /home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so`
> 
> and `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX`.

I went trhough unstailled EVERYTHING including python reinstalled step by step and still hit the same issue, but what is weird as hell is on my main pc (same set up for everything) it works fine someone said it could be the way torch was loaded but still no joy in mudville and I dont even know why it started having this issue in the first place. But so far i am still getting the same error  and not sure what to do hell can't even run  the bat file on auto111 keeps locking the lap top up for some reason .

**Comment by poedator** [comment]
@Windrider30, below it the command output.
I have system Driver Version: 535.104.12, CUDA Driver Version: 12.2, and cuda 11.8 in my conda env.
Even if there is a mismatch or whatever else - what is different btw 0.41..3 and 0.41.3.1 so it fails?

```
ldd /home/optimus/conda/envs/py38/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
        linux-vdso.so.1 (0x00007fffe6987000)
        libcudart.so.12 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12 (0x00007f33bd897000)
        libcublas.so.12 => /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.12 (0x00007f33b70d3000)
        libcublasLt.so.12 => /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.12 (0x00007f3394186000)
        libcusparse.so.12 => /usr/local/cuda/targets/x86_64-linux/lib/libcusparse.so.12 (0x00007f33843e6000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f338405d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3383cbf000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3383aa7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f33836b6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f33beaf3000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f33834b2000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3383293000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f338308b000)
        libnvJitLink.so.12 => /usr/local/cuda/targets/x86_64-linux/lib/libnvJitLink.so.12 (0x00007f337fec3000)

strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_DEBUG_MESSAGE_LENGTH

```

**Comment by Titus-von-Koeller** [comment]
@poedator Ok, do I understand you correctly that you changed nothing else and 0.41.3.post1 failed. Then you downgraded to 0.41.3 and it works fully again? Actually the only thing that (should have) changed are two lines in Params4bit.. Nothing to do with the setup logic at all. Please confirm this.

Will look at the ldd output with fresh eyes tmr.

@Windrider30 For you, could you please confirm that it also doesn't work with pinning to the bnb version that worked for you before?

> I went trhough unstailled EVERYTHING including python reinstalled step by step and still hit the same issue

But to me this doesn't seem related to the Python + bnb install, but to the cuda install or bnbs lack of finding it. 

Do computations work fine with vanilla PyTorch on GPU?

> Did you go through the solution steps?

```
What I mean by this is the steps proposed in the debug output:

CUDA SETUP: CUDA detection failed! Possible reasons:

You need to manually override the PyTorch CUDA version. Please see: "https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA driver not installed
CUDA not installed
You have multiple conflicting CUDA libraries
Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with make CUDA_VERSION=DETECTED_CUDA_VERSION for example, make CUDA_VERSION=113.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via conda list | grep cuda.
================================================================================
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is in found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
```

**Comment by poedator** [comment]
> @poedator Ok, do I understand you correctly that you changed nothing else and 0.41.3.post1 failed. Then you downgraded to 0.41.3 and it works fully again? Actually the only thing that (should have) changed are two lines in Params4bit.. Nothing to do with the setup logic at all. Please confirm this.

@Titus-von-Koeller this is correct. I only uninstalled different versions of bnb into the same env.

I also tried to install both versions into my other env with older cuda==11.8. same results (post1 craches). [logs here](https://hastebin.com/share/luburanepa.bash)

is it possible that the two versions placed to _pypi_ were compiled differently?

I tried to install the latest bnb from sources using cuda 11.8 env - it worked fine. [logs here](https://hastebin.com/share/omazoyopuw.bash)

**Comment by Titus-von-Koeller** [comment]
Well, the only difference is that the very last one (post1) was compiled on my dev machine, according to Tim's instructions, whereas all the prior ones were compiled by Tim on his.

At this point, I would like to pull in @TimDettmers, even though he's pretty busy these days. Let's see if we can get a hold of him despite NeurIPS..

**Comment by Titus-von-Koeller** [comment]
Ok, Tim got back to me and has just pushed a new patch. @poedator, could you please verify if it is working for you now?

According to Tim, there seems to have been a compiler version mismatch between the g++ version I used for compiling and the GCC version available on the users' systems: The software was developed using GCC version 9.1. However, some users, particularly those on Ubuntu 18.04, might have older versions of GCC by default (e.g., GCC 7.4), leading to compatibility issues.

If the CUDA library is compiled with a newer C++ standard than what is available on the user's system, it results in runtime errors.

I saw in your logs that you're on NixOS? I thought that means that such toolchains are more bleeding edge? In that light it's surprising to me that you'd have an older gcc.

Please let me know your thoughts and if Tim's republishing solved the issue.

**Comment by poedator** [comment]
Hi, @Titus-von-Koeller ,
the fresh 0.41.3.post2 works OK. Thanks to you and @TimDettmers for the quick reaction.
My system is a big shared server with Ubuntu 18.04 and tons of stuff. perhaps it is time for distro upgrade, yet so many reasons to postpone it.
