### ISSUE TITLE
Training with 0 Steps

### ISSUE THREAD

**Issue by Ijsanher** [TimDettmers/bitsandbytes#96]
Hi! iIm trying to train my Models with my photos but  It doesnt work. The proccess completes his normal work but it doesnt get training at all. This is the log in the end.

Thanks ins advance!

Starting Dreambooth training...
 VRAM cleared.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Scheduler Loaded
 Allocated: 0.2GB
 Reserved: 0.2GB

Steps:   0%|                                                                                  | 0/1111 [00:00<?, ?it/s] Exception while training: 'Options' object has no attribute 'tag_drop_out'
 Allocated: 3.8GB
 Reserved: 3.9GB

Traceback (most recent call last):
  File "D:\AI_CONTROLLED_IMAGE\FINIS\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 954, in main
    for step, batch in enumerate(train_dataloader):
  File "D:\AI_CONTROLLED_IMAGE\FINIS\stable-diffusion-webui\venv\lib\site-packages\accelerate\data_loader.py", line 376, in __iter__
    current_batch = next(dataloader_iter)
  File "D:\AI_CONTROLLED_IMAGE\FINIS\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "D:\AI_CONTROLLED_IMAGE\FINIS\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\AI_CONTROLLED_IMAGE\FINIS\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\AI_CONTROLLED_IMAGE\FINIS\stable-diffusion-webui\venv\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\AI_CONTROLLED_IMAGE\FINIS\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 434, in __getitem__
    example["instance_prompt"] = self.text_getter.create_text(instance_prompt, instance_text)   #TODO: show the final prompt of the image currently being trained in the ui
  File "D:\AI_CONTROLLED_IMAGE\FINIS\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\finetune_utils.py", line 41, in create_text
    if shared.opts.tag_drop_out != 0:
  **File "D:\AI_CONTROLLED_IMAGE\FINIS\stable-diffusion-webui\modules\shared.py", line 433, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'tag_drop_out'**
 CLEANUP:
 Allocated: 3.8GB
 Reserved: 3.9GB

 Cleanup Complete.
 Allocated: 3.8GB
 Reserved: 3.9GB

**Steps:   0%|                                                                                  | 0/1111 [00:00<?, ?it/s]
 Training completed, reloading SD Model.
 Allocated: 0.0GB
 Reserved: 3.8GB**

Memory output: {'VRAM cleared.': '0.0/0.0GB', 'Training completed, reloading SD Model.': '0.0/3.8GB'}
Re-applying optimizations...
Returning result: Training finished. Total lifetime steps: 0

**Comment by vixound** [comment]
same

**Comment by TimDettmers** [comment]
Sorry I cannot help you with this, since it seems to be an issue in the DreamBooth code. Maybe updating all related software libraries could help. Good luck!

Closing this, since it is not related to bitsandbytes.
