### ISSUE TITLE
CUDA Setup failed despite GPU being available

### ISSUE THREAD

**Issue by omarnj-lab** [TimDettmers/bitsandbytes#966]
### System Info

ubuntu 2022
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

### Reproduction

from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments

got this error : 

False

===================================BUG REPORT===================================
================================================================================
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda-11.8/lib64')}
The following directories listed in your path were found to be non-existent: {PosixPath('@/tmp/.ICE-unix/2351329,unix/lambda-hyperplane'), PosixPath('local/lambda-hyperplane')}
The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-ubuntu')}
The following directories listed in your path were found to be non-existent: {PosixPath('1'), PosixPath('0')}
The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/e30de06d_2a37_4aad_b119_a930085ee5ce')}
The following directories listed in your path were found to be non-existent: {PosixPath('unix'), PosixPath('path=/run/user/1000/bus,guid=27210033eac86f942c4dbe3e65888953')}
The following directories listed in your path were found to be non-existent: {PosixPath('//matplotlib_inline.backend_inline'), PosixPath('module')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/cuda/lib64')}
DEBUG: Possible options found for libcudart.so: set()
CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
libcusparse.so.11: cannot open shared object file: No such file or directory
CUDA SETUP: Problem: The main issue seems to be that the main CUDA runtime library was not detected.
CUDA SETUP: Solution 1: To solve the issue the libcudart.so location needs to be added to the LD_LIBRARY_PATH variable
CUDA SETUP: Solution 1a): Find the cuda runtime library via: find / -name libcudart.so 2>/dev/null
CUDA SETUP: Solution 1b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_1a
CUDA SETUP: Solution 1c): For a permanent solution add the export from 1b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Solution 2: If no library was found in step 1a) you need to install CUDA.
CUDA SETUP: Solution 2a): Download CUDA install script: wget https://github.com/TimDettmers/bitsandbytes/blob/main/cuda_install.sh
CUDA SETUP: Solution 2b): Install desired CUDA version to desired location. The syntax is bash cuda_install.sh CUDA_VERSION PATH_TO_INSTALL_INTO.
CUDA SETUP: Solution 2b): For example, "bash cuda_install.sh 113 ~/local/" will download CUDA 11.3 and install into the folder ~/local
/home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

  warn(msg)
/home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/akoubaa/anaconda3/envs/arabic_llm did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: :/usr/local/cuda-11.8/lib64 did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:5                                                                                    │
│                                                                                                  │
│   2                                                                                              │
│   3 import torch                                                                                 │
│   4 from datasets import load_dataset, Dataset                                                   │
│ ❱ 5 from peft import LoraConfig, AutoPeftModelForCausalLM                                        │
│   6 from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, Traini     │
│   7 from trl import SFTTrainer                                                                   │
│   8 import os                                                                                    │
│                                                                                                  │
│ /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/peft/__init__.py:22 in       │
│ <module>                                                                                         │
│                                                                                                  │
│   19                                                                                             │
│   20 __version__ = "0.3.0.dev0"                                                                  │
│   21                                                                                             │
│ ❱ 22 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_    │
│   23 from .peft_model import (                                                                   │
│   24 │   PeftModel,                                                                              │
│   25 │   PeftModelForCausalLM,                                                                   │
│                                                                                                  │
│ /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/peft/mapping.py:16 in        │
│ <module>                                                                                         │
│                                                                                                  │
│    13 # See the License for the specific language governing permissions and                      │
│    14 # limitations under the License.                                                           │
│    15                                                                                            │
│ ❱  16 from .peft_model import (                                                                  │
│    17 │   PeftModel,                                                                             │
│    18 │   PeftModelForCausalLM,                                                                  │
│    19 │   PeftModelForSeq2SeqLM,                                                                 │
│                                                                                                  │
│ /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/peft/peft_model.py:31 in     │
│ <module>                                                                                         │
│                                                                                                  │
│     28 from transformers.modeling_outputs import SequenceClassifierOutput, TokenClassifierOutpu  │
│     29 from transformers.utils import PushToHubMixin                                             │
│     30                                                                                           │
│ ❱   31 from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder              │
│     32 from .utils import (                                                                      │
│     33 │   TRANSFORMERS_MODELS_TO_PREFIX_TUNING_POSTPROCESS_MAPPING,                             │
│     34 │   WEIGHTS_NAME,                                                                         │
│                                                                                                  │
│ /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/peft/tuners/__init__.py:20   │
│ in <module>                                                                                      │
│                                                                                                  │
│   17 # See the License for the specific language governing permissions and                       │
│   18 # limitations under the License.                                                            │
│   19                                                                                             │
│ ❱ 20 from .lora import LoraConfig, LoraModel                                                     │
│   21 from .p_tuning import PromptEncoder, PromptEncoderConfig, PromptEncoderReparameterizatio    │
│   22 from .prefix_tuning import PrefixEncoder, PrefixTuningConfig                                │
│   23 from .prompt_tuning import PromptEmbedding, PromptTuningConfig, PromptTuningInit            │
│                                                                                                  │
│ /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/peft/tuners/lora.py:36 in    │
│ <module>                                                                                         │
│                                                                                                  │
│    33                                                                                            │
│    34                                                                                            │
│    35 if is_bnb_available():                                                                     │
│ ❱  36 │   import bitsandbytes as bnb                                                             │
│    37                                                                                            │
│    38                                                                                            │
│    39 @dataclass                                                                                 │
│                                                                                                  │
│ /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/bitsandbytes/__init__.py:6   │
│ in <module>                                                                                      │
│                                                                                                  │
│    3 # This source code is licensed under the MIT license found in the                           │
│    4 # LICENSE file in the root directory of this source tree.                                   │
│    5                                                                                             │
│ ❱  6 from . import cuda_setup, utils, research                                                   │
│    7 from .autograd._functions import (                                                          │
│    8 │   MatmulLtState,                                                                          │
│    9 │   bmm_cublas,                                                                             │
│                                                                                                  │
│ /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/bitsandbytes/research/__init │
│ __.py:1 in <module>                                                                              │
│                                                                                                  │
│ ❱ 1 from . import nn                                                                             │
│   2 from .autograd._functions import (                                                           │
│   3 │   switchback_bnb,                                                                          │
│   4 │   matmul_fp8_global,                                                                       │
│                                                                                                  │
│ /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/bitsandbytes/research/nn/__i │
│ nit__.py:1 in <module>                                                                           │
│                                                                                                  │
│ ❱ 1 from .modules import LinearFP8Mixed, LinearFP8Global                                         │
│   2                                                                                              │
│                                                                                                  │
│ /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/bitsandbytes/research/nn/mod │
│ ules.py:8 in <module>                                                                            │
│                                                                                                  │
│    5 from torch import Tensor, device, dtype, nn                                                 │
│    6                                                                                             │
│    7 import bitsandbytes as bnb                                                                  │
│ ❱  8 from bitsandbytes.optim import GlobalOptimManager                                           │
│    9 from bitsandbytes.utils import OutlierTracer, find_outlier_dims                             │
│   10                                                                                             │
│   11 T = TypeVar("T", bound="torch.nn.Module")                                                   │
│                                                                                                  │
│ /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/bitsandbytes/optim/__init__. │
│ py:6 in <module>                                                                                 │
│                                                                                                  │
│    3 # This source code is licensed under the MIT license found in the                           │
│    4 # LICENSE file in the root directory of this source tree.                                   │
│    5                                                                                             │
│ ❱  6 from bitsandbytes.cextension import COMPILED_WITH_CUDA                                      │
│    7                                                                                             │
│    8 from .adagrad import Adagrad, Adagrad8bit, Adagrad32bit                                     │
│    9 from .adam import Adam, Adam8bit, Adam32bit, PagedAdam, PagedAdam8bit, PagedAdam32bit       │
│                                                                                                  │
│ /home/akoubaa/anaconda3/envs/arabic_llm/lib/python3.9/site-packages/bitsandbytes/cextension.py:2 │
│ 0 in <module>                                                                                    │
│                                                                                                  │
│   17 │   if lib is None and torch.cuda.is_available():                                           │
│   18 │   │   CUDASetup.get_instance().generate_instructions()                                    │
│   19 │   │   CUDASetup.get_instance().print_log_stack()                                          │
│ ❱ 20 │   │   raise RuntimeError('''                                                              │
│   21 │   │   CUDA Setup failed despite GPU being available. Please run the following command     │
│   22 │   │                                                                                       │
│   23 │   │   python -m bitsandbytes                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

### Expected behavior

Whenever I want to do Finetuning of LLMs, my whole project could not be completed because of this !! I could not find any solution to this problem that is always appear ! please I need to run this on my current CUDA but I do not know how ! Any help ?

**Comment by ghostpepper108** [comment]
The bitandbytes support specific cuda versions. Run 

```
import torch
print(torch.version.cuda)

```
Lets say cuda version is 11.6 then you install `pip install bitsandbytes-cuda116`. You can use the following versions

CUDA_VERSIONS {110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 120}

**Comment by SatishKKumar** [comment]
I have been facing similar issue with bitsandbytes, even after trying the pip install bitsandbytes-cuda117. 

It is leading to different issue. 
"WARNING! This version of bitsandbytes is deprecated. Please switch to `pip install bitsandbytes` and the new repo: https://github.com/TimDettmers/bitsandbytes".

AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear8bitLt'.

**Comment by witness-xue** [comment]
same issue i met. any one can help me?

===================================BUG REPORT===================================
/data/conda/envs/xx/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:167: UserWarning: Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes


  warn(msg)
================================================================================
/data/conda/envs/xx/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:167: UserWarning: /data/conda/envs/xx did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The following directories listed in your path were found to be non-existent: {PosixPath('//127.0.0.1'), PosixPath('http'), PosixPath('5001')}
The following directories listed in your path were found to be non-existent: {PosixPath('//127.0.0.1'), PosixPath('http'), PosixPath('5001')}
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching in backup paths...
/data/conda/envs/xx/lib/python3.11/site-packages/bitsandbytes/cuda_setup/main.py:167: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}.. We select the PyTorch default libcudart.so, which is {torch.version.cuda},but this might missmatch with the CUDA version that is needed for bitsandbytes.To override this behavior set the BNB_CUDA_VERSION=<version string, e.g. 122> environmental variableFor example, if you want to use the CUDA version 122BNB_CUDA_VERSION=122 python ...OR set the environmental variable in your .bashrc: export BNB_CUDA_VERSION=122In the case of a manual override, make sure you set the LD_LIBRARY_PATH, e.g.export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.2
  warn(msg)
DEBUG: Possible options found for libcudart.so: {PosixPath('/usr/local/cuda/lib64/libcudart.so'), PosixPath('/usr/local/cuda/lib64/libcudart.so.11.0')}
CUDA SETUP: PyTorch settings found: CUDA_VERSION=121, Highest Compute Capability: 8.0.
CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md
CUDA SETUP: Loading binary /data/conda/envs/xx/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...
libcusparse.so.12: cannot open shared object file: No such file or directory
CUDA SETUP: Something unexpected happened. Please compile from source:
git clone https://github.com/TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=121
python setup.py install
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/data/conda/envs/xx/lib/python3.11/site-packages/bitsandbytes/__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "/data/conda/envs/xx/lib/python3.11/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>
    from . import nn
  File "/data/conda/envs/xx/lib/python3.11/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "/data/conda/envs/xx/lib/python3.11/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "/data/conda/envs/xx/lib/python3.11/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "/data/conda/envs/xx/lib/python3.11/site-packages/bitsandbytes/cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues

**Comment by MatthiasKohl** [comment]
Since you're getting `libcusparse.so.12: cannot open shared object file: No such file or directory` this seems to be an issue with your CUDA install.
Can you ensure that CUDA is correctly installed, and then follow instructions such as the ones suggested at the end of this issue to install bitsandbytes from source: https://github.com/TimDettmers/bitsandbytes/issues/1042 ?

**Comment by Rehan018** [comment]
/workspace/SFT_FineTuning  master ✗                      ◒  
▶ python model_deployment/service.py
==============================WARNING: DEPRECATED!==============================
WARNING! This version of bitsandbytes is deprecated. Please switch to `pip install bitsandbytes` and the new repo: https://github.com/TimDettmers/bitsandbytes
==============================WARNING: DEPRECATED!==============================
/workspace/SFT_FineTuning/sft_venv/lib/python3.8/site-packages/transformers/integrations/peft.py:418: FutureWarning: The `active_adapter` method is deprecated and will be removed in a future version.
  warnings.warn(
(sft_venv) (base) 
/workspace/SFT_FineTuning  master ✗

**Comment by TimDettmers** [comment]
Closing this issue. The CUDA detection system (`cuda_setup/main.py`) used in bitsandbytes 0.41.x–0.42.x was fragile and had known bugs — it could fail to find CUDA libraries even when they were correctly installed, particularly in conda environments, Docker containers, and systems with multiple CUDA versions. That entire module was replaced starting in v0.43.0 with a more robust library loading mechanism.

If you're still hitting CUDA setup problems on the **latest** bitsandbytes (v0.45+), please open a new issue with the output of `python -m bitsandbytes` and your environment details (OS, Python version, PyTorch version, GPU).
