### ISSUE TITLE
Is bitsandbytes available on windows?

### ISSUE THREAD

**Issue by forhonourlx** [TimDettmers/bitsandbytes#972]
### System Info

windows 11, python 3.10.6 conda

### Reproduction

Traceback (most recent call last):
  File "d:\LLM\fingpt.py", line 11, in <module>
    from peft import PeftModel  # 0.5.0
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\peft\__init__.py", line 22, in <module>
    from .auto import (
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\peft\auto.py", line 31, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\peft\mapping.py", line 23, in <module>
    from .peft_model import (
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\peft\peft_model.py", line 38, in <module>
    from .tuners import (
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "C:\Users\Administrator\AppData\Roaming\Python\Python310\site-packages\peft\tuners\lora.py", line 45, in <module>
    import bitsandbytes as bnb
  File "C:\miniconda3\lib\site-packages\bitsandbytes\__init__.py", line 5, in <module>
    from .optim import adam
  File "C:\miniconda3\lib\site-packages\bitsandbytes\optim\__init__.py", line 5, in <module>
    from .adam import Adam, Adam8bit, Adam32bit
  File "C:\miniconda3\lib\site-packages\bitsandbytes\optim\adam.py", line 11, in <module>
    from bitsandbytes.optim.optimizer import Optimizer2State
  File "C:\miniconda3\lib\site-packages\bitsandbytes\optim\optimizer.py", line 6, in <module>
    import bitsandbytes.functional as F
  File "C:\miniconda3\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    lib = ct.cdll.LoadLibrary(os.path.dirname(__file__) + '/libbitsandbytes.so')
  File "C:\miniconda3\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\miniconda3\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 Win32 。

### Expected behavior

Is [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) available on windows?

**Comment by Titus-von-Koeller** [comment]
Dear all,

Since the current release (last week, 8th of March) we now have official support for Windows 🎉 (which we did not have before) via

```
pip install bitsandbytes>=0.43.0
```

We're closing all old Windows issues and are asking everyone to try installing with this new version as outlined above and validate the install with `python -m bitsandbytes` which should spit out a bunch of stuff and then `SUCCESS`. Please let us know if everything worked correctly in [this new umbrella / catch-all issue](https://github.com/TimDettmers/bitsandbytes/issues/1131). Thanks 🤗
